### ISSUE TITLE
EDD License not activating

### ISSUE THREAD

**Issue by rvmourik** [reduxframework/redux-framework#1120]
Hi,

After some hours of trial and error i managed to get an license field in one of my sections. But the next problem i can't seem to get solved.

Whatever license i put in the input it keeps on saying it's invalid, looking at the Ajax request it sends all the data to admin_ajax.php. 

The extension is not that well documented, so can anyone help?

Thanks in advance.

Robbert

**Comment by towfiqi** [comment]
any news on this guys?

**Comment by kprovance** [comment]
Here is the news:  We're very busy working on other projects that will - if successful - continue to fund the Redux project, because the other truth is, it's not supporting itself. That means - not to put too fine a point on it - low priority thing such as this aren't going to be addressed until 1) Redux becomes self supporting 2) Other projects were currently invested in do so instead of the thousand of devs who are making huge stacks of cash off Redux, and have giving back, literally nothing, in the big picture.

There is absolutely *nothing* stopping you, or anyone else from rolling up your sleeves and digging into these things for yourself, so that the entire community could benefit, versus the dozens of posts crying for fixes we're expected to provide, gratis.  Caveat: any fix must *not* break any backwards compatibility, which seems to be an ongoing problem with recent contributions.  Previous functionality MUST be respected, and that's about it.

Hope this clears up the state of affairs for the time being.

And that's currently where we are.

**Comment by towfiqi** [comment]
Please for the love of God, create a gratipay account a ask people for donation telling them exactly what you wrote here. People would love to fund the theme with a weekly payment. It will help redux support itself.

**Comment by kprovance** [comment]
Been there, done that.

**Comment by towfiqi** [comment]
You have a huge user base. You are just not reaching them. You guys should collect emails send them emails about the progress and hiccups of redux get users more involved. I know it sound a lot to do, but a little effort could get you where you want to be. Thanks. Let me know If I can help in anyway.

**Comment by kprovance** [comment]
Again, been there, tried that, *multiple* times.  We were mostly ignored and disregarded.  If you really want to help, fix the issues you find (without breaking compatibility) and submit pull requests.  Otherwise, be patient.

**Comment by dovy** [comment]
@towfiqi honestly we've tried a bunch. Let me tell you what we've done.

In the beginning our support and response to bugs were unparalleled. That's why we have such a following. We grew SO very quickly.

We sent out monthly newsletters. Each time we asked people to do a Paypal donation of at least $5/month. We had a total of 3 devs sign up, only 2 are still paying.

We had webinars and those brought us the most money in, but they were in the form of extension sales. Truth be told, people won't donate, but they'll purchase features.

Then we look at this and get a little sick with envy: http://reduxframework.com/showcase/envato/

Even people who are making $20,000 a month find it hard to donate even $100 every 4 months or so... rather confusing.

So we've decided to do what everyone else is doing, make a theme. We're in the process and we're starting our own design firm. The hope is that designers will team up with us and we can share revenue rather thank doing endless work for free.

So that's where we're at. We'll be starting newsletters and webinars back up after we've released a theme or two. We need cash flow, and the devs are just not providing it.

So if you have any other ideas we're all ears. It's just frustrating and we're a little burned by the community.
