### ISSUE TITLE
multiple Validation 

### ISSUE THREAD

**Issue by RodionBezruk** [reduxframework/redux-framework#1332]
Hello,

How I can set validation to field 'not_empty' and 'numeric' and etc.? 'validate' parameter must be as array. Let me know please if I can do it without create my custom validation function.

Thank you

**Comment by ehrig** [comment]
The numeric_not_empty validation triggers the error message when entering integer "0", which shouldn't happen, as "0" should be treated as an integer in that case, not "empty" as PHP interprets it.

Removing the empty check here should fix it: https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/inc/validation/numeric_not_empty/validation_numeric_not_empty.php#L30

**Comment by kprovance** [comment]
Should?  Did you try it?

**Comment by ehrig** [comment]
Yes, removing the empty check works. I am not eager to touch the core code, so I was proposing to ship this fix ;-)

Being able to chain multiple validations using an array, as @RodionBezruk suggested would be perfect. 

The alternative, writing custom validations for each possible validation combination creates a lot of redundancies, see email_not_empty, numeric_not_empty etc. Or does the validation chaining fail due to something I am not aware of?

**Comment by kprovance** [comment]
That would take a lot of work in core rewrites.  Maybe someday we'll get financial banking and I can do this full time.  Until then, I can put it on my 'would be nice' list.  :)

**Comment by ehrig** [comment]
Understood. Thanks for the quick reply, and keep up the good work Kevin!
