### ISSUE TITLE
Ace javascript error

### ISSUE THREAD

**Issue by ghostpool** [reduxframework/redux-framework#1529]
Hi there,

I'm using the latest version of framework (3.3.5.9). When the Visual Composer plugin (4.2.3) is activated the following error is generated:

Uncaught TypeError: Cannot read property 'ace/ace' of undefined

All plugins disabled.

I've also raised this issue with the VC developers.

**Comment by kriskhoury** [comment]
Can someone point me in the direction of the problem? 

Visual Composer: v5.1.1
Redux: v3.3.9.4
Wordpress: v4.8

**Comment by sqpp15** [comment]
@kriskhoury Did you manage to fix it? Got the same... but only like 1 months ago

**Comment by prafgon** [comment]
Hi guys,

I'm not sure if you guys use the CDN or not but if you DON'T then I found (I hope so) the source of the problem. The ace.js file located in the vendor extension is simply outdated and it has a priority over the one being used by the Visual Composer plugin (they updated it there) and that causes the error to appear. I just updated the ace.js file in the vendor plugin and the issue is gone.

Hope that helps?
