### ISSUE TITLE
Options lost after DB migration

### ISSUE THREAD

**Issue by tszilassi** [reduxframework/redux-framework#1823]
I do fair amount of web development (under my own domain on a dev server) and then upload the finished product to the client's hosting.

My workflow is:
1) Export the dev database
2) Replace the hard-coded URL references to the final domain name in the database dump (ex. replace test.com -> finaldomain.com)
3) Move the web files and adjust the wp-config.php according to the new database credentials

Quite standard procedure, however for some reason the ReduxFramework options needs to be re-imported after that, which is quite inconvenient. One would think moving the database and web files over would result in a perfect clone of the website. How are the options being stored, in what manner can such a migration break them? I filed this issue ticket because I believe it is not the expected behaviour, or am I doing some mistake in the process?

**Comment by roryatbrightoak** [comment]
I'm having the exact same issue. The site in question is a multisite installation, with each website having it's own redux options panel. I've verified that opt_name is the same, and that the data is still in the database, but on the new site, the options are not showing up.

**Comment by mihairepo** [comment]
You'll have to check your database export file and make sure if the domains don't perfectly match to find/replace everything to the correct form. Lots of options strings are escaped so this issue is not easily solvable. 

They way we eventually did is was to setup virtual domains and keep local working copies identical to the production websites. For our developers when they use domain.com it will load the local version while for general public using domain.com would load the production server.

This way, when we sync development with production nothing is lost.

**Comment by webraptor** [comment]
You'll have to check your database export file and make sure if the domains don't perfectly match to find/replace everything to the correct form. Lots of options strings are escaped so this issue is not easily solvable.

They way we eventually did is was to setup virtual domains and keep local working copies identical to the production websites. For our developers when they use domain.com it will load the local version while for general public using domain.com would load the production server.

This way, when we sync development with production nothing is lost.

**Comment by marpstar** [comment]
Just ran into this issue with Redux 3.5.9 when migrating from localhost to my staging server.  I was very careful about updating the DB with my new host name, but still fell into this.   

The fix is as easy as exporting your options from your working site and importing them into the non-working site, but it'd be nice if this issue would be looked into.  This is my first time with Redux and was absolutely loving it until I hit this roadblock.

**Comment by Letreiros** [comment]
Good afternoon!
The file imported.

**Comment by nr1q** [comment]
Hello everybody, I found the problem when doing migration (specially when dealing with domain names). I work in .test domains for development, so when I do a search/replace in the sql file, the serialized data gets corrupted if the replace affected some data inside the database, for example:

before the replace
```
s:5:"email";s:15:"mail@domain.com"
```

after the replace
```
s:5:"email";s:15:"mail@domain.test"
```

Notice that the `15` is not the length of the data so that breaks the internal wordpress mechanism that gets it from the database.

**Comment by AHTOXA86** [comment]
wp db can correct search-replace domain in serialized data:
https://developer.wordpress.org/cli/commands/search-replace/
