### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by krishna19** [ReduxFramework/redux-framework#1947]
Whenever i use info field, it adds more space before the the next field.

**Comment by krishna19** [comment]
i'm using Redux 3.3.9.31

**Comment by kprovance** [comment]
This is what I see with the info fields:

![info](https://cloud.githubusercontent.com/assets/3412363/5598789/2e5dabfc-928a-11e4-91f2-b7c1aa516b7c.png)

If it looks like this, it's normal.  Otherwise, you may need to post back a screen cap of what you're referring to, because some extra space is expected.

**Comment by krishna19** [comment]
Recently i update to 3.3.9.32. In this version also info field adds extra spaces.

![Issue](http://oi61.tinypic.com/f1cfax.jpg)
![Using Firebug](http://oi62.tinypic.com/o0ukx2.jpg)

Thanks

**Comment by kprovance** [comment]
What will it take to you get you to review the posting guidelines, so you'll post the relevant information?  You've given me nothing to work with.

**Comment by krishna19** [comment]
sorry, whenever i try to use info field it adds extra spaces below the info box. here's the code i use
<pre>
                    array(
                        'id'   => 'top_bar_social_info',
                        'type' => 'info',
                        'desc' => __( 'Social Media Options', 'wthemes' )
                    ),
</pre>
Redux Version : 3.3.9.32

**Comment by kprovance** [comment]
Added display:none to the TR tag in new push, as removing it breaks stuff.
