### ISSUE TITLE
PHP 5.2 Support not fully working

### ISSUE THREAD

**Issue by denbec** [ReduxFramework/redux-framework#1951]
According to the changelog, you fixed php support for version 5.2 in 3.3.9.27. Unfortunately, I'm getting (in a wordpress theme) the error:

Parse error: syntax error, unexpected T_STRING in [...]/ReduxFramework/ReduxCore/inc/scssphp/src/Colors.php on line 13

It starts with "namespace", I googled and I believe there is no namespace support in php 5.2. Is there any way to get this framework (and therefore the theme I bought) working with php 5.2?

**Comment by kprovance** [comment]
We're using the develop branch of scssphp, which no longer supports 5.2.  I guess we're going to have to go back to their master branch, since WP and hosts insist on living in the dark ages with the php 5.2 garbage.  Even so, I would HIGHLY recommend using a newer PHP version 5.2 still has security issues that will not ever be addressed.

**Comment by kprovance** [comment]
Updated in latest push to the git.
