### ISSUE TITLE
Git Version VS WP Org Version

### ISSUE THREAD

**Issue by raphaelkross** [ReduxFramework/redux-framework#1954]
Hi guys, simple question.

I'm currently requiring that the plugin Redux Framework be installed together with my themes,I'm embedding the version from wordpress.org version - I would like to know if I should instead use the Git version that looks more bleed-edging than the one from the WP repo, or it's completely fine using the older version from repo and any critical update will be added there when necessary?!

Thank you for you hard work guys! I hope all you had an awesome year's end!

Kind Regards.

**Comment by dovy** [comment]
If you have your users install the plugin, they'll get the updates when we roll them out. We're just holding off a little because we're testing thoroughly our SAAS compiler. Don't want to break user functionality.  :)

But you can also use the bleeding-edge version. We're pretty sure it's working well and it does have a bunch of bug fixes. We'll be rolling it out to WP.org this month though.  ;)

**Comment by dovy** [comment]
Oh and if you embed the new version AND use TGM to get them to install the plugin (and they do) they'll get the updates.  ;)

**Comment by raphaelkross** [comment]
Amazing! As I suspected, there's nothing wrong and I can keep working in the same way I'm doing right now!

Thank you for the really solid software you guys provide - all questions solved!

Kind Regards.

**Comment by dovy** [comment]
You're so welcome.

If you're happy with Redux please do some or all of the following:
* Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
* Like us: http://facebook.com/ReduxFramework
* Follow us: http://twitter.com/ReduxFramework

Oh and check out our extensions to take Redux to a whole new level! http://reduxframework.com/extensions/
