### ISSUE TITLE
Problem in color-rgba field 

### ISSUE THREAD

**Issue by Momizat** [ReduxFramework/redux-framework#1961]
In latest update i have problem with this field default color is #000 i can't change it and if i remove default color in this field and reset options does not change anything 
<pre>
 array(
'id' => 'br_bg',
'type' => 'color_rgba',
'title' => __('Option name', 'framework'),
'output' => array('.class'),
 'default'  => array( 
                'color' => '', 
                'alpha' => '' 
 ),
'mode' => 'background',
'validate' => 'colorrgba',
),
</pre>

Also i modify this file field_color_rgba.js and remove this color from here 
<pre>if (palette === null) {
            palette = [
                ["#000000", "#434343", "#666666", "#999999", "#b7b7b7", "#cccccc", "#d9d9d9", "#efefef", "#f3f3f3", "#ffffff"],
</pre>
 and reset options this black color removed but if i click on save options back again
how to fix this problem ?

**Comment by kprovance** [comment]
Okay, first, you don't want to be modifying the JS files.  It will be overwritten on updates.  You can modify the palette via it's argument, as documented here:  http://docs.reduxframework.com/core/fields/color-rgba/

I tried the code you provided.  A blank default string will give you a picker with no set color.  That is how it works.  I was able to change the color by selecting a new one and clicking Choose.  

I then set the default to #000, and reset section.  The picker set as black.  I selected red, clicked Choose and saved.  It saved a red.  I reset, it went back to black.  Everything works as expected.

If you are doing something different, then I need you to 1) Provide the information required by our posting guidelines (which you did not) and 2) Be WAY moe specific about what you are doing, because as it stands, the fields works as expected.

**Comment by Momizat** [comment]
Now if i want to make this option without defaults
<pre>
'default'  => array( 
                'color' => '', 
                'alpha' => '' 
 ),
</pre>
And i reset theme options and save it again this field take the black color, I think this is an error
From where comes this value ? I think in this case it must be without any values ?

**Comment by Momizat** [comment]
I think this problem resolved by removing this black color from field_color_rgba.php
<pre>
public function render() {
            $defaults = array(
                'color'     => '', //removed from here 
                'alpha'     => 1,
                'rgba'      => ''
            );
</pre>

**Comment by kprovance** [comment]
Weird, the default in my code is blank,, which explains why I can't reproduce this.  Go ahread and leave that default blank.  I'll make sure our core reflects the same in the next push.

**Comment by dovy** [comment]
Just pushed another fix for this. We found the reason. Pull from this repo.

**Comment by Momizat** [comment]
Thanks @dovy

**Comment by kprovance** [comment]
Technically, I was the one who fixed it.  :P

**Comment by Momizat** [comment]
And a big thanks to you @kprovance  :)

**Comment by KAJOJEK** [comment]
Hello, is  that possible that I can have the same problem now?  I use color_rgba in metabox extension I've set:
'default'   => array(
                    'color'     => '',
                    'alpha'     => ''
                ),

and always output color is 0,0,0;

redux version 3.6.0.2
metabox extension version 1.4.2
wp 4.7.3
