### ISSUE TITLE
404 Error when save the option settings

### ISSUE THREAD

**Issue by badjohnny** [ReduxFramework/redux-framework#1963]
I'm a wordpress theme author, a buyer purchased my theme which is based on Redux framework, but he got 404 error when he save the option setting, and his server is godaddy hosting, I've readed this issue https://github.com/ReduxFramework/redux-framework/issues/1852  But still not found the solution.

He contact godaddy support and they said "Upon primary investigation, they could see that the domain eventswizard.net was blocked due to Mod security rules in our server. file "/usr/local/apache/conf/modsec_rules/10_asl_rules.conf" msg "Atomicorp.com WAF Rules: Generic Path Recursion denied""] severity "CRITICAL" uri "/2015/wp-admin/options.php"   " 

"Please do contact the web developer to optimize the web page source code to avoid this issue in future."

Is there any solution?

Thanks!

**Comment by kprovance** [comment]
Okay, here is the reality:  GoDaddy, as a Wordpress solution is as awful as it gets.  They claim they are WP friendly, but are the farthest thing from.  As you have seen first hand, they have WAY too many too-strict rules in place that chokes WP, plugins, themes, etc.  The other reality is we cannot rewrite our entire core to satisfy GoDaddy's tyrannical rules.  They're passing the buck to developers when the problems are theirs.  It's not something we can 'fix', per se, and the ugly truth is, their overly strict guidelines are not really our problem.  That said, if you're willing to pay our premium support rate, and provide WP and FTP access to your client's server, we could do some debugging there.  But because GoDaddy is such a mess, no promises can be made.  No joke, the best solution is to dump GoDaddy and move to a truly WP friendly host.  BlueHost (for which I receive no compensation for suggesting them) has some of the most inexpensive plans out there, and I've been with them for almost a decade now.  Never once had a problem with ANY WP install.

**Comment by badjohnny** [comment]
Hi

Thanks for fast reply, and how much about the premium support rate? If it's expensive, maybe I will tell the buyer to change the webhosting.

Thanks

**Comment by kprovance** [comment]
It's $75.00 an hour.  @Dovy would probably be doing it, since he's WAY better at debugging those things than I.  There is a time considering however, as we are days away from a theme release.  It's probably not something we/he would be able to get until next week.

**Comment by badjohnny** [comment]
OK, thanks! I will tell the buyers.

**Comment by badjohnny** [comment]
Oh, sorry, just one last question,  is it too hard to debug it? Or is it need to change too many php files?

**Comment by kprovance** [comment]
Honestly, I have no idea where to begin looking in terms of debugging.  See if you can get access to the error log where PHP errors are logged to, and start from there.  Assuming GoDaddy even offers such a thing.
