### ISSUE TITLE
Site unconfigured after saving changes to the Theme Panel

### ISSUE THREAD

**Issue by walkernolasco** [ReduxFramework/redux-framework#1965]
After making changes to the Theme Panel and click "Save", my site is completely unconfigured. I believe it is something with unserialize, because when I replace the wp_options table database with an earlier version to the rescue, everything returns to normal.

This prevents me from making any changes by Theme Panel. Can anyone help me?

**Comment by dovy** [comment]
Hello there, I need to know more details.

First, are you a developer or a user? Did you buy a theme from someone? If so, this is for their support boards...

**Comment by walkernolasco** [comment]
Yes, i am the developer. I bought the theme RealEstast Responsive Real Estate WordPress Theme (http://themeforest.net/item/realestast-responsive-real-estate-wordpress-theme/4740027?WT.oss_phrase=real%20estate&WT.oss_rank=22&WT.z_author=pixelgeeklab&WT.ac=search_list).

**Comment by kprovance** [comment]
You're the developer, and you bought your own theme?  I'm sorry, but it's one or the other.

As pointed out, you need to contact the author of that theme (pixelgeeklab) and report this issue to him.  They are the one(s) who need to do the debugging.  This is not a widespread issue, otherwise, we'd have thousand upon thousand of tickets reporting the same thing, which is not the case.

**Comment by walkernolasco** [comment]
I'm developer and owner. What's the problem?

Well, i figured this would happen. Never buy anything that has something of you.

Support fails.

**Comment by dovy** [comment]
Haha. We're an open source project. We did not get paid a penny for you buying the theme. Your theme creator is the one who owes you support. The problem is in their code not ours. We can only tell you the truth. 

Best of luck!

**Comment by kprovance** [comment]
You said you were the developer of that real estate theme, but yet you bought it?  So you are the individual who wrote the code for that real estate theme?  

You do understand that we, Redux, are NOT that theme's author.  We do not support actual themes that use our framework, which is why you need to contact the author of that theme.  Asking us to support themes that use our framework is unrealistic.  If the author of that theme is having an issue, they need to contact us.  Users of their theme need to contact the author.  That's how it works.
