### ISSUE TITLE
TO ALL DEVS - PLEASE HELP

### ISSUE THREAD

**Issue by dovy** [reduxframework/redux-framework#1966]
Many of our developers have told us that getting started with Redux is very painful at best. We need your help.

We want to improve our getting started documentation, but that means we need you! To us the documentation is quite clear, to others not so much.

We want the community to gather round and make the getting started guide easier. We want this to be as simple to use as anything else out there.

Please help and submit like a http://gist.github.com with this in mind. Any amount of help you can provide will be greatly appreciated.

Thanks!

**Comment by daithi-coombes** [comment]
:+1: going to be putting time to learn redux from next tuesday (backlog of features to complete first).

**Comment by danyj** [comment]
OK , here are few things that pushed  me away from redux , do not take it personal 

1. No download link, on redux website
http://www.uploady.com/#!/download/4zk4Hjd68Ek/7ng538RtPQBM_AFd
should be there somewhere or a git link, I see you saying something about it but is not there
2. Your registration is pain, does not work , cant register not getting emails yet you tell us  to use 
Redux Builder which we cant access.  

3. where is a start here?
http://docs.reduxframework.com/
what is redux a plugin , an option framework to be used from  the theme, 
where do I start as developer ?

4. is this how product demo should look like ?
http://redux.wpdemo.io/?preview&utm_referrer=http%3A%2F%2Freduxframework.com%2F
and what exactly can I see there ?
oh , I missed the text  on top right because I dont look at  the way top right on 27" screen, 
I look in the mid of the screen trying to figure out what to do next. My bad , my fault that I cant see the gray letters on white bg. 
suggestion , make blank page , with HUGE colored ( action ) button that says start here , I am a dumb developer who needs help from you and I am lazy to build my own options framework, so please lead me, dont make me guess. 

5. your git looks unorganized and not well  thought trough. You have core folder but the main class is outside, you check for class existence instead of a simple autoload and few more unusable coding practices that others have previously addressed.  

6. that demo is heavyyyyyy and slow. 
AWESOME options but looks like way to many and again unorganized. 

I see that this is a group of brilliant developers but guys, remember, you are doing this for lazy developers who just want to get on with the main thing and that is theme development and many of us look for these options;

1. Simple form elements, radios, selects, textareas, etc. 
2. page builder

that is all we need. So if you trow so many things at us that we wont use,  many of us will say this is to much.  

again dont take any of this  personal. I looked trough most sold themes and see that they all started with SMOF and you are fork of it so is only natural that I hoped to use redux but to be honest I am bit disappointed and reluctant to put in a work in to something that needs to be cleaned up.

**Comment by Jim-E** [comment]
I also had trouble with registration, it had some kind of errors or something and didn't think it created an account so I gave up. Came back a few days later and I guess it had created the account after all.

I tried to purchase an extension and you only take PayPal? And then I have to create a Paypal account? Not liking that at all. So I backed out of the purchase and now it's stuck in my Redux account as pending with no way (that I can find) to add it back to the cart and delete it or checkout. 
Stripe payments used to be free, not sure they still are but might be something to look at.
I'll just also mention that I make a lot of online purchases so I'm no amateur at buying stuff :). 

I hope to see Redux thrive so I'm mentioning these things with strictly good intentions.

**Comment by dovy** [comment]
@Jim-E @danyj I just realized our database had grown so much (users) that our PHP was hitting memory limits! Registration will now work properly. Sheesh, may need to increase our whole server soon. Sorry about that.

@Jim-E I'll look into getting us a stripe account. Shouldn't be too hard...

@danyj I appreciate the honest criticism. You're right, our website needs a bit of updating. The docs just need a better "let's get your started" document. I'll go through your items one at a time.

1. Yes, our website hasn't really changed in years, only our doc site has. That will be fixed hopefully this quarter.

2. You were right! I just fixed it. It should work perfectly now.

3. We assume, albeit perhaps wrongly, that anyone who comes to use Redux will be (at least in part) a basic developer. I am guessing you're speaking of those that do not fit into that category. It's hard to appease such diverse crowds. That's why, however, I wrote this post. I want the community to help us make a better getting started page.

4. Not really. I've been working on a new demo and it's almost done. Point taken.

5. Umm, our git is actually a plugin, but only the ReduxCore is needed. The builder as well as the WordPress plugin removes a ton of our debugging. We use things like Travis to do continual testing and PHP docs to make a doc site among other things. So I fear you're approaching Redux in the more advanced way. Perhaps you should start with the Plugin and go from there? Remember, Redux can run as a plugin or embedded. The builder gives you a nice small custom version if you use it. Now you can since registration is working again!

6. The demo is just to show every option off. I am totally open to suggestions here. If you have a better way to organize them, let me know. I'd love some input. Alas, people complain, but not many people are willing to contribute time to make things better.

While I agree people want simplicity, there are also people who are looking for more than 3 field types. Redux has over 30! That being said, with the builder you can reduce that to anything you want. We haven't entered the page builder space as of yet, but we will. Don't you worry.

Also we're not just a fork of SMOF, we are SMOF! We're Redux 2.0, SMOF, and NHP on steroids. We have the most widely adopted framework and we have every feature anyone could need. We just need to polish the edges for people who are less technical. Truly we'd love to improve. If you have ideas or are willing to contribute time, we would love the time.

And honestly, no offense taken at all. Thank you for taking the time.

**Comment by dovy** [comment]
@daithi-coombes look forward to your insight!

**Comment by danyj** [comment]
you must get a page builder. My opinion, without it the framework is incomplete.

**Comment by danyj** [comment]
still no luck with that registration/reset. no emails is coming when resetting, 
I used all my emails trying to signup so I cant reuse them

**Comment by dovy** [comment]
That means each account was setup. Give me all your emails and I will nuke them from the db. Then you can start anew.

**Comment by dovy** [comment]
Email me directly as to not have your emails get out there. dovy@reduxframework.com or Skype me: DovyDigital.

**Comment by FiGO-** [comment]
<em>"While I agree people want simplicity, there are also people who are looking for more than 3 field types. Redux has over 30! That being said, with the builder you can reduce that to anything you want. "</em>

Absolutely 100% agree! Do not reduce the options. I think that would be silly. I believe the keywords here are "options" framework not just "theme options" framework. I can pretty much use the framework for anything and as stated earlier you can simply control which options you wish to use or not use. That's ridiculously awesome IMO. Can't wait to release my first theme.

**Comment by TuxReports** [comment]
As a complete neophyte last year, but learning as fast as possible, redux framework was challenging for a few reasons.

1. Redux Builder has 3.3.6 stable and dev version is now 3.4.1. So I question, what happened to everything between because the link to releases shows numerous versions? Is 3.3.6 the last stable release? As a developer of a plugin, I'm expecting the latest stable to be obvious.

2. The documentation is very unclear. Consider the following:

"The opt_name variable can be found in your Redux configuration file. An example can be found in /sample/sample-config.php, included in the Redux plugin."

What you really mean is ...

The opt_name variable can be found two ways: in the WordPress wp_options table or in your Redux configuration file. You can find this file in the following places: ______. An example OF THIS FILE can be found in the folder /redux-framework/sample/sample-config.php. If you used the builder then an option-init.php file is also available....

Why is all of those details important? The docs section referenced is about opt_name. Are you suggesting an example of the opt_name is found in ..?  No, you are referencing the file to find the opt_name.

Or try later in that same page:

"Lets say we want to translate three fields. To make it more interesting we’ll demonstrate three different types of options."

Just get to the point:

What you mean is ... 

"In our example we will translate three fields: textfield, textarea with editor, sortable textfield array."

3. The Redux builder tosses in so much junk such as .tx, sample, codestyles ... that should be moved to a documents or docs folder. The size of the Redux Framework is already large.

I hope this helps give some insights.

**Comment by adlibeo** [comment]
As another relative neophyte I find the ReduxBuilder excellent. It streamlines my theme building. However, many of the example usage shown in http://docs.reduxframework.com/ are extremely brief. 

The sorter fields (http://docs.reduxframework.com/core/fields/sorter/) has an additional real-use example - more docs like this would be excellent.

**Comment by kprovance** [comment]
All the fields have real life examples.  If you're referring to the arguments section, there are only so many ways to demonstrate the entry of a key/pair array entry.  if you have a suggestion for a different way to go about it, we're all ears.

**Comment by ahmadawais** [comment]
I am working on a series of tutorials about Redux. I hope so it will be helpful

**Comment by dovy** [comment]
If you need any help let me know.

**Comment by dovy** [comment]
Everyone, I really REALLY appreciate the insight. Does anyone want to take up the task to re-work our getting started guides? For us it's REALLY simple because we code this. We need insight from others.

If you can provide me with a http://gist.github.com of any article, we'll proof and update our docs. We can only be as good as our community.  :)

**Comment by wpinsite** [comment]
Hi Dovy, Absolutely love the plugin and the amazing time yourself and Kevin have put in to make the Redux Framework what it is., You have also spend one of one time with me in the past helping me with issues on extending the plugin..

Once query I do have though is that when changing the "output" tag over to the "compiler" tag are the changes instant or does it take some time to propagate the changes when writing to an external CSS file. When using the "output" tag I found that the changes were instant when I clicked the save button, but when changing this to the compiler tag it can take some time for the changes to be displayed.

If there is anything I can do to contribute to the worlds best WordPress Framework please do no hesitate to contact me.

I have a development environment set up on windows 8 using a top of the range Alienware notebook using XAMP.

P.S I also noticed that you are using my "Advanced Social Widget - MailChimp Edition" ( http://bit.ly/SPMD0y) WordPress pluin that you have purchased from the Codecanyon website. As some compensation for such an outstanding plugin ( Redux Framework ) if you are interested in any of my other Codecanyon plugins please do not hesitate to contact me and i will send them to you for free. That is the last I can do.

Keep up the extraordinary work.
Broady (http://codecanyon.net/user/Broady)
http://www.wpinsite.com
