### ISSUE TITLE
Unable to Switch from Localhost To Live Site Despite Database Edits

### ISSUE THREAD

**Issue by scrollmapper** [ReduxFramework/redux-framework#2004]
I'm familiar with switching wordpress in the wp_options table... no problem there.

I'm attempting to change redux from localhost by changing the JSON string stored with a find/replace. 

Localhost > www.example.com

When I do the find/replace, it appears all of redux resets. 

Is there a way around this? Perhaps redux gets confused and goes back to defaults?

**Comment by kprovance** [comment]
Redux gets confused because you do a find/replace?  If you are replacing any data, then it's not Redux's fault, now is it?  There is no need to change any of that info.

The data is stored in your equivalent of the wp_options table.  They key is the opt_name argument of your options panel.

There is also the Import/Export panel in the Redux options panel.

This is pretty much all that can be done.

**Comment by scrollmapper** [comment]
You might be misunderstanding the issue - but I'll work on it myself thank you.

**Comment by kprovance** [comment]
Perhaps, but since #1975  was completely disregarded, I had very little to work with.  Sorry.
