### ISSUE TITLE
Developer Mode: On by default ? 

### ISSUE THREAD

**Issue by justnorris** [ReduxFramework/redux-framework#2016]
I've always skipped the 'dev_mode' argument, and now, for some-reason - all my clients are seeing "developer mode" in their redux admin panel :/

Was it on purpose or did it just slip in there :) ?

By the way - how about listening for WP_DEBUG instead of having a separate arg 'dev_mode' ?

Redux 3.4.1

**Comment by kprovance** [comment]
`dev_mode' has always been part of Redux and is on by default - as - developers typically are the ones who use it.  Yes, you have to set it to false before shipping your work.  The reason it isn;t attached to WP_DEBUG is because not every developer knows about it.  If folks begin reporting issues with dev_mode set to off, specifically where JS is involved, it makes our lives three times as difficult as it need be, and handwalking folks through activating WP_DEBUG is more time than we have, really.  :)

**Comment by justnorris** [comment]
lol :D

Okay, in any case - since the new update ( 3.4 I think ) Redux is doing weird and ugly things now with dev mode on. I didn't notice that it was on this whole time. Okies, I'll just have to release a bunch of theme updates today...

**Comment by kprovance** [comment]
Ugh.  You maybe want to report these 'weird and ugly' things for verification and possible fix?  :P

**Comment by justnorris** [comment]
Nothing looks broken, it's just the "Redux Ads" and the new "Developer Mode" badge that totally doesn't look right for end-users :)

**Comment by kprovance** [comment]
Okay.  Yes, you must have upgraded from a significantly older version of Redux.  Those were added for developer benefit, not end user benefit.  Those things are shut off when dev_mode is off.  Dovy added a notice that should appear to end users if dev_mode is left on about how to turn it off manually, via a simple one time use plug-in.  I forget when added those things.  Indeed, it was mid-last year, or earlier.

**Comment by justnorris** [comment]
Well....I noticed them just now, and I upgraded from ~3.3.9/8
