### ISSUE TITLE
Can we add EM based line height for fonts?

### ISSUE THREAD

**Issue by pratikchaskar** [reduxframework/redux-framework#2032]
Screenshot - http://bsf.io/7pp08

There should be an option to set font size in PX & line height in EM.

Currently - we can use either PX or EM at same time.

**Comment by kprovance** [comment]
That would require a significant rewrite of the typography field.  Since we have little to no financial backing from our developer based community, there isn't enough incentive for me to take time off from my day job to do it, for free.

You're free to form the project, add that option, and submit a pull request, however.  Note that new functionality must not break existing functionally or break ANY backward compatibility with existing configurations.

**Comment by dovy** [comment]
Tis open source after all.  :)
