### ISSUE TITLE
Themeforest Data Validation issues

### ISSUE THREAD

**Issue by yawalkar** [reduxframework/redux-framework#2054]
Themeforest is rejecting theme with having data validation issues. I have fixed all the data validation in my theme, but the redux framework is having the same issues. Can you please take a look into this?

Following is the comment from Themeforest Reviewer - 

> Data Validation issues have been found in your theme. All dynamic data must be correctly escaped for the context where it is rendered.

> - All dynamic data must be escaped with esc_attr() before rendered in an html attribute.

> - Whenever you are rendering a url to the screen its value must be passed through esc_url() first.

> - If dynamic data is rendered inside an attribute that triggers a JavaScript event, it must be escaped with esc_js().

Awaiting for your reply.

Thanks

**Comment by kprovance** [comment]
Could you be a little more specific?  Which parts of redux, for starters.

**Comment by dingo-d** [comment]
This indicates you didn't escape the things in your theme properly. Redux is escaped properly (I work on theme development for themeforest themes).

earch 'echo $' - those variables must be escaped. Search for any variable in href values (or any url or mailto links), they must be escaped with esc_url() function, all other dynamic variables must either be escaped with esc_attr (id, alt, data, get_permalink() function and similar functions should be escaped as well), textareas should be escaped with esc_textarea. All translatable strings as well (esc_attr_e() and esc_attr__() ). And some titles you are outputing or any input value from Redux that you output on your theme should also be escaped, but for that use wp_kses() function with the allowed strings.

Themeforest started to check thoroughly for non escaped strings lately.

But as said, it's not a Redux issue since Redux is escaped (from what I've saw anyway). 

Check this link for explanation on escaping variables: https://vip.wordpress.com/2014/06/20/the-importance-of-escaping-all-the-things/

**Comment by kprovance** [comment]
Still waiting on specific examples, @yawalkar .  If there are none, I'll be closing the ticket.  Thanks.
