### ISSUE TITLE
Presets - removes undefined subparam

### ISSUE THREAD

**Issue by Ninos** [reduxframework/redux-framework#2064]
If you have a custom field like:
```
array(
	'id'					=> 'typography_h1',
	'type'					=> 'typography',
	'title'					=> 'H1',
	'font-backup'			=> true,
	'text-transform'		=> true,
	'default'				=> array(
		'color'					=> '#888888',
		'font-family'			=> 'Montserrat',
		'font-backup'			=> 'Arial, Helvetica, sans-serif',
		'font-size'				=> '26px',
		'font-weight'			=> '400',
		'text-align'			=> 'left',
		'text-transform'		=> 'none',
		'line-height'			=> '32px'
	)
)
```

and you're using following preset:
```
'typography_h1' => array(
	'color' => '#efefef'
)
```

the in the preset undefined param will also be removed. So after using the preset you get:
```
'typography_h1' => array(
	'color' => '#efefef'
)
```

and not
```
'typography_h1' => array(
	'color'					=> '#efefef',
	'font-family'			=> 'Montserrat',
	'font-backup'			=> 'Arial, Helvetica, sans-serif',
	'font-size'				=> '26px',
	'font-weight'			=> '400',
	'text-align'			=> 'left',
	'text-transform'		=> 'none',
	'line-height'			=> '32px'
)
```
as expected.

I think this should be fixed :)

**Comment by dovy** [comment]
Since this isn't a typical scenario, the following suggestion was made. Add an additional argument to the presets array:

```php
$field = array(
        'type'    => 'image_select',
        'presets' => true,
        'options' => array(
            'bright' => array(
                'alt'     => 1,
                'img'     => 'Image.png',
                'presets' => array(
                    'typography_h1' => array(
                        'color' => '#efefef'
                    )
                ),
                'merge'   => true,
            )
        )
    );

    $field = array(
        'type'    => 'image_select',
        'presets' => true,
        'options' => array(
            'bright' => array(
                'alt'     => 1,
                'img'     => 'Image.png',
                'presets' => array(
                    'typography_h1' => array(
                        'color' => '#efefef'
                    )
                ),
                'merge'   => array( 'typography_h1' ),
            )
        )
    );
```

If found, inside image_select.php add a data argument to the same element that houses the json string. Call it data-merge. If set to true, set it to 1. If set to an array, spit out the array in pipes:  `field1|field2`

Then inside image_select.js you're going to take that value. If the data-merge is not empty, you're going to parse the json string, and adjust it with the values housed on the panel page of redux.options.

So, for example. You'd do the following in javascript.
1. Grab the json string, convert to object.
2. Define `newVariable` as the value in redux.options. IE: redux.options.typography_h1
3. Take your json object data: `jsonData.typography_h1` and do an `$.each()` on the elements, setting the values by key into your new_variable.
4. Replace data: jsonData.typography_h1 = newVariable;
5. Re-endcode jsonData and perform the remaining import function.

Send a pull request when/if you get it done.  :)

**Comment by Ninos** [comment]
After talking with @dovy we'll solve it in this way (for the record):
```
$field = array(
	'type'    => 'image_select',
	'presets' => true,
	'options' => array(
		'options1' => array(
			'alt'     => 1,
			'img'     => 'Image.png',
			'presets' => array(
				'typography_h1' => array(
					'color' => '#efefef'
				)
			),
			'merge'   => true
		)
	)
);

$field = array(
	'type'    => 'image_select',
	'presets' => true,
	'options' => array(
		'options1' => array(
			'alt'     => 1,
			'img'     => 'Image.png',
			'presets' => array(
				'typography_h1' => array(
					'color' => '#efefef'
				)
			),
			 'merge'   => array( 'typography_h1' ),
		)
	)
);
```

I'm planning to create a pull request in the next time..
