### ISSUE TITLE
Minor issue with IDs of li elements

### ISSUE THREAD

**Issue by ahmadawais** [reduxframework/redux-framework#2093]
I am trying to add a bit of styling for the Redux Admin panel but it is not working.
Reason: IDs in CSS cannot start with numbers(https://css-tricks.com/ids-cannot-start-with-a-number/). Which is the case here.
Redux Version: 3.4.3.5

Screenshot: http://prntscr.com/6atrf6

If you can move these numbers at the end or add the title of the li elements as IDs it'll be great.

**Comment by ahmadawais** [comment]
I figure it will be somewhere in this file menu_container.tpl.php
Between line 14 to 49 https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/templates/panel/menu_container.tpl.php#L14-L49

**Comment by ahmadawais** [comment]
I have submitted a patch, @dovy @kprovance  kindly look at ti
https://github.com/reduxframework/redux-framework/compare/master...ahmadawais:patch-1

**Comment by kprovance** [comment]
You've not taken into account the EXTENSIVE changes required in the javascript which will break the panel completely, doing only what you suggest.  This is not some simple 'fix'.

**Comment by ahmadawais** [comment]
Well, I am not aware of that. I just changed it and refreshed the panel, it worked well, so I thought I should give you people a heads up. Guess I have to use CSS technique to address that.

**Comment by kprovance** [comment]
No, you really are not, especially considering how aggressive you were at insulting our project when you first appeared.  This is why we don;t just take every change people want to make to our core, because 99% of them don't understand it.  Considering the time and testing it would take to rework all that, I personally don't see it happening.  It is Dovy's call, but I won't be part of it.  I spend WAY too much time cleaning up the messes people make of our core when they don;t understand it.

**Comment by dovy** [comment]
Chill, chill.

@ahmadawais We have a lot of JS that may be affected by that change...
