### ISSUE TITLE
best way to enable have options per user (for admin) II

### ISSUE THREAD

**Issue by mc007** [reduxframework/redux-framework#2143]
incredible what answers i got for a simple question, nothing special, and even often requested: dealing managing with multiple and dynamic instances. looks this is rather a strong overall design flaw, also giving your attempts to look away from that. 

And about 'sending me money'. how much would that be then ? Writing better docs: are you kidding? That's task for the foundation provider. 

jeez, that must have been a joke, you might have had a bad day, isn it? 

so, now you can close this as you did reckless and rude with the original. idiot!

**Comment by dovy** [comment]
Umm. You are out of line. We're an open source project and we don't owe you anything. Open source means contribution. If you want to contribute with code or money, that's fine. But we're not going on work endlessly for free dude. How many open source projects do you work with? Sheesh.

**Comment by mc007** [comment]
thanks for the lessons! we contribute to 40+ open-source projects. 

just for the record , i asked a simple question: all i got was plain rubbish and pure rudeness. a simple 2 liner would have been enough, ie: not possible due the design.

**Comment by dovy** [comment]
What you're failing to understand is it is possible. You just have to massage it a little...

**Comment by dovy** [comment]
@mc007 now that my brother-in-law is finally checked into drug rehab and I have a moment at the computer I will further post here about this issue and #2141.

Redux is an option framework, not so much a user control management suite. It has the ability to add/remove sections and fields via filters at any time provided the filter/action hooks run BEFORE the Redux option is instantiated.

Now Redux doesn't have built into it a dynamic field generation automatically. You'd have to code that yourself. You could very easily bind it per user and generate fields. Again, you'd have to make that happen dynamically. We can't do that for you.

What I'd suggest is the following. Have a master panel that uses something like the Repeater field. Then have a select field denoting the fields that exist, and have the admin pull them.

Then grab each user, and pull that user's suffixed opt_name (with their user id) to get the values so you can see them from the master admin panel. 

Then you'd have to do a save hook to detect changes and update opt names accordingly.

To do as you're suggesting will require either changing the value ids per users, and hiding all the other others, or having separate opt_names.

This is not a design flaw, but you are asking to make an entire admin suite similar to the WordPress widget area for which the WordPress settings API is not exactly suited for.

The reason @kprovance was a bit edgy is you requested this new feature and he stated accurately that we would need financial support in order to build a unique use case like you are requesting that (although you think otherwise) has only been requested maybe a handful of times.

Upon which you were a bit harsh saying that somehow your use case represents a design flaw. I really am sorry that there's more work for you to do, but that is not my fault. You won't find another framework out there that will support that of which you're requesting out of the box. You have to do some work.

That being said, let's all back off. Let's get along and be happy. We appreciate any support you're given and hope that we can get past this.

**Comment by mc007** [comment]
Sorry to hear about your brother. Put him into a hard job, that helps too a lot :-) Farming/Carpentry as best...

However, yes, lets get over it.

Thank you for the heads up. I will have a look into it. But hey, a ui config framework which can't create configs or custom structs out of its own parts is a little odd, isn't? No offence but I did that things a few times already (enterprise, in C++) and this particular feature came up as requirement at the first sight, always. 

However, I guess you have already a key-widget map, ie: 
integer:text-field, boolean:checkbox, etc... What i did here was adding a type for a 'custom structure' which just contains another map, its like sub sections in your case, or with some dirty tricks (for kids) 'suffixes' as workaround. The 'custom structure' however could cover my use-case but also enriches your current design. That's why i said design-flaw, sorry, wasn't meant that way. Ideally the API would look then like this (more or less): 

type-registry::registerType(name,type-map)
type::render(name,type-map) //renders your types and custom structs

and, of course the data model needs adjustments, but still didn't got into it.

however, don't bother. will find a way to get this done, as always :-)

**Comment by dovy** [comment]
:)
