### ISSUE TITLE
how to remove dashboard widget and admin menu item

### ISSUE THREAD

**Issue by seedprod** [reduxframework/redux-framework#2209]
I have version 3.5.0.5 embedded in my plugin and appears a redux news dashboard widget and admin menu item show by default. Is there a way to remove these things?

**Comment by dovy** [comment]
http://codex.wordpress.org/Dashboard_Widgets_API#Advanced:_Removing_Dashboard_Widgets

We ask you to leave the Tools => Redux Framework menu item so we can easily direct the users there if they need support from us, as we get from time to time. The Support and Status pages really help us to debug.

Hope all is well!

**Comment by dovy** [comment]
Here's an example: 
https://wordpress.org/support/topic/why-is-redux-framework-installed-on-my-site?replies=3

;)

**Comment by seedprod** [comment]
I think that issue was created because they saw the widget and item in the
menu. I've had several emails complaining :( You might make that a paid add
on option to remove. I would pay for it :)

On Wed, Apr 8, 2015 at 2:39 PM, Dovy Paukstys <notifications@github.com>
wrote:

> Here's an example:
>
> https://wordpress.org/support/topic/why-is-redux-framework-installed-on-my-site?replies=3
>
> ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reduxframework/redux-framework/issues/2209#issuecomment-90999653>
> .
>



-- 
John Turner

**Comment by kprovance** [comment]
Then we have to deal with your users coming to us when they have issues, which happens ALL the time.  Yet no one seems to care when EDD does it, or WooCommerce, or Yoast.  We have to do what we feel is appropriate to handle the load of issues that come in that aren't even related to us.  :)

Besides, if we devised such a plan, how long until it gets posted somewhere and *everyone* does it (and not pay us for it).  Kinda defeats the purpose.

**Comment by seedprod** [comment]
That's what I'm saying why do you want users coming to you? They should go through the dev of the product right? When you put Redux in the menu, seems like you are inviting users to come to you when they have an issue like in the example @dovy posted.

**Comment by kprovance** [comment]
They DO come to us, they rarely go to the dev, because they don't know how.  Our support page asks in very simple, easy to understand terms "which are you, a user or a developer?"  Users - should they have an IQ higher than their show size - click "User" and receive instructions on where to obtain support for the plugin and/or theme in question.  Everyone else receives a support URL that tells us everything we need to know (versus a dozen back and forth replies, painfully extracting one piece of information at a time).  So far, it's worked out GREAT for us, cutting down on our support requests.

**Comment by seedprod** [comment]
Asking users to have an IQ higher than their shoe size is a tall order ;) 

OK we'll justing giving you some feedback. Several users have come to me asking what is redux like in the example post. They didn't bother to click on the support tab. They see the new widget and start Googling or open a ticket. Might put a note on the dashboard widget.

**Comment by dovy** [comment]
@seedprod thank you for your input. Kevin and I will discuss it.

Would you Skype (DovyDigital), email dovy@reduxframework, or google chat me: info@simplerain.com. I'd like to get more feedback from you.

Thanks!

**Comment by dovy** [comment]
We're going to make the widget load only when a Redux instance is set to dev_mode on as per your suggestions and to reduce confusion.  :)

**Comment by seedprod** [comment]
Cool cheers!

**Comment by kprovance** [comment]
updated.  :)

**Comment by justnorris** [comment]
I'm sorry, I strongly disagree with this direction. It's just going to generate more support for you. There is that saying - If ain't broke - don't fix it. 

I agree with @seedprod - the shoe sized IQ is really a tall order. People don't read instructions. They just blindly click around.

And what is this URL for `http://support.redux.io/?id=YEWQ[.......]D%3D` ? It doesn't even load.

> Please be sure to include for your developer - via cut and paste - the Support URL in the box below.
*Ohh yeah ? I thought I was trying to already contact my developer with the support tab. Ohh well, I guess I have to go back and click "Developer" instead and paste it there.*


@kprovance - *"they rarely go to the dev, because they don't know how"* - that conclusion came from what exactly ? My forums are full of people who know exactly how to find me. "They rarely go to the dev" implies that I get 40% of support requests, and you're getting the 60% of my support requests. 



I love Redux and I really appreciate the work you've all put into it, but these decisions sometimes amuse me.

**Comment by kprovance** [comment]
First, I'm locking this thread.  The complaining is getting tiresome.

Second, no, the URL won't load for you.  We have a special key to unlock it.  Keeps prying eyes out.

Third, my conclusion comes from experience, here on the issue tracker.  I've already explained the how and why.  Most will be redirected here:  http://docs.reduxframework.com/core/support-defined/, should they not understand simple instructions on how to contact the theme or plugin author.

Lastly. I'm glad you're amused, but the panel is staying.  I don't get why people don't complain when other devs do it, but when WE do it - to save us time and energy - it's some kind of unforgivable sin.  That or perhaps some devs don't want to acknowledge they are using Redux?  I don't know.  I make no direct accusations toward anyone, but it sure does sound that way sometimes.

Any further complaints - to _anyone_ reading this may be directed to info@reduxframework.com.  We'll leave the issue tracker to actual issues.

**Comment by dovy** [comment]
@justnorris We're not trying to frustrate, but there are a number of support issues that come to us. Our Facebook account is loaded with theme/plugin support messages. So we simply direct people to that support page and the problem is solved!

The dashboard newsfeed now only applies to instances where dev_mode is on. So that shouldn't affect your users.

If you have such a problem with a menu item under the most unused parent menu in WordPress (tools), then I guess you can manually remove the link using standard WordPress calls. If any of your users ever contact us, we'll still direct them to that support page.

If anyone wants to learn about WHY we're doing the support URL, or talk more in depth, you're welcome to contact me directly (Skype: dovydigital). Honestly, the support has reduced our ticket support time in almost HALF. I am not kidding. It just makes our life easier and we're better able to support everyone,

So anyways. We're not trying to frustrate anyone.

Oh, and @justnorris soon there will be a support extension you can use to get a full Status report for each of your users. We're just building it now. I am sure in the near future your frustrations will all but disappear regarding this matter when you get the benefits we currently have with support URLs.
