### ISSUE TITLE
undefined when chaning opt-name on the fly with ajax save on

### ISSUE THREAD

**Issue by AlexAlexandru** [reduxframework/redux-framework#2224]
WordPress: v4.1.1
Redux v3.5.2.1 Embed Only(from the build generator )
PHP v5.6.3

here is a quick video  https://youtu.be/GLeQ7_cPZRI
I change the opt-name but I don't reload the page and then I press save

**Comment by kprovance** [comment]
We're not accepting videos anymore.  

In order for us to begin debugging your issue, we need you to first generate a support URL. You can learn about how you generate that here: http://docs.reduxframework.com/core/generating-a-support-hash/

Please update this ticket with the support URL when you have it. Thank you.

And, if you change the opt_name, you MUST reload the page, otherwise the old opt_name exists in the HTML.

**Comment by AlexAlexandru** [comment]
http://support.redux.io/?id=PNYVWd4meP%2FJqL3QU%2FfUEKYkuvI4dEc3EWH9oPoxS1laolaApn%2BWkZV0zTYV9LGHP9dMCnOundfyjDnCsg77RQ%3D%3D

Well that was the issue but I think there could be an message beign said not just undefined

**Comment by kprovance** [comment]
@Dovy will have to take a look at it, as it has something to do with ajax save kicking back an error with the ajax save JS function.  Probably something to do with what you were attempting to do, changing the opt_name without reloading.  I don't know.  I cannot recreate the issue.
