### ISSUE TITLE
Dynamic css generation issue

### ISSUE THREAD

**Issue by FiGO-** [reduxframework/redux-framework#2267]
I've recently updated Redux to 3.5.4.1 from a  very old version for testing. For some reason I'm not able to generate the dynamic css via the compiler hook. The hook runs and displays the message configured in the sample file but there is no output to the css file. I noticed in your new sample config file you removed the piece of demo code that was responsible for adding the css content to the file. I tried to reapply using the info from the docs but to no avail. I'm sure Im missing something I just can't figure out what. Does the hook work the same as it did in previous versions or is there a different way to get it working?

Hash: 
http://support.redux.io/?id=iB%2B6xQITyR6%2FKIjF%2FNQW5IrFln5eJbFOLNxJ2TQ0zYZxsANYi8nMXSuPaVjBZ0OfH9PqVCaZGBJD6LOfqb%2BkZg%3D%3D

( By the way this new support hash tool is brilliant and I'm really loving your new Redux API )

**Comment by kprovance** [comment]
We removed that example code from the config for two reason 1) It's an improper use of the WP_Filesystem object that leads to 2) It not being reliable on every possible install of Wordpress.  Because we offered that sample code, people expected us to support it when it failed under certain circumstances.  Devs would have clients in which that code would fail, and those devs came running back to us for a solution.  We simply got tired of supporting issues outside the scope of Redux.  We offer the tools, what people do with it is up to them.  Since outputting content from the compiler to an actual file doesn't fall under a Redux issue or 'bug', it's not something we are able to support.  It's more than likely a PHP issue, which - not to put too fine a point on it - we'd need to be compensated for, time wise.

Now, that old code is still in the sample-config-legacy.php file, but it's 'as is'.  We won't support it.  It's hackish anyway and not something you'd really want to use in production.

We have a file system proxy Redux uses, that uses the wp_filesystem the correct way here:  http://docs.reduxframework.com/core/wp_filesystem-proxy/  You could use those functions to create your own solution.

Good luck!

**Comment by FiGO-** [comment]
Thanks @kprovance  I appreciate the explanation.
