### ISSUE TITLE
Problems with upload to Wordpress Plugin Repo

### ISSUE THREAD

**Issue by drosa88** [reduxframework/redux-framework#2289]
Hi guys,

my plugin (options panel build with your framework) was rejected because of the following:

--------------------------------------
## Including another plugin 

We cannot accept a plugin that includes an entire other plugin, wholesale, inside it. 

This means the Redux Framework's got to go :/ 

While we understand the use of framework (or boilerplate) plugins, and encourage the use of common libraries, full blown plugins should never be included inside another, as it causes multiple potential issues, such as function/attribute conflicts, and also opens your code up for issues should the included plugin be closed for a security hole. 
----------------------------------------------

You´re familiar with this problem?

**Comment by kprovance** [comment]
I guess it depends on how you included Redux in your project.

**Comment by drosa88** [comment]
I generated the "admin"-folder with all needed functions with your redux-builder, then i created my own config file.

The including-part:

    if ( !class_exists( 'ReduxFramework' ) && file_exists( dirname( __FILE__ ) . '/admin/redux-framework/ReduxCore/framework.php' ) ) {
      require_once( dirname( __FILE__ ) . '/admin/redux-framework/ReduxCore/framework.php' );
    }
    if ( !isset( $dd_options ) && file_exists( dirname( __FILE__ ) . '/options.php' ) ) {
      require_once( dirname( __FILE__ ) . '/options.php' );
    }

Thanks for support!!

**Comment by drosa88** [comment]
Maybe the complete message from wordpress will help you:

---------------------
## Including another plugin 

We cannot accept a plugin that includes an entire other plugin, wholesale, inside it. 

This means the Redux Framework's got to go :/ 

While we understand the use of framework (or boilerplate) plugins, and encourage the use of common libraries, full blown plugins should never be included inside another, as it causes multiple potential issues, such as function/attribute conflicts, and also opens your code up for issues should the included plugin be closed for a security hole. 

The proper way to include another plugin would be to require it in your own. You can use the hook is_plugin_active() to check to see if the plugin is, indeed, installed and active. 

https://codex.wordpress.org/Function_Reference/is_plugin_active 

The other alternative would be to actually fork the code, and not have a 100% copy in yours. Sadly, WordPress plugins don't have the ability to do sub-modules, so you'll have to actually customize the code for interaction.

**Comment by dovy** [comment]
Only embed ReduxCore in your plugin. If they give you a problem give me link to the track issue and also the slack channel and I'll get it resolved. Sounds like a reviewer just doesn't understand.

**Comment by dovy** [comment]
Actually give me the trac URL anyways. ;)

**Comment by drosa88** [comment]
Hi @dovy :-)

Thank you!! So..just for understanding: i will remove all other folders (sample, .txt etc.) and embed ONLY the ReduxCore folder? Then i have to anwer my reviewer directly via eMail with the new ZIP file of my plugin after fix it..what i can write him about the solution of this problem? I have no link to the track issue..i got an email from the reviewer (it´s my first plugin, so i don´t know the workflow yet) ..

Thanks a lot!

**Comment by dovy** [comment]
Send them this:

---
From the Lead Dev of Redux Framework.
So that you are aware, Redux Framework is a framework for making options. We do have a plugin hosted on the WordPress.org repo. This is not because Redux is a plugin, but rather it is to facilitate framework updates so developers need not update their plugin/theme every time Redux rolls out an update. Even though the Redux Framework plugin has big stats, it only accounts to about 14% out of our total developers who use Redux. Have have 7300+ developers who have made [hundreds of products](http://reduxframework/showcase/envato) for thousands of users World Wide.

If you have a problem with Redux Framework being used, then you should feel similarly towards [Options Framework](http://wordpress.org/plugins/options-framework/), [Titan Framework](http://wordpress.org/plugins/titan-framework/), [Option Tree](http://wordpress.org/plugins/option-tree/), [Advanced Custom Fields](https://wordpress.org/plugins/advanced-custom-fields/), and others (Used by endless products throughout the WordPress space).

I don't tell you this to frustrate, but to inform. We are a framework, and we only place our code in a plugin to facilitate updates to our core (bug fixes). If you choose to disallow Redux Framework, can assume that you will also take the same action for the other frameworks afore mentioned? Redux is no different than any of them.

Thank you!
---

That should get you through.  ;)

**Comment by dovy** [comment]
P.S. Anything our builder exports is fine for shipping with.  ;)    So no need to alter further. You only need to alter if you decided to place the entire repo inside your theme. That could raise this concern. Sounds like you used the builder, and that strips the "plugin" stuff out.  ;)

**Comment by drosa88** [comment]
Great! Thank you! +1

**Comment by drosa88** [comment]
@dovy The Reviewer wrote back:
-----------------------------
We DO feel exactly the same about those other plugins, and tell people they are not permitted to use them inside their plugins either. 

We do not disallow it's usage, we disallow it's INCLUSION, wholesale, in another plugin. Just like we do Advanced Custom Fields. 

Simply put, no, you may not have another plugin included in YOUR plugin. 

Please change your plugin to require the Redux Framework as a separate plugin. Don't include it's code in yours.

**Comment by drosa88** [comment]
I don´t understand this guy..i embedded *only* the ReduxCore, so that´s not really a wordpress plugin..just a framework.. i don´t want to include it as required plugin because nobody wants a plugin who require another plugin.. not really beautiful.

**Comment by dovy** [comment]
So you have to use TGM because Redux is based as a plugin in the repo. Even though you're only using the core, if you're using Redux in the .org repo you must use TGM to install the Redux plugin.

That's the new rule as of 8 months ago.  :(

**Comment by drosa88** [comment]
I see...! My plugin was approved after require redux separate. :) thanks for your support!

**Comment by dovy** [comment]
Glad you got it sorted!

If you like Redux, or the support we render, please do some or all of the following:
* Donate to keep us going: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW
* Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
* Like us: http://facebook.com/ReduxFramework
* Follow us: http://twitter.com/ReduxFramework

**Comment by drosa88** [comment]
I like this framework. I like your support. So i donated with pleasure! ;) 

Have a nice day!
