### ISSUE TITLE
Field: spacing

### ISSUE THREAD

**Issue by kpodemski** [reduxframework/redux-framework#231]
I think is good to have suffix with unit name even if we have only one value.

**Comment by Stas0238** [comment]
Hello, i would like to add vh and vw dimensions in spacing field. It works till I won't refresh the options page which contains an error with text like 'Undefined index on .../redux-framework/ReduxCore/inc/fields/spacing/field_spacing.php on line 161' so that when I looked closer I saw you have an array of acceptable values for units 
array(
                        '',
                        '%',
                        'in',
                        'cm',
                        'mm',
                        'em',
                        'rem',
                        'ex',
                        'pt',
                        'pc',
                        'px'
                    )
Can you please add vh, vw also in this array of units to make them working good ?:)
