### ISSUE TITLE
Last field error

### ISSUE THREAD

**Issue by soutocorral** [reduxframework/redux-framework#2352]
Hello
I have a redux panel installed on a wordpress theme and it contains many fields.
For it may be that the last field does not work and does not change its default value.
But if it remove fields to reduce the number it works perfectly
Thanks

**Comment by dovy** [comment]
This probably means you're reached the max input variables. If you have more than your server is set for, the last fields will be removed.

That, or you're accidentally using the same field ID twice.

**Comment by soutocorral** [comment]
I do not have any ID doubled. Once you step this error?. What can be the solution? Will my server settings?
Thanks

**Comment by dovy** [comment]
Do php_info() and check the `max_input_vars` line.  ;)

**Comment by kprovance** [comment]
Even if you change your max_var_input settings, that won't change it on your users boxes, which means the issue will persist for them.  You have a design problem, if your options panel uses more than 1000 variables.  Post a support URL and we can see if that's the case.

**Comment by soutocorral** [comment]
Hello
I have still the problem and save changes when an alert opens with the message "There was a problem with your action. Please try again or reload the page.".
Thanks

**Comment by soutocorral** [comment]
http://support.redux.io/?id=VUcu6AFFYTVSwGAG0cf9XLxsWB0o%2BBFGtIcqlUvGu4SmxONdS0BZJxFl3P%2BlNN%2BYhEjvvqls1VgGwRdHsMsz%2Fg%3D%3D

**Comment by kprovance** [comment]
<blockquote>
"There was a problem with your action. Please try again or reload the page.".
</blockquote>
Open the javascript debug console and check for the error.  if you are using echo or print_r statements someplace, they would appear there, and interfere with the saving process when using ajax save.

**Comment by kprovance** [comment]
I pulled your config from the support URL and ran it for myself.  The reason for the error, which you can see in the debgu console for yourself is thus:
```
1234567891011121314151617181920212223242526272829303132333435363738394041424344<br />
<b>Warning</b>:  parse_str(): Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini. in <b>D:\xampp\apps\wordpress\htdocs\wp-content\plugins\redux-framework\ReduxCore\framework.php</b> on line <b>2772</b><br />
```
I'm not sure what that string of numbers is all about, however, the warning explains your original issue; your options panel has too many input variables.  Yes, you can increase them in your dev environment, but you can't really do so for your users, and since 1000 is the default value for max_input_var, chances are likely your end users will experience the issue you currently have.  This is a design issue that we can't really help with.  You'll have to give some consideration to designing your options panel to use less input variables.
