### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by Joseph-a** [reduxframework/redux-framework#2355]
Hi, 
I recently update the redux to the latest version (3.5.4.15) but if I add any typography fields in the theme option "redux.js" throw the below error:
"Uncaught TypeError: Cannot read property 'split' of undefined"

I checked your demo to find out what is the issue but it seems that the demo is not updated yet.

**Comment by dovy** [comment]
*sigh* introduced a bug. Almost fixed. :)

**Comment by Joseph-a** [comment]
Any update about the fixing this issue? Can I have the fixing in the current version or must be waiting for the next version release?

**Comment by dovy** [comment]
Fixed in the repo now. Not done with what I am doing, but no more errors.  ;)

**Comment by SMR21** [comment]
This same failure occurs in the field of switch and is due to a lack of space .

File: field_switch.php

Error:  echo '<input type="hidden" class="checkbox checkbox-input' . $this->field['class'] . '" id="' . $this->field['id'] . '" name="' . $this->field['name'] . $this->field['name_suffix'] . '" value="' . $this->value . '" />';

solution: echo '<input type="hidden" class="checkbox checkbox-input ' . $this->field['class'] . '" id="' . $this->field['id'] . '" name="' . $this->field['name'] . $this->field['name_suffix'] . '" value="' . $this->value . '" />';

**Comment by SMR21** [comment]
In the field switch the same problem due to lack of space in the line 49.
class="checkbox checkbox-input' . $this->field['class'] . '"
solution:
class="checkbox checkbox-input ' . $this->field['class'] . '"

**Comment by kprovance** [comment]
Resolved in v3.5.4.16

**Comment by kprovance** [comment]
ps - in the future, please do not piggy back old tickets with new issues.  Create a new ticket for each new issue.  Thanks!
