### ISSUE TITLE
500 error on some server environenments, probably php version related

### ISSUE THREAD

**Issue by seventhqueen** [reduxframework/redux-framework#2393]
Hi, plugin version 3.5.4 not in dev mode and embedded in theme. We switched from 3.3.6 to 3.5.4 and lots of users are reporting that they get a blank theme options page, a 500 page or a 502 page. 
Unfortunately I couldn't get specific hosting environment details but I am on it. 
I am guessing it is related to the PHP version used. Do you know anything about this?
With the older version everything works fine.

Thanks

**Comment by kprovance** [comment]
You switching PHP environment would have no effect on your users, as your users are using whatever version of PHP is installed on their own server.  Are YOU able to reproduce the issue?  If so, we need that information, plus a support URL (https://docs.reduxframework.com/core/generating-a-support-hash/).  That information will only be good for your server.  You'll need to do some more investigating, since we do not support your end users.  Problems on their end could range from improper server setup, permissions issues, etc.  You should examine their PHP error logs for clues.  Also, PLEASE sure you are including the latest version of Redux, which is v3.5.4.18

**Comment by seventhqueen** [comment]
Thanks for the fast response, I will dig more into this to find the problem. I mentioned the PHP version since one was fixed upgrading to a newer php version and I guessed that maybe it could be related or maybe it needs at least 5.3. Thanks again

**Comment by seventhqueen** [comment]
Solved it. The problem was that the options were initialized in an "init" action hook. Removing them and putting them in the theme functions solved the problem. Can't really say why that happened but it was a very isolated issue. Thanks

**Comment by dovy** [comment]
Aha, well I can explain that.

Redux LOADS on init. So if you're trying to add some options on the init hook, I am 100% sure it's happening after Redux is initialized, and you're double loading Redux.  ;)

Glad you solved it! Best of luck.

**Comment by Shopyloot** [comment]
Hi, it been years I think, 
Still, I was having the same issue, I tried to install reduxframe work plugin I clicked on install and that's it gave me an Internal 500 Error! May I know how can this be rectified?
