### ISSUE TITLE
Options Init. Raw field with a 0 as content does NOT render.

### ISSUE THREAD

**Issue by IzaacJ** [reduxframework/redux-framework#2447]
This is an example on how the raw field does NOT accept a zero character ('0') as content. Is this considered a bug or a feature? In my case, it's definitely a bug.

```php
Redux::setSection( $opt_name, array(
   'title' => 'Raw Type Issues',
   'id' => 'raw_issues',
   'fields' => array(
      array(
         'id' => 'renders',
         'type' => 'raw',
         'title' => 'Renders correctly',
         'content' => '<i>0</i>'
      ),
      array(
         'id' => 'does_not_render',
         'type' => 'raw',
         'title' => 'Not rendered',
         'content' => '0'
      )
   )
);
```

**Comment by kprovance** [comment]
Could you please provide a support URL?  There is no version information indicated.

**Comment by IzaacJ** [comment]
Oh, using version 3.5.4.3

**Comment by dovy** [comment]
http://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by IzaacJ** [comment]
Here it is: http://support.redux.io/?id=o9tjAlPcO4iERIxcV7q96Mkbt97Z%2F9abKF2C8egnpS6Lv2XIBcKfN8VyteNDcsGOPooryfvqGAtRVTk9HuPIKw%3D%3D

**Comment by kprovance** [comment]
Well, it looks like when the html is run through the WP settings API, it interprets 0 as false, and outputs it as such, meaning a blank.  There isn't much we can do about it, since the settings API is wordpress.  You could mention it to them via their trac, but I wouldn't get my hopes up on an actual fix, since they don't really care about their API so much.  If you wrap the 0 in a div, it outputs fine.  That's about all you can do, really.
