### ISSUE TITLE
switch field returns string not boolean

### ISSUE THREAD

**Issue by AlexAlexandru** [reduxframework/redux-framework#2464]
```php
Redux::setSection( $opt_name, array(
        'icon'            => 'el el-list-alt',
        'title'           => __( 'Just testing', 'redux-framework-demo' ),
        'desc'            => __( '<p class="description">Here you can put some info.</p>', 'redux-framework-demo' ),
        'customizer_only' => true,
        'fields'          => array(
             array(
                'id'       => 'selector',
                'type'     => 'switch',
				'customizer_only' => true,
                'title'    => __( 'Turn on now', 'redux-framework-demo' ),
                'default'  => false,
            )
        )
    ) );
```

$redux_demo['selector'] returns a string with 1 or 0 shouldn't be a boolean true or false?

**Comment by kprovance** [comment]
As I used to say to my son, when he played with the power window switch, "stop that, you'll break it!"  ;-)  

Did you figure out what was wrong?  I didn't look into it yet, but I believe the reason the value is still stored as a sting is because we allowed for the default value to be an integer, boolean, or string, and this was the way of maintaining that backward compatibility.

**Comment by AlexAlexandru** [comment]
Just done a clean install of redux.The default value is stored as a boolean but when I change it and save it it's getting converted to a string.

**Comment by kprovance** [comment]
Because on first save, Redux is saving the default value you specified.  Since it's bool, that's what gets saved.

When changing the setting on the panel, the JS is doing this
```
$( '.checkbox-input', parent ).val( 1 ).trigger('change');
```
Or
```
$( '.checkbox-input', parent ).val( 0 ).trigger('change');
```
depending on the switch value.  The result is set as a string in the HTML value param, and is how it's saved in the database.

Not much we can about that, since values need to be saved as strings in the HTML itself.  Even if there was another way, we'd be breaking so much backwards compat, it wouldn't be worth doing.  The only caveat is using the === evaluator, which probably won't work since it's type specific.

**Comment by AlexAlexandru** [comment]
Ok thanks for clearing this one.
