### ISSUE TITLE
SMOF to Redux using Redux Converter

### ISSUE THREAD

**Issue by contempoinc** [reduxframework/redux-framework#2471]
I'm migrating from SMOF to Redux, I've used the Redux Converter plugin and it worked (http://grab.by/IKDS) I then went to Convert to Redux > downloaded the config file > did a git clone of the framework into my admin directory > created a new folder within admin > ReduxFramework > theme-options.php > copied the config file into that (http://grab.by/IKE2) > then added the following to my functions.php

```
require_once( ADMIN_PATH . 'ReduxFramework/ReduxCore/framework.php' );
require_once( ADMIN_PATH . 'ReduxFramework/theme-options/ReduxFramework.config.php' );
```

Once I remove the require_once ('admin/index.php'); for SMOF the admin option menu items are removed and the new one isn't added? Here's my config https://gist.github.com/contempoinc/3496c1676733cb752937

Even if I activate the Redux Framework plugin the config file isn't recognized, but no errors are thrown like it can't find the file or anything.

If I include the sample-config.php it works just fine.

**Comment by kprovance** [comment]
Please post a support URL:  https://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by contempoinc** [comment]
I'm running on my local so that wouldn't work correct?

**Comment by kprovance** [comment]
It will.  If it's in your config, it'll tell us.  Plus, we can offer you a config that uses the Redux API, instead of the legacy method your employing.

**Comment by contempoinc** [comment]
Gotcha, when I click generate it throws an error http://grab.by/IKEs

**Comment by kprovance** [comment]
Open up the console log and report back the error (CTRL + SHIFT + I).  May need to get @Dovy in on this since I'm not familiar with the converter process.

**Comment by contempoinc** [comment]
Object {readyState: 4, responseText: "<br />↵<b>Fatal error</b>:  Call to private Browse…s.redux_helpers.php</b> on line <b>408</b><br />↵", status: 200, statusText: "OK"}

redux-welcome-admin.js:58

**Comment by kprovance** [comment]
Ahy way to get the non-abbreviated version of that message?  I can;t research anything with ellipses in them, it's incomplete.

**Comment by contempoinc** [comment]
Here's the whole thing https://gist.github.com/contempoinc/aa7c46b1d3fa47c68df8

http://grab.by/IKEY

**Comment by kprovance** [comment]
Well, without knowing what version of Redux you're using, if it's embedded or installed as a plugin someplace else, and a bunch of other things, I have to assume it's an issue in the config someplace (and I have NO idea what admin/index.php does, since it doesn't appear to be a Redux file).  The thing is, if I take the time to download this project and fix it, I'm going to ask you pay for premium support for me to do it, UNLESS it's a Redux bug (which I'm pretty sure it isn't).  That error message about the Browser object also makes no sense since it doesn't have a private constructor to begin with which leads me to believe the configuration is off, or the version is off due to another instance.  The other alternative is to wait for Dovy to weigh in, but that won;t be till next week.

**Comment by contempoinc** [comment]
I'm using the latest, just did a git clone a little under an hour ago.

admin/index.php is for SMOF

**Comment by contempoinc** [comment]
I'm using the latest, just did a git clone a little under an hour ago.

admin/index.php is for SMOF

The config generated from Redux Convert isn't working, if I use the included sample config the options page is included when I switch the generated config nothing is shown, no errors either.

**Comment by kprovance** [comment]
All I can tell you is I ran your config file in my own setup, as shown here:
![git_options](https://cloud.githubusercontent.com/assets/3412363/8635193/6fbc41e8-27e6-11e5-8c21-a690ec96c9c8.png)

it loads and runs fine, which tell me the issue in how you have the whole thing set up.  This is not something I can debug from where I sit.  You could always try running Redux as a plugin and see if that makes a difference.

**Comment by contempoinc** [comment]
When I run it as a plugin how would I import the config?

If remove the framework require and keep the require_once( ADMIN_PATH . 'ReduxFramework/theme-options/ReduxFramework.config.php' ); then activate the plugin it doesn't show. It only shows the Sample Options.

I'm also seeing this error:

Fatal error: Call to private Browser::__construct() from context 'Redux_Helpers' in C:\wamp\www\wordpress\wp-content\plugins\redux-framework\ReduxCore\inc\class.redux_helpers.php on line 408

**Comment by contempoinc** [comment]
When I go to http://localhost/wordpress/wp-admin/tools.php?page=redux-status

**Comment by kprovance** [comment]
Again, it's somewhere in your config, and I cannot debug that from here.

**Comment by contempoinc** [comment]
You used the ReduxFramework.config.php on your install and it worked right? Just by simply adding:

require_once( ADMIN_PATH . 'ReduxFramework/theme-options/ReduxFramework.config.php' );

**Comment by kprovance** [comment]
My setup is significantly different from yours.  From my functions.php I just used: 

```php
require_once( 'admin/ReduxFramework.config.php' );
```
having placed the file in <theme root>/admin/ReduxFramework.config.php.  I don't use defines or any other type of global variable since I believe them to be unreliable.

**Comment by contempoinc** [comment]
I understand that, just making sure you included the same config I posted. I also tried it on a fresh install of WP, with Redux in theme and the config won't show the options page.

I'm also seeing the same error:

Fatal error: Call to private Browser::__construct() from context 'Redux_Helpers' in /nfs/c01/h16/mnt/1320/domains/wp.contempographicdesign.com/html/wp-real-estate-7/multi-demo/wp-content/themes/realestate-7/admin/ReduxFramework/ReduxCore/inc/class.redux_helpers.php on line 408

Is it possible that the latest version on WordPress.org and the Github repo has a bug?

**Comment by contempoinc** [comment]
The error is also appearing when I use the sample config but the admin options menu link shows like it should.

**Comment by contempoinc** [comment]
Its gotta be an issue with ReduxFramework.config.php right?

**Comment by kprovance** [comment]
I don't think your hearing me; I don't know.  I tried your config, it loaded.  It's not a bug in Redux because if it were, there would be thousands of issues just like this one, and there aren't.  It's in your setup, and that's not something I can debug from here.  I don't know the particulars of your setup, (php version, mysql version, etc).  So, for a fee I can download your project, examine it and determine where the problem is, or you can wait for Dovy to show up next week, but I'm fairly certain he'll say the same thing, in that our time isn't free.  We already give away Redux and half a dozen other services with it, and we support bug fixes for free, but this isn't a bug on our code, it's in your config somewhere, and again, I cannot see into your computer to see why.  It's *impossible*.  I'm not sure what else you want me to do here.

**Comment by contempoinc** [comment]
No worries, I went ahead and just created a new one from scratch and its working.

**Comment by contempoinc** [comment]
Thanks!
