### ISSUE TITLE
ACE Editor works only in Dev Mode

### ISSUE THREAD

**Issue by abhishek1234321** [reduxframework/redux-framework#2493]
I am using the latest stable release of redux (3.5.5), the ace editor component works good when `dev_mode` is set to `TRUE` but when it is set to `FALSE`, It doesn't load the editor CSS/JS files. Please refer the screenshots.

<img width="1011" alt="dev mode on" src="https://cloud.githubusercontent.com/assets/529159/8717786/2995b850-2bbc-11e5-8c21-cd68649c6fec.png">

<img width="977" alt="dev mode off" src="https://cloud.githubusercontent.com/assets/529159/8717787/299b7c68-2bbc-11e5-95eb-85987b7f35db.png">

I think the `use_cdn` is dependent on `dev_mode` variable (Not sure of how this works). 

CSS and JS files of the editor are loaded only when 'dev_mode' is set to `TRUE` irrespective of `use_cdn` setting. I have the vendor files in `redux-extensions/extensions/` folder)

Am I doing something wrong or is this a bug? 

Any help is appreciated.

Thanks

**Comment by kprovance** [comment]
If you're going not use the CDN, you need to install the extensions for vendor support, or use the plugin, your choice:  https://github.com/reduxframework/redux-vendor-support

**Comment by abhishek1234321** [comment]
Yes I do have that in `redux-extensions/extensions/` folder. 
This is my admin-init.php file 

		<?php

		// Load the TGM init if it exists
		if ( file_exists( dirname( __FILE__ ) . '/tgm/tgm-init.php' ) ) {
		  require_once dirname( __FILE__ ) . '/tgm/tgm-init.php';
		}

		// Load the embedded Redux Framework
		if ( file_exists( dirname( __FILE__ ).'/redux-framework/framework.php' ) ) {
		  require_once dirname(__FILE__).'/redux-framework/framework.php';
		}

		// Load Redux extensions
		if ( file_exists( dirname( __FILE__ ) . '/redux-extensions/extensions-init.php' ) ) {
		  require_once dirname( __FILE__ ) . '/redux-extensions/extensions-init.php';
		}

		// Load the theme/plugin options
		if ( file_exists( dirname( __FILE__ ) . '/options-init.php' ) ) {
		  require_once dirname( __FILE__ ) . '/options-init.php';
		}
I am loaded extensions-init before options-init file.

In spite of this the CSS and JS files are loaded from the local install, even when `use_cdn` is set to `true`.

**Comment by abhishek1234321** [comment]
All is working fine. I think the issue is with caching. Thanks for the support!

**Comment by anikitas** [comment]
Hello Sorry to reply on closed ticket.

I have the same issue with the same setup only affected on server.

Tested on:
Redux v3.5.6.6
Redux v3.5.7.5

I assume it's could be caching. Works on localhost not on live server.

When using CDN some servers don't load the scripts.
When using the plugin as an extension the ace editor doesn't work .

In one project i had to revert back to an older version of Redux before the CDN implementation.

So i don't know how to proceed or if something can be changed in:

Redux Framework
Redux Vendor support Plugin
Some change in the Theme itself

The weird thing is that only ace.js is not loaded. Select 2 doesn't have any issues with use CDN false.

I realize that it's not easily reproduced as it depends on server configuration.
With dev_mode on it works on all cases.

I'll try to debug it to see if i can find anything.

@abhishek1234321: How you solved this issue with caching? Was it due to a WordPress Plugin or server caching?

Any feedback would be helpful.

Thanks in advance!

**Comment by anikitas** [comment]
Hello again,

I think i found the problem.

The problem is in Vendor Support Plugin: class.vendor-url.php Line 13
<pre>
if ( $handle == 'ace-editor-js' && file_exists( self::$dir . 'vendor/ace_editor/ace' . Redux_Functions::isMin() . '.js' ) ) {
</pre>

In the directory ace there is not minified version present so the ace_editor file is not found.
That's why select2 is fine, as it has a minified version.

In localhost with debug mode and with dev_mode on, the full files are loaded instead.
Otherwise the .min extension is added to the filename.

I changed the line to:
<pre>
if ( $handle == 'ace-editor-js' && file_exists( self::$dir . 'vendor/ace_editor/ace.js' ) ) {
</pre>
and everything is loaded successfully.

Of course the other alternative is to add the minified version of the file in the directory if available.

I hope it helps!

Thanasis

**Comment by dovy** [comment]
Wow, thank you! We'll add the fix shortly.

@kprovance Care to add this in?

**Comment by anikitas** [comment]
Anything for you Dovy :)

**Comment by kprovance** [comment]
It would also be MUCH appreciated if we opened NEW tickets and not piggy backed old ones.

ace used to have the min check.  Guess it got taken out.  :(

**Comment by kprovance** [comment]
vendor support repo updated.
