### ISSUE TITLE
Confilct between Typography field and JW Player plugin

### ISSUE THREAD

**Issue by VladNov** [reduxframework/redux-framework#2500]
Hi Guys,

When "JW Player for Flash & HTML5 Video" https://wordpress.org/plugins/jw-player-plugin-for-wordpress/ plugin is activated the Typography field becomes empty of fonts and show only one value in the drop down which is "none" and the current selected font. See the image below how it behaves.

![typography-field](https://cloud.githubusercontent.com/assets/2650362/8765358/dd9d46c8-2e10-11e5-9062-975588b82f25.png)

**Comment by kprovance** [comment]
Well, since it's them that interferes with us, probably making it their fault, have you asked them about it first?

**Comment by kprovance** [comment]
Well, knowing this was a select2 issue, I checked their version, which is outdated and why it messes up our panels.  Since it's been my observation that asking other developers to update their vendor code is often met with silence and inaction, I unregistered and dequeued their old version of select2.  Redux renders properly.  However, if now things in their plugin start not working, then it's up to them to update their select2 library, or enqueue it in such a way so that is doesn't conflict with ours.

Fixed in v3.5.5.9
