### ISSUE TITLE
Using redux with a parent theme symlink

### ISSUE THREAD

**Issue by hannwong** [reduxframework/redux-framework#2504]
Reopening issue #2360 as it was closed by kprovance.

Here's how to reproduce this problem...

1. Install and activate Redux Framework plugin.
2. Create symlinks in /wp-content/themes to point to a parent theme and its child theme.

Redux Framework stops working with child theme activated.

But the moment I copied the parent theme over (rather than using symlink), Redux Framework starts working immediately. Child theme is still using symlink.

# Support Hash not available!

Oh, I just realized there is no "Tools -> Redux Framework" in my wp-admin. Redux Framework version 3.5.5.10. What do I do?

**Comment by kprovance** [comment]
IS it your theme, or did someone else author the theme?

**Comment by kprovance** [comment]
Okay, welll, here's the deal.  If you are NOT the author of the theme, then the author removed that support function, and shame on them for doing so.  This means you will need to contact them and complain about it.  They should not have done that.  It also means you'll have to seek support from them, and not us.  We do not support themes and plugins made with Redux, that's the developers responsibility.

That said, symlinks is unreliable and unpredictable.  We've never been able to successfully integrate them.  You're free to give it a go, but as of yet, because of their lack of flexibility, no one has successfully done so.  This is why WP has the https://codex.wordpress.org/Function_Reference/get_stylesheet_directory API and it's various flavours.

**Comment by hannwong** [comment]
@kprovance Not my theme, but from http://coffeecreamthemes.com . Yes, I would expect Coffee Cream Themes to have bought support for Redux Framework and handed that support service to us "as is". That said, perhaps they are taking on Redux Framework support themselves so as to avoid loading u with support requests? But wait, we simply clicked on a pop-up inside wp-admin to install Redux, so we might have installed a version that didn't come with support? The theme doesn't come with the files for Redux.

Your comment about symlinks being unpredictable is true.

Also, I accept that there is no real benefit to hosting a single copy of a parent theme. It is the child theme that holds a lot more files and assets. The parent theme can be a really light skeleton.

Kudos to u for answering my questions, even though u r not legally bound to do so.
I'll find ways to return the favor, to u or to Redux Framework, or both.

Thanks!
