### ISSUE TITLE
Possible to remove sidebar?

### ISSUE THREAD

**Issue by kmob2** [reduxframework/redux-framework#2535]
Hello,

Is it possible to totally remove the sidebar? I see there is an option to collapse or hide, but this has the effect that the admin panel then just becomes one big panel, where all options are on 1 page.

I just don't fully understand why there is a need for a sidebar inside of a sidebar. All the tabs are already displayed inside the wp admin menu. it seems to me that having a 2nd sidebar, is totally redundant and takes up much of the required space.

Anyway, is there an option to remove the sidebar completely? Or is that a feature that is planned?

**Comment by dovy** [comment]
Not really, since the sidebar isn't always in "view."
https://docs.reduxframework.com/core/arguments/#allow_sub_menu   Turns off the submenu items for the admin menu.

https://docs.reduxframework.com/core/arguments/#hide_expand Hides the expand button.

https://docs.reduxframework.com/core/arguments/#open_expanded Opens expanded.

IF you wanted to do something like this, you'd add your own CSS and do this:
```
.redux-sidebar {
    display:none;
}
.redux-main {
    margin-left: 0;
    border-left: 0;
}
```

**Comment by dovy** [comment]
@kprovance Should we make this part of core? Just an arg to output that exact CSS?

**Comment by kprovance** [comment]
Don't we usually stick with the Wordpress way of doing things?  :)
