### ISSUE TITLE
Can't access global variable, returns NULL

### ISSUE THREAD

**Issue by webstractions** [reduxframework/redux-framework#2575]
First, I have an older version of Redux (Version 3.4.3.2) embedded in a theme and it is working fine.

I am using the the latest version (Version 3.5.7) as a  plugin in a new theme I am working on and can't access the global variable. 

I have the option variable set up correctly as follows:

```
$args = array(
        'opt_name' => 'webby_options',
        ...
);
```
In both cases, I use a required utility function to get an option as follows:
```
function webby_get_option($id, $fallback = false) {
	
	global $webby_options;
	
	if ( $fallback == false ) 
		$fallback = '';
		
	$output = ( isset($webby_options[$id]) && $webby_options[$id] !== '' ) ? $webby_options[$id] : $fallback;
	
	return $output;
}

```
For the life me, the global keeps returning a null value!

**Comment by kprovance** [comment]
https://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by kprovance** [comment]
https://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by webstractions** [comment]
Thanks for the reply. 

I just figured it out a few minutes ago. I needed to include the `options-init.php` file on the frontend for the global to take effect. This of course raises another issue.

While the global variable comes in handy, it shouldn't come at the expense of loading the ReduxFramework configuration file on the frontend. All we need here is access to options, yes?

I am going to rewrite my get_option function to grab what I need.

**Comment by dovy** [comment]
Redux should load in both places if you use dynamic output like typography fields or background fields. If you want to roll your own, then yes don't include the config on the front end. But know that we severely limit what we do the front end automatically. ;)

**Comment by webstractions** [comment]
@dovy The fact that using the global was universal on the frontend is not apparent in the docs. Before you can use the global, you must include the `option-init.php` file. I just think that little factoid should be included in the docs. Just saying.

**Comment by kprovance** [comment]
Well, if you don't include the option-init.php (where I assume option arrays are), then you won't have options panels on your backend.  Including it is required (no pun intended).

**Comment by webstractions** [comment]
The frontend only needs access to the option values, not the configuration. That is what I am trying to get at. I can't see defining operational control for options on the frontend. They should be seperate.

The goal, in my mind, is that the global variable for options are just options. Not options and the configuration of the options. 

This might be me, but the two should be seperate. Should I start a new issue for this?

**Comment by kprovance** [comment]
Well, you could, but it doesn't mean Dovy and I are going to make changes as you think they should be implemented.  We're more or less done sinking months of time into this project with no community support.  Put another way, donations are rare, no one pays us, and we've had to take other work because of it, which means major overhauls to Redux won't be happening any time soon.  That's reality when dealing strictly in a developer's market.  They simply do not want to kick back, no matter how many millions they make with their projects.

If you believe you have a better way of doing things (that won't break the framework, or break ANY backward compatibility), feel free to fork the project and tinker away.  Pull requests are carefully vetted (as time allows) as we are REAL sticklers on backward compatibility.

Cheers.

**Comment by webstractions** [comment]
Well, that is a fine howdy-do attitude. Basically, all you need to do is point out that one file had to be incuded on the frontend in your docs. No change in code necessary.  Just show and include some sample code. I will be happy to write and contribute it for you.

**Comment by kprovance** [comment]
Just telling it like it is.  I don't sugarcoat.  It's a waste of time.

**Comment by webstractions** [comment]
BTW, I am inept to forking, making changes, contributing in the GitHub world. I can only post the code and/or suggestions. 

If I come up with solid code changes, will you take the time to review and intergrate?

**Comment by kprovance** [comment]
As time allows (although we prefer pull requests).  As I said, day jobs and family come first.  Then Redux bugs and required fixes.  Anything else, it could be weeks before review, and integration only happens if it breaks nothing else, including backward compatibility.  We've had so many people try to 'contribute' who ended up breaking code because they didn't understand the entire core.

Redux is an intricate piece of work.  You really have to have a firm grasp of PHP, Javascript and CSS.

**Comment by webstractions** [comment]
I will try to do 'pull request', but don't bank on it. The easiest thing I can do is write an article to inform other users how to use it on the frontend. There is nothing wrong with the plugin, it just needs a little bit of clarification. 

BTW, I do have a firm grasp of PHP. That is how I discovered this little glitch. Even so, it threw me for an hour or two before discovering it. It just would be nice that others can learn from it as well. 

Thanks for your time!

**Comment by dovy** [comment]
Boys, boys. chill.

@webstractions (Ronnie) The config isn't actually run in the front-end except for one loop to check for dynamic CSS. Otherwise only the opt_name is used to pull and populate the global variable.

If you prefer to roll your own, then that's totally fine. It's actually standard among all major option frameworks to load on the frontend and on the backend. This is the first time anyone has complained about it.

You're right, our getting started docs need to be improved. I'm planning on doing an overhaul soon.

No offense was made by the grasp of PHP comment by @kprovance. We have a lot of designers coming in here asking us to code for us. We, admittedly, have become a bit cynical to new requests that hint of PHP newbieness. Sorry that we came off that way.

And to clarify, the project is in no way deprecated. We just can't put in extra effort without monetary compensation, as the community was unwilling to support us in efforts.  ;)

Thank you for your patience and understanding.

**Comment by webstractions** [comment]
@dovy Thank you very much! Your explanation for the front-end loop has satisfied me. I did not dig that deeply into it, and now I feel like a complete goof-ball. 

I have been using Redux for quite a while and got off on a tear when the non-embedded plugin threw me for a loop. I take no offense in the conversation that took place, for it just made me knuckle down harder in my work. 

Yes, there just just needs to be one line added in the docs for accessing the global variable (the init file needs to be included). If you need help in reviewing or editing certain parts of the documentation, I can help. I will be available in a couple of weeks and can do my best.
