### ISSUE TITLE
Global argument 'use_cdn' => 'false' does not work

### ISSUE THREAD

**Issue by dasmaeh** [reduxframework/redux-framework#2590]
I've tried using the global argument 'use_cdn' => 'false' to force Redux loading scripts from the local server upon user request. However this does not have any effect. JS and CSS are still being loaded from cdn.jsdelivery.net
Did I misunderstand the argument or is simply not working in the way intended?

As I've tried this on localhost I can't really provide a support URL. Let me described the steps I've taken on Wordpress 4.3.0 using ReduxFramework (plugin) 3.5.7:
- My plugin <a href="https://wordpress.org/plugins/recipepress-reloaded/">RecipePress reloaded</a> is using Redux to generate its settings page. In the relevant file (<a href="http://plugins.svn.wordpress.org/recipepress-reloaded/trunk/views/settings.php">http://plugins.svn.wordpress.org/recipepress-reloaded/trunk/views/settings.php</a>) I've added `'use_cdn'			=> false,`around line 507, so no cdn should be used.
- However when navigation to the settings page at <a href="http://localhost/wordpress/wp-admin/edit.php?post_type=rpr_recipe&page=_options">http://localhost/wordpress/wp-admin/edit.php?post_type=rpr_recipe&page=_options</a> still some css and js files are loaded from cdn.jsdelivery.net. I've also tried deleting the browser cache. The issue remains.

If necessary I can try setting up a testing environment accessible from the internet.

**Comment by vburlak** [comment]
@dasmaeh for use local scripts, you need to include [Redux Vendor Support](https://github.com/reduxframework/redux-vendor-support) extension to your Redux.
Redux Framework does not have all of these scripts pre-installed, in order to take up less space.

I'm also sometimes using [Airplane Mode](https://github.com/norcross/airplane-mode) plugin, when developing on localhost without stable internet connection. Redux has recently announced support for this plugin.

Hope, it's helped.

**Comment by dovy** [comment]
Thank you @vburlak. Yes, install the Redux Vendor Support (plugin) and Airplane Mode will kick in when enabled. No need to set the argument.  ;)
