### ISSUE TITLE
Demo Import feature

### ISSUE THREAD

**Issue by nomansbeauty** [reduxframework/redux-framework#2619]
Hi,

It would be great to provide demo content import feature by default in redux framework for theme developers. Currently we are using this but it has problems we often face:
https://github.com/Webcreations907/WBC-Importer-extension

<strong>Problems that can be solved:</strong>

1. No incremental loading of data - asynchronous data loading will bypass server php execution time limits, which is often 30 sec on shared hosting (godaddy, hostgator, bluehost, etc..).

2. Should function properly with PHP Memory Limit = 64mb or more

3. There are plugins bypassing these limits efficiently such as All-in-One WP Migration:
https://wordpress.org/plugins/all-in-one-wp-migration/

4. Should give proper notifications or warnings in case of import demo is stopped or broken or network connection is lost or host server memory consumed or originating server is not responding due to lack of resources, or successful without problems etc... So user knows what caused the stoppage of import demo content.

5. And if demo content is stopped in mid for any reason, it should erase whatever was imported. So re-importing content wont show duplicated content issue (such as menu items).

6. Plugin should detect server settings and display user warnings that his server lacks certain configurations that he should make before starting import process.

Redux can either take this plugin & modify or write it from scratch with efficient code. This will save tons of headache and issues for theme authors and support teams.
Thank you

**Comment by kprovance** [comment]
Well,l here is the thing:  Such a feature would never be part of the core.  It's too much work to give away for nothing, and since developers who make bank don't like to give back, it's just not something that will likely ever happen.  That said, I wrote a demo importer extension for personal use.  It's not perfect and has no rollback feature (it's based on the WP import, which doesn't support that).  The reason I've not released it is because it's far from perfect and has no export capability, which would generally be required, and again, unless someone is going to bankroll that effort (and I'm talking thousands, not hundreds), I'm just not interested in dumping weeks worth of work into HOPING it will sell.  We've done that for years now, and the time that's gone into our extension library has not paid off.  People want our work for free (While paying extended licenses for Rev Slider and Visual Composer...can't figure that one out).  Why Redux should be the exception, I do not know.

I've toyed with the idea of posting the concept to http://ideas.reduxframework.com, and if the community wants to bankroll the project, I'd seriously consider it.  As far as free code with no return.  No, sorry.  We have families to feed too.  :)

**Comment by nomansbeauty** [comment]
Thanks for details. It was just a suggestion. Was not expecting a personal response to this. But I understand. The current campaign seems funded well.

1. Extensions are great, but 1 year limit for each product updates is not good. Rev slider & VC allows 1 extended license for lifetime updates for one product, which make more sense and affordable.

2. Adding a demonstration video for each extension is a good way, often times its difficult to see full potential of a plugin when there is only text details. This certainly help sales.

Thanks.

**Comment by nomansbeauty** [comment]
3. Tryout sites like Kickstarter & Indiegogo
4. Also there are many developers who would want to contribute their code and services to this open source framework. If you try to reach out to them. Like the WBC import extension I shared above.
