### ISSUE TITLE
Current Registered Sidebars

### ISSUE THREAD

**Issue by benjaminritner** [reduxframework/redux-framework#262]
Hey I'm trying to add a select box to the options that will list the current registered sidebars. You have any tips?

**Comment by oitentaecinco** [comment]
Hello there. 
Picking up this conversation...:

Is there any way to manually add a custom value to the select-box, when using this data field? In my case, besides the sidebar values, I need an extra option saying something like "Default".

I've tried the other way...: manually creating the select-box options by using the global $wp_registered_sidebars... but the var is empty... I believe that's because the sidebars aren't yet registered, at the moment of the redux initialization.  Is there any useful hook for sorting this out?

Thanks in advance.

**Comment by dovy** [comment]
@oitentaecinco 

The easiest thing to do would be to grab the code used in the Redux framework.php file, and override the output using this filter:

$data = apply_filters( "redux/options/{$this->args['opt_name']}/data/$type", $data );

Basically, you can make any "data" type and set anything you want. So you have the example code already there. Just grab it, and add your one extra value.  :)

**Comment by shawnhayes** [comment]
First, @dovy I love your framework. Really great work man!! Can't say enough.

Since I had a rough time with using the filter @dovy mentions I thought I would post a bit more detailed response on how to accomplish it. Maybe it will help another middle of the road programmer like me.

That said, this is what your select box should look like in your Redux config file...
```
array(
	'id'       => 'sidebar_selection',
	'type'     => 'select',
	'title'    => __('Sidebar', 'your_prefix'), 
	'subtitle' => __('Select the Default Sidebar', 'cakewalk'),
	'data'  => 'sidebar',	//This is the "data field" @dovy mentions in his above comment		
	'default' => 'sidebar',		//This should match the id from your registered sidebar
),
```
Once you have that in place your select box will pull all sidebars that are registered in WordPress. Beauty!!

I needed to remove the footer sidebars from my sidebar list since this select box is for my pages and posts sidebar. Using the filter @dovy mentions I added the code below to my themes functions.php...
```
function your_prefix_redux_sidebar_list( $data ) {
	global $wp_registered_sidebars;
		$data = array();
	    foreach ( $wp_registered_sidebars as $sidebar ) {
	    	$data[$sidebar['id']] = $sidebar['name'];				
	    }			
	    unset($data['footer1' ], $data['footer2' ], $data['footer3' ], $data['footer4' ]); //This is where I am removing the footer sidebars
	    return $data;
}
add_filter('redux/options/{$opt_name}/data/sidebar', 'your_prefix_redux_sidebar_list');
```
Be sure to replace {$opt_name} with the $opt_name you used in your Redux config file. My themes $opt_name is "swd_var" so my add_filter would look like...

`add_filter('redux/options/swd_var/data/sidebar', 'your_prefix_redux_sidebar_list');`

Hope this helps.

**Comment by shawnhayes** [comment]
First, @dovy I love your framework. Really great work man!! Can't say enough.

Since I had a rough time with using the filter @dovy mentions I thought I would post a bit more detailed response on how to accomplish it. Maybe it will help another middle of the road programmer like me.

That said, this is what your select box should look like in your Redux config file...
````
array(
    'id'       => 'sidebar_selection',
    'type'     => 'select',
    'title'    => __('Sidebar', 'your_prefix'), 
    'subtitle' => __('Select the Default Sidebar', 'cakewalk'),
    'data'  => 'sidebar',   //This is the "data field" @dovy mentions in his above comment      
    'default' => 'sidebar',     //This should match the id from your registered sidebar
),
````
Once you have that in place your select box will pull all sidebars that are registered in WordPress. Beauty!!

I needed to remove the footer sidebars from my sidebar list since this select box is for my pages and posts sidebar. Using the filter @dovy mentions I added the code below to my themes functions.php...
````
function your_prefix_redux_sidebar_list( $data ) {
    global $wp_registered_sidebars;
        $data = array();
        foreach ( $wp_registered_sidebars as $sidebar ) {
            $data[$sidebar['id']] = $sidebar['name'];               
        }           
        unset($data['footer1' ], $data['footer2' ], $data['footer3' ], $data['footer4' ]); //This is where I am removing the footer sidebars
        return $data;
}
add_filter('redux/options/{$opt_name}/data/sidebar', 'your_prefix_redux_sidebar_list');
````
Be sure to replace {$opt_name} with the $opt_name you used in your Redux config file. My themes $opt_name is "swd_var" so my add_filter would look like...

`add_filter('redux/options/swd_var/data/sidebar', 'your_prefix_redux_sidebar_list');`

Hope this helps.
