### ISSUE TITLE
Problem with unset borders being saved as 0

### ISSUE THREAD

**Issue by aljuk** [reduxframework/redux-framework#2624]
Hi there, just discovered your framework and loving it! Thank you so much for putting this together.

I design sites for local small businesses, and have a custom base theme that I build from. I'm experimenting with transferring much of the repeat coding I do to the options panel, and it's going great. 

But one thing is tripping me up - the 'border' field.

            array(
                'id'       => 'wpm-opt-header_borders',
                'type'     => 'border',
                'title'    => __( 'Header Borders', 'wpm-redux-framework' ),
                'subtitle' => __( 'Sets Header Borders', 'wpm-redux-framework' ),
                'output'   => array( '#header' ),
                'all'      => false,
            ),

I'm not using any default values in the options panel, so on first load all options fields are unset and the base theme styles rule.

However, as soon as I set any option and save the options panel, all the border fields it contains become saved, with '0' values.

This is causing me 2 problems:

1. any borders set in the underlying theme are overridden by the framework and set to 0

2. a verbose chunk of unnecessary css is output containing the many border fields I've got set up, all set to 0.

I'm wondering if I'm missing something in the setup?
Or, if not, is there a practicable way I can work around this (i.e. prevent border values that I haven't specified being saved as 0)?

![border-options-screenshot](https://cloud.githubusercontent.com/assets/1291017/10022464/437de140-614d-11e5-8bc5-2b82b702c2d4.gif)

**Comment by kprovance** [comment]
You've indicated NO version information.  Please submit a support URL:  https://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by aljuk** [comment]
Redux version is 3.5.7

http://support.redux.io/?id=i8ApVH3vKcxfnrUO5b1nScspdMHhOhwbuuAnVgZ1Z9DZfBUQ%2Fv64b0FlANWKrrg8yuIltnZTQif%2BMUWiUPdzfA%3D%3D

**Comment by kprovance** [comment]
Ugh, this is all coming back to me now, the issue with this field.

As I recall, the issue with defaulting to blank spaces caused designers who are not developers (and who do not understand the PHP empty function) a lot of grief, especially where output/compiler was concerned, because it printed blank values for the property (ie - border-bottom:  solid #ffffff ).  That was a few years ago (well, maybe 1.5ish).  Back then, I didn't know this project as well as I do now, and back then, no one wanted to dive into the field code and fix the obvious flaws in the output routine in as far as empty values went.  After a quickie look, I think I can revert the field back to blanks and fix output so it will bypass CSS properties with blank values (no value, no property is output, otherwise, we have to put something in there, and NO ONE liked inherit, which I believe is how we ended up with zeros).  So, that will be the trade off.  Blank values will produce no CSS properties within the selector (which is to say if border-top has no value, there border-top property will be omitted).

You good with this?  :)

**Comment by aljuk** [comment]
Yes definitely, I'm good with that - only output what's been explicitly set. "Blank values will produce no CSS properties within the selector" is the right way. That brings it into line with the other fields too (it's the only field I've found that sets a value even when there's no default value specified). Then it's fully flexible.

**Comment by kprovance** [comment]
A few of those older fields were written by others - people who were here before me.  Not to impugn their work, but...yeah, a lot of those fields required some redoing.  Border may be the last of them.   Anyways, I'll push the fix here in a bit.  :)

**Comment by kprovance** [comment]
Okay, v3.5.7.10 pushed.  That should fix it up for you.  :)

**Comment by aljuk** [comment]
It works perfectly, thanks.
