### ISSUE TITLE
redux causes wsod

### ISSUE THREAD

**Issue by stephangriesel** [reduxframework/redux-framework#2625]
every time i activate the redux framework i get the white screen of death? anybody else having this issue?

**Comment by kprovance** [comment]
Clearly, not, otherwise this tracker would be filled - quite literally - with hundred of thousands of issues.  Now, you indicated no version information of ANY kind, so it's difficult to respond.

See this:  http://www.wpbeginner.com/wp-tutorials/how-to-fix-the-wordpress-white-screen-of-death/   

Usually, WSOD is a configuration issue on the server.  This is something you'll need to debug and ascertain for yourself by examining your PHP error logs.  If you find reference to Redux frame in said logs, post the errors back (wtih Redux version and PHP version.)

**Comment by stephangriesel** [comment]
Yep managed to fix the WSOD. I am running WP version 4.3.1.

How would I go debugging the PHP? Had a look at the error logs and don't see anything there?

**Comment by kprovance** [comment]
You'd have to contact whomever hosts your server for information on where your PHP logs would be.  Typically, that's specified in the php.ini.

**Comment by stephangriesel** [comment]
Ok cool let me contact host, will get back to you. Thank you so much.

**Comment by stephangriesel** [comment]
Tested this on local development environment and got the following error message:
Warning: file_get_contents(http://www.reduxframework.com/wp-content/uploads/redux/redux_notice.jason):failed to open stream: Connection timed out in /opt/lampp/htdocs/www/wordpress/wp-content/themes/domik/ReduxCore/inc/class.redux_filesystem.php on line 186
