### ISSUE TITLE
Problem with redux framework

### ISSUE THREAD

**Issue by EEDARGT** [reduxframework/redux-framework#2694]
In my theme i create a lib folder then i include redux framework

functions.php
include( 'lib/ReduxCore/framework.php' );
include( 'lib/sample/sample-config.php' );
 
When i refresh wordpress dashboard i get this message

Called with an argument that is deprecated since version 2.1! Use WP_User->ID instead. in C:\xampp\htdocs\wordpress\wp-includes\functions.php on line 3570

Thanks

**Comment by kprovance** [comment]
Please be mindful of your new posting guidelines.  There is not enough information here for us to assist.

https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment]
Here's the other problem, and why I'm not convinced Redux is your issue.  Our framework makes no use of the WP_Query_Users wrapper.  That depreciated error occurs when a developer used ->id instead of ->ID.  I did a full search of our code and could find no instances of either the user wrapper or improper ID.

You might need to begin deactivating plugins until the message goes away to find the culprit.
