### ISSUE TITLE
Save script tags

### ISSUE THREAD

**Issue by davidtaboas** [reduxframework/redux-framework#2702]
Hi,

it's possible save a script tag? like:
```
<script type="text/javascript src="url.js"></script>
````
When I put a similar code in a textarea, when I reload the page, the console show me this:

![captura de pantalla 2015-11-06 a las 20 06 35](https://cloud.githubusercontent.com/assets/725182/11006095/211aea42-84c2-11e5-852e-4133985aca02.png)

**Comment by davidtaboas** [comment]
This only happens with developer mode enabled. I think it's because the object console print the script with source code of the page.

**Comment by kprovance** [comment]
It all depends on how that text is being output into your page, or if you're saving the field with escaping, or validation, or if you're outputting with escaping  That's not something we can debug.  You'll have to do some digging into your code and check your output to see why it's messing up your HTML (which is why those errors are happening).
