### ISSUE TITLE
Multi_text Undefined index error

### ISSUE THREAD

**Issue by PauloNatal** [reduxframework/redux-framework#2724]
Hi there, just wondering if you could help me on this https://github.com/reduxframework/redux-framework/issues/2709 

I am really sorry, wasn't aware that you were having a holiday there in America. And as for paying for redux, I really do appreciate all the hard work you guys have put in to it and will certainly pay for it. I havent done so yet as I have been playing with it trying to understand if it is a good fit for my project. I am now convinced that it is the best option for me and am willing to pay. 

Please let me know if you can assist with the issue that I am experiencing and where can I make a payment for the framework.

Thank you

**Comment by kprovance** [comment]
Well, the problem was - besides you declaring it MUST be Redux and nothing else, even when the error you posted was completely unrelated - was lack of required info.  This time, I'm not wasting time.  These are our support guidelines: https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md.

The error you originally posted:
```
Notice: Undefined index: custom_sidebars in C:\xampp\htdocs\empyrus\wp-content\themes\empyrus\functions.php on line 231
```

That has NOTHING to do with Redux.  If that variable is empty, it's because no default is set, and it's up to YOU to check for empty or isset.

**Comment by PauloNatal** [comment]
Thanks a lot but I do check if its empty..

		global $mytheme_option;

			$mytheme_custom_sidebars = $mytheme_option[ 'custom_sidebars' ];

			if ( isset( $mytheme_custom_sidebars ) && sizeof( $mytheme_custom_sidebars ) > 0 ) {
				foreach ( (array)$mytheme_custom_sidebars as $sidebar ) {
					register_sidebar( array(
						'name' => $sidebar,
						'id'   => 'sidebar-' . $sidebar,
						'before_widget' => '<div id="%1$s" class="widget %2$s">',
						'after_widget' => '</div> ',
						'before_title' => '<h3 class="widget-title">',
						'after_title' => '</h3>'
					));
				}
			}

**Comment by kprovance** [comment]
I'm sorry, but I've told you what information I need, and you won;t provide it.  I am not here to debug your code, unless you want to pay for that service.  Checking the size of the complete array does not check the individual values, and therein lies your problem.
