### ISSUE TITLE
text field value shows utf code instead of correct value

### ISSUE THREAD

**Issue by danielwebguy** [reduxframework/redux-framework#2725]
I use the reduxframework for some projets already and now, in the first time, I have encountered this problem.
The value in the text field is inserted in Hebrew, but after refresh (it loads it from DB) it shows the value in UTF instead of the Hebrew text.

![image](https://cloud.githubusercontent.com/assets/15003148/11337840/c70f694e-91f8-11e5-982d-4505a88e4cb6.png)

save is doing well:
![image](https://cloud.githubusercontent.com/assets/15003148/11337872/ff9f9e50-91f8-11e5-8d76-4ee1386b77f4.png)

now refresh the page:
![image](https://cloud.githubusercontent.com/assets/15003148/11337900/42b4f55a-91f9-11e5-93ba-518569c0942f.png)

**Comment by kprovance** [comment]
I don't know how exactly this is  Redux issue.  That sounds more like a server issue.

**Comment by danielwebguy** [comment]
its on local WAMP as well as on hosting server.
differents DB's

**Comment by kprovance** [comment]
You're going to have to do some research on this, as I am unable to.  Star by seeing what format the values are saved in the database as.  Redux uses the WordPress API to save and retrieve from the database.

**Comment by kprovance** [comment]
Might want to read this too:  https://wordpress.org/support/topic/text-in-hebrew-saved-as-question-marks

**Comment by danielwebguy** [comment]
hehe, I see. I know all these and its not the same.
it shows utf code, not questions mark.
also, all other options in the DB are ok, only the redux options are converted.
it converts:
בדיקה
to 
u05d1u05d3u05d9u05e7u05d4

the strange thing is, that it take away the % from the code.
the correct unicode should be:
%u05D1%u05D3%u05D9%u05E7%u05D4

you can see here:
http://unicode.online-toolz.com/tools/text-unicode-entities-convertor.php
![image](https://cloud.githubusercontent.com/assets/15003148/11361025/af6b00b0-9292-11e5-97cc-f5588e9cb668.png)

the DB collation is as needed:
![image](https://cloud.githubusercontent.com/assets/15003148/11361048/db24fc60-9292-11e5-97ee-f09e17f65a18.png)

as you can see other settings (not in redux) are show correct:
![image](https://cloud.githubusercontent.com/assets/15003148/11361084/248ae32e-9293-11e5-8e14-2d7a0af045ce.png)

**Comment by kprovance** [comment]
Yeah, I just don't know.  Sorry.  I asked Dovy about it, but as he works a real job now, I barely hear from him.  The wait could be considerable.

**Comment by danielwebguy** [comment]
So Dovy is no more part of redux framework?





*//* -------------------------------------------- *//*
*דניאל שלגי-שירה // Daniel Shalgi-Shira*
*WEBGUY Themes*
daniel@webguy.co.il
www.webguy.co.il
054-6867727
077-2044492

<http://www.webguy.co.il/>
[image: Inline image 1]

**Comment by kprovance** [comment]
His name is on the lease, so to speak, and he pops by every now and then.  See, the developers, whom we helped make MILLIONS collectively decided we were good enough for their projects, but not so much to donate to.  He had to get a day job to feed his family (and I'm one step out that particular door as well).  We erred in believing Redux was worth more to the dev community.  It is what it is.

Anyways, I tried using some Hebrew text in my theme and could not recreate the issue.  I entered it, saved it, and refreshed.  No UTF

![hebrew](https://cloud.githubusercontent.com/assets/3412363/11376800/a3371a9a-92b0-11e5-9fa5-a0a194b46864.png)

Still not sure where the problem lies.

**Comment by danielwebguy** [comment]
Wow, so are you saying that redux framework is deprecated? will not have
more development? I am so surprised. and also worried...





*//* -------------------------------------------- *//*
*דניאל שלגי-שירה // Daniel Shalgi-Shira*
*WEBGUY Themes*
daniel@webguy.co.il
www.webguy.co.il
054-6867727
077-2044492

<http://www.webguy.co.il/>
[image: Inline image 1]

**Comment by kprovance** [comment]
I didn't say that.  It may end up meaning longer wait times in the future for one of us to have free time to devote to the issue tracker.  The exception is for those who purchase premium support, for obvious reasons.  :)

**Comment by danielwebguy** [comment]
If I will buy premium support, will you be able to help me more with that?





*//* -------------------------------------------- *//*
*דניאל שלגי-שירה // Daniel Shalgi-Shira*
*WEBGUY Themes*
daniel@webguy.co.il
www.webguy.co.il
054-6867727
077-2044492

<http://www.webguy.co.il/>
[image: Inline image 1]

**Comment by kprovance** [comment]
It's not that I'm saying no, it's that I can't recreate this.  I'm not even sure if it's Redux, yet.  I'm not saying it isn't, but this whole Unicode setup for servers and software is not something I am familiar with (I see RTL is involved as well, which is also over my head).  I would have no idea where to start, and in cases like that, we're running into multiple hours, which add up quickly.  I also want to be fair, obviously.  Before we go that route, let me corner Dovy and see if he has any idea why this is happening.  Sometimes he just knows these things and can figure it out quickly (which is what I'm hoping for, in this case).

**Comment by kprovance** [comment]
Do more one more favour, paste back a support URL:  https://docs.reduxframework.com/core/generating-a-support-hash/  Doesn't matter if it's local.  It'll show us the server config, and maybe provide a clue or two.

**Comment by danielwebguy** [comment]
this:
http://support.redux.io/?id=px4gCuErZ13%2FR537p51lR2EYF5IFv4hLwYsvPv%2F4yBjuUZhdGd35zCzvFpUc6bj8RbriEaEWpU1LQGrU0vV8og%3D%3D





*//* -------------------------------------------- *//*
*דניאל שלגי-שירה // Daniel Shalgi-Shira*
*WEBGUY Themes*
daniel@webguy.co.il
www.webguy.co.il
054-6867727
077-2044492

<http://www.webguy.co.il/>
[image: Inline image 1]

**Comment by kprovance** [comment]
I tried changing my WP setup to Hebrew (MAN is that difficult to read!) and still could not reproduce.  Check out this article:  https://codex.wordpress.org/Converting_Database_Character_Sets  Are the DB_CHARSET and DB_COLLATE something abnormal?

I looked in my database, and I don't see unicode or escaping for Hebrew.  It looks like this:  `s:9:"like_icon";s:81:"fa-thumbs-o-up הָאָרֶץ, הָיְתָה תֹהוּ וָבֹהוּ, וְחֹ";`


I wonder if it's a PHP thing.  I see you're using 5.3.  Do you have the ability to change it to 5.4 or higher, just to see if it makes a difference?  (I do not, otherwise I'd have done that here).  There is SOME setting, somewhere that's causing this.  It's a needle in a stack of needles.

**Comment by dovy** [comment]
Hello @danielwebguy. I'm not gone, I'm just loving my new day job. http://owletcare.com.  ;)

Redux is not dead, but we're leaving it up to the community to offer support when possible like any other typical open source project. We'll keep Redux working, and we'll keep developing. I just can't devote all of our full-time hours to it all the time. We need to feed our families. Rest assured, however, we will not let Redux deprecate. We'll keep it as strong as it can be  ;)

Anyways, this seems rather odd. @kprovance tried to duplicate it in his own environment. So we can do a few things, but this really does not seem like it's on our end as we can save properly in @kprovance's testing. Here are the things I'd like to do and we'll do all way can to help you get this sorted.

1. If you can, 2 orders of premium support as this seems like an odd use case and truly we can't duplicate it. In other words, this is going to take more than 1 hour.
2. Provide as @kprovance as requested as well as (if possible) your wp-contents/ directory zipped and mailed to support@reduxframework.com. We want to make sure we're using your same code.
3. Access to your host server. WP login and FTP so we can test in a failed environment.

We'll help as we are able, but your problem is quite unique.   :)    Let us know and we're there for you.

**Comment by kprovance** [comment]
Since we've not heard back about it, I'll assume this issue closed.

**Comment by danielwebguy** [comment]
I have found a solution and I will update you soon for the details.
I still appreciate your trying and willingness to help me :)

Daniel





*//* -------------------------------------------- *//*
*דניאל שלגי-שירה // Daniel Shalgi-Shira*
*WEBGUY Themes*
daniel@webguy.co.il
www.webguy.co.il
054-6867727
077-2044492

<http://www.webguy.co.il/>
[image: Inline image 1]

**Comment by shnjawee** [comment]
@danielwebguy for the love of.. what was the solution for this, please?

**Comment by dovy** [comment]
Oh come now. haha.

**Comment by dovy** [comment]
@danielwebguy share the results.  :)

**Comment by shnjawee** [comment]
@dovy literally my biggest nightmare.
