### ISSUE TITLE
Redux Causes Fatal Error with over 20,000 users

### ISSUE THREAD

**Issue by emmtv** [reduxframework/redux-framework#2731]
Hello, we are building a site with redux. It was working fine until we imported over 20,000 of our users. After importing we got this error:
Fatal Error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 71 bytes) in /wp-includes/meta.php on line 837

We tried increasing our memory on php and WordPress to 512, but the problem continued.

After we deactivate the Redux plugin the error goes away and the site works fine.

Please help us to resolve this issue.

Thanks

**Comment by kprovance** [comment]
Um...we're gonna need just a little bit more information (especially since meta.php is NOT one of our files).  Please review:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by dovy** [comment]
Yea, very odd.

**Comment by emmtv** [comment]
Thanks for looking into it. From our understanding it seems that the Redux plugin is having some side effects on the WordPress call when having a large amount of users.

**Comment by kprovance** [comment]
Yeah, we can;t look into it, because you've not provided any of the information I asked for.  And you're merely assuming it's Redux simply because it only happens when it's loaded?  Appearances can be deceiving.  You've not show us any hard evidence Redux is the real problem.  Either way, if you won;t read the link I supplied and return ALL the required information, we won;t be able to help.  I'd also consider turning on WP_DEBUG and installing the Debug Bar plugin so you can get a stack trace of the calls up to the error.  We can tell then if Redux is truly the culprit.

And more importantly, are you the theme author or a user of a theme that uses Redux?

**Comment by kprovance** [comment]
It's still a memory issue.  Redux is probably pushed the server to it's limits...but again, I can't make that determination without the support URL.  Read here:  https://wordpress.org/support/topic/fatal-error-out-of-memory-6

Her issue was:  Fatal error: Out of memory (allocated 67108864) (tried to allocate 35 bytes) in /home/maxlife/public_html/healthydinnerrecipesreview.com/wp-includes/meta.php on line 310

The solution was:
==========
OK, my problem just got solved!!!

Got it from this http://wordpress.org/support/topic/fatal-error-out-of-memory-messages?replies=24#post-1929111, thought I'd share it with you guys :

 THIS TO BE ENTERED IN THE WP-CONFIG FILE WHICH IS IN THE ROOT OF THE WORDPRESS SETUP:
ENTER AFTER: define('ABSPATH', dirname(__FILE__).'/');
THE FOLLOWING:

define('WP_MEMORY_LIMIT', '64M');

I ALSO CREATED A PHP.INI WHICH I UPLOADED TO THE PLUGIN FOLDER IN WP-CONTENT:

memory_limit = 128M; Maximum amount of memory a script may consume (64MB) 
max_execution_time = 45; 
upload_max_filesize = 10M; 
post_max_size = 20M;

Hope this helps!
========

**Comment by kprovance** [comment]
No reply or follow up.  Closing.
