### ISSUE TITLE
GALLERY SETTINGS is not being saved

### ISSUE THREAD

**Issue by waksiu** [reduxframework/redux-framework#2757]
We can't save changes in GALLERY SETTINGS, for example changing size is not being saved. After reopen gallery setting, default values are shown.

![image](https://cloud.githubusercontent.com/assets/16332744/11863735/b30f1736-a496-11e5-985a-543b9be16645.png)

**Comment by kprovance** [comment]
That does appear to be the case.  My guess is that additional javascript may be required to save/recall those settings.  I'm not sure.  We're dealing with a very,very small use case here for what is sure to be many hours of research and work.  If you're will to purchase some premium support to support said work, it would get done sooner, rather than later.  If not, I'll add it to my list of things to look into as time allows.  Can;t give any ETA on that.

**Comment by kprovance** [comment]
Upon a little research, those settings are specifically for insertion into a post/page.  The are not applicable to the Redux gallery field.  I'll hide them in the next version.
