### ISSUE TITLE
Redux Gallery problem with size image

### ISSUE THREAD

**Issue by mesmeriseme** [reduxframework/redux-framework#2759]
Hi there
I'm new here and i have a problem with gallery - when i want change thumbnail to full size image or add new image it's always showed as a thumbnail and redux  don't save this. It's always is thumbnail image. What's could be the problem?

**Comment by kprovance** [comment]
It's not possible to change this setting currently.  Redux specifically selected the 'thumbnail' size from the wp_get_attachment_image_src function.  It's entirely possible to make this an option, but as it's not a wide user case scenario, we'd need support in the form of premium support to accomplish it now.  Otherwise, it's something that goes on our todo list and we'll get to it when we get to it.  :)

Alternatively, Redux is a community project.  You're free to add the feature and submit a pull request.  If it passes muster, we can add it that way as well.
