### ISSUE TITLE
Ho to disable unnecessary notices?

### ISSUE THREAD

**Issue by hamdan-mahran** [reduxframework/redux-framework#2801]
Hello,

Thank you so much for this awesome framework!

I want to disable the unnecessary notices like the following screenshots?
http://envato.d.pr/1hSGm/4BiscHbu
http://envato.d.pr/1gJqR/tQmKBnc1

Note: I install redux-framework inside my theme, not as a plugin.

Thank you so much!

**Comment by kprovance** [comment]
I just released a new extension to deal with this: https://reduxframework.com/extension/ad-remover/

Cheers.

**Comment by hamdan-mahran** [comment]
$60 to remove ads! :D 
Thank you so much!

**Comment by matyushen** [comment]
For a piece of code that adds zero functionality to the framework and just removes the ads(not really ads), $60 is a huge price. Honestly. It's just not nice. Don't get me wrong. I respect you guys for all the work and effort you put in the framework and totally understand that you need to earn a buck. But this is not the way. The extensions are to extend the framework. And I absolutely agree to pay for that, I actually purchased meta boxes extension, and it's great. Those notice, ad and dashboard widget are for developers only, not for the end user of the theme. I do not mind having them around while I'm working on the theme, they are useful. But as soon as dev mode is set to false they must be gone. Development is over. Otherwise, what is the point in dev mode? 

Anyways, I've purchased the extension and have one question. When 3.5.8.15 will be released on wp.org? I'm using Redux as a plugin and can't submit the theme to TF before 3.5.8.15 goes live on wp.org.

**Comment by kprovance** [comment]
We'll have to agree to disagree then.  

Dovy updates the wp.org svn.  I'll ask him about doing it ASAP.

**Comment by matyushen** [comment]
@dovy could you please give an ETA of v.3.5.8.15 on the wp.org?

**Comment by kprovance** [comment]
Version 3.5.9 has just been pushed to wp.org.  Cheers.  :)
