### ISSUE TITLE
Global variable and soft rejection

### ISSUE THREAD

**Issue by sodbileg** [reduxframework/redux-framework#2805]
I just got a soft rejection on ThemeForest with the message below.

>global variable should be used restrictively and only if theme really needs to. It's highly recommended not to use them at all just to keep things out of the global namespace, they're poor coding practice.

I only use global variables to get admin options from Redux framework. For example, I have `global $mondo_admin_data;` in **header.php** file to get navbar style. Is there any workaround for this? Is it possible to get option values without `global` variable?

**Comment by kprovance** [comment]
I don't even know how to reply to that one.  TF has simple gone made with their guidelines.  The whole point of an option framework is to access data through a global variable.

You could try centralizing a routine to pull your options, necessitating only one global variable.  Otherwise, you're going back to get_option, which with Redux is possible, but will requir extra parsing with certain fields.

**Comment by kprovance** [comment]
I spoke with one of the admins over at TF review.  He said:  "If you're using a Framework, you can leave framework_name as the prefix, but whatever falls under the theme would need to be theme_name. Text domains should match your theme name. Loading an additional one is fine. Global is fine, as long as you are using it inside of a class or function."  There ya go!  :)

**Comment by sodbileg** [comment]
Hi Kevin,
Yep, I also spoke with the reviewer and got that response. It was my bad coding practice as I defined globals on top of files. Thanks for your reply and time :)
