### ISSUE TITLE
Redux not compatible with PHP 7

### ISSUE THREAD

**Issue by contempoinc** [reduxframework/redux-framework#2812]
Recently noticed redux isn't compatible with PHP 7 is there going to be a fix for this soon, or?

**Comment by dovy** [comment]
Please provide some additional details, like the error.  :P

**Comment by aristath** [comment]
Looks perfectly fine to me...
I've been using it with PHP7 for a month without any issues.

**Comment by kprovance** [comment]
There was an issue in the previous version where the raw field would not parse with markdown, but that's since been resolved.  Otherwise, if you believe there is an issue someplace, we'll need to know the specific error (including module and line number, and trace info if available), plus the things mentioned here:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by contempoinc** [comment]
It won't load any of the options pages just shows blank, running 3.5.8.10 had multiple buyers raise tickets all about the same thing and downgrading to PHP 5 fixes the issue.

**Comment by kprovance** [comment]
First, you need to review the posting guidelines I posted back to you.  That is required information.  You'd also have determined we've upgraded Redux since the version you have.  Always use the latest version, first and foremost.

Once you've done that, and if the issue exists, you have two options:  First, if you want us to go on your server and debug, that is a premium service (as outlined in the posting guidelines).  Second, you can dig a little deeper and provide us with some error information.  You'll have to comb your PHP error logs and look for messages that pertain to Redux, and include them with the requested information from our posting guidelines.

**Comment by kprovance** [comment]
Closing issue due to lack of reply.
