### ISSUE TITLE
ThemeForest reviewer today feedback - about Theme Check

### ISSUE THREAD

**Issue by azexo** [reduxframework/redux-framework#2852]
3: Please resolve all warning and required messages output by the Theme Check plugin, https://wordpress.org/plugins/theme-check/ - Anything you include within your theme must be up to the same standards as the theme itself. 

i have only redux warning and required messages

**Comment by kprovance** [comment]
Sorry about that.  Unfortunately, you're going to have to be a bit more specific about what the issue is exactly.

**Comment by azexo** [comment]
reviewer saw only this messages
https://drive.google.com/file/d/0B9F2Y3cqc8pCTVZtaGJ3b0Q4Rzg/view?usp=drivesdk

and this is second his answer about redux in themecheck

**Comment by azexo** [comment]
what you think about some update this code like this for TGM ?

https://github.com/TGMPA/TGM-Plugin-Activation/compare/develop...Otto42:develop

**Comment by kprovance** [comment]
TGM isn't our project.  :)

@Dovy, you might need to read the screenshot provided.  I don't know what the answer is, except to say because Redux functions as both a plugin and embed, those calls are needed, but they are used conditionally.  That message about the shorttag in the regex is a false flag.  There is no shorttag, it's part of the regex statement.  You can explain that to the reviewer.

**Comment by dovy** [comment]
If you're embedding you have to comment them out manually. That's all there is to it and be sure you don't use them.

We strongly suggest you use TGM instead so Redux can be updated without your interaction.
