### ISSUE TITLE
Activating Redux framework plugin in wordpress causes Internal server error

### ISSUE THREAD

**Issue by longtoe** [reduxframework/redux-framework#2886]
I have a theme which uses the Redux framework plugin which is hosted on a windows 2008 R2 server. When I activate the plugin the Wordrpress installation automatically shows a Internal Server error. The theme authors have stated that it is that redux does not work on windows server and that it only works on a Linux server.

Is there a fix for this?

**Comment by kprovance** [comment]
I work on Redux is Windows every day.  Unfortunately, it sounds like you have a theme author who doesn't want to work for a living.  He has to go into your server and determine which setting it making this happen.  He needs to look at PHP logs, etc.  Since he is the one who got paid, it's his job.  For us to do it would be a premium service.

**Comment by dovy** [comment]
We're willing to help, we just cannot offer free labor when you have an author of whom you have paid. I hope that makes sense.

Best of luck to you, and let us know if you need further assistance.
