### ISSUE TITLE
Adding the Section Name (The title) on the Header.tpl.php of the Redux

### ISSUE THREAD

**Issue by flovro** [reduxframework/redux-framework#2930]
Hello, 

I like to take out the title or the name of the section from the content.tpl.php, from where is now, and to display on the header file.

Is there a way to do that? 

Thanks

**Comment by kprovance** [comment]
I honoestly don't think there is any simple way to do this.  All the section HTML is preloaded on the page, and displayed per section tab, when clicked on it.  The section title isn't loaded on demand (meaning a variable that changed that can be inserted into the header on click).  I imagine it could be done with a bit of custom javascript, but such a thing doesn't fall under the scope of free support.

Dovy might know if there is another, way, but as I said, since the load of section is dependent upon the click of the panel tab, it becomes a javascript solution.

**Comment by dovy** [comment]
You can just set the section title to "" and it should disappear.  :P

**Comment by kprovance** [comment]
He wanted to add it.  ;-)

**Comment by dovy** [comment]
Ohhh. Interesting.  I see.

**Comment by flovro** [comment]
Hey :))

As kprovance said I will do this via javascript. :)) Many thanks
