### ISSUE TITLE
Issue with extension_customizer.min

### ISSUE THREAD

**Issue by DJMIMi** [reduxframework/redux-framework#2956]
When WP_DEBUG is enabled and extension_customizer.js is loaded there is no issue in working with WP LIve Customizer but as soon as it is disabled and extension_customizer.min.js is loaded Live Composer breaks with this error http://prntscr.com/ax2mbf this started to happen with latest update of Redux.

**Comment by madebycm** [comment]
Confirmed, how can you force WP to load the non-minified version of extension_customizer.js?

**Comment by DJMIMi** [comment]
Hi madebycm

You enable WP_DEBUG in wp-config.php

**Comment by zokky93** [comment]
Same here. Here it's the support url http://support.redux.io/?id=XkD6LeQoHRRZukG9FSDwVycScphYbcY7SLPPnEp%2BIu8jSydj6YbAOP4FTcATmtnSbpRTcKxdpb%2BtW6QzkpLiww%3D%3D 

When debug mode is set to false, the customizer it's not working. 

Thanks!

**Comment by dovy** [comment]
I'll get on it. Thanks @zokky93 for the support URL for testing.

**Comment by dovy** [comment]
So I fear I can't reproduce this. I tried installing Redux via this repo as well as WordPress.org as a plugin. Then I ran the config @zokky93 was using. Unfortunately, the customizer ran without a flaw and dev_mode was off.

So that means your issues above are one of the following:

* You may be running an old version of Redux. To test that, try installing Redux as a plugin via WordPress.org or this repo. If you have the plugin installed and activated, it will override anything you have embedded in your product.
* You're running your config too late via hooks. Try running your instance of Redux early without waiting for any hook. The customizer especially has some hooks that fire earlier than `init`, so if you're waiting until later it's probably not running the enqueue and it can't since the customizer enqueue hook has already run.

Best of luck! :)

**Comment by DJMIMi** [comment]
HI dovy.

I was talking about WP_DEBUG set to false not dev_mode to false.
Nothing is hooked in too late or too early since options are build out of sample file you provide. Further more theme was created a year ago and options never changed and everything worked until this version.

Customizer works when extension_customizer.js is loaded with WP_DEBUG is set to true but once it is set to false and extension_customizer.min.js is loaded error starts to happen. I copied file from this repo and still same is happening Version is 3.6.0.1 and with it the issue started. 

Regards,

**Comment by dovy** [comment]
<script type='text/javascript' src='http://reduxclean.dev/wp-content/plugins/redux-framework/ReduxCore/inc/extensions/customizer/extension_customizer.min.js?ver=2.0.0'></script> is loading on my instance.

We haven't changed the enqueue code at all. Perhaps WP changed the hook they load the customizer, but like I said I can't reproduce the issue at all.

If you don't have that file included, then it's not firing...

**Comment by dovy** [comment]
Wait, what version of PHP are you using?

**Comment by dovy** [comment]
And browser.

**Comment by DJMIMi** [comment]
Hi dovy.

The issue is not in enqueue code but in minified version of extension_customizer.js
PHP 5.5.12 but I do not see how can this be related since issue is in JS
Browsers firefox 45.0.1, chrome 50.0.2661.87  they all fail

Again the issue is in code since unminifed version of extension_customizer works fine while minified version does not. Sounds like bug in the code which shows itself once the file is minified.

Regards.

**Comment by dovy** [comment]
The issue @DJMIMi is I'm running the current minified version without problem locally. It's hard to fix something I can't reproduce...

**Comment by dovy** [comment]
Scratch that, just reproduced it.  :P

**Comment by dovy** [comment]
Just pushed some code to the repo. Let me know if that fixed it.

**Comment by DJMIMi** [comment]
Hi dovy.

Awesome, you nailed it. Great job.

Regards.

**Comment by dovy** [comment]
Deploying to WP.org now

**Comment by dovy** [comment]
Released.  :P
