### ISSUE TITLE
Gradient Picker

### ISSUE THREAD

**Issue by Bluxart** [reduxframework/redux-framework#2977]
Hi, not possible add this for gradient field? 
https://github.com/evnix/gradx

The default gradient of Redux it is limited only from two colors.

**Comment by kprovance** [comment]
You could either author your own extension to do so, or pay us to do it for you.  :)

**Comment by Bluxart** [comment]
Can you send me an email for talk about this?

**Comment by Bluxart** [comment]
@kprovance Let me know how to pay for this customization. What steps I need to follow? Thanks

**Comment by kprovance** [comment]
my email is kevin@reduxframework.com.  But honestly, after looking at the project, you're looking at at least several hundreds of dollars here, possibly pushing a grand to replicate that.  In the end you'll still have to do most of the gradeitn CSS on the front end and Redux doesn;t ypically handle that kind of thing.  It outputs saved options, which is why we have the gradient field we do in which it returns the saved values and devs plug into their own gradient routines.

**Comment by Bluxart** [comment]
Thanks, I send you an email for another paid customization if possible.
