### ISSUE TITLE
Redux Framework make Add to cart button disappear

### ISSUE THREAD

**Issue by benchun1** [reduxframework/redux-framework#3013]
Hello supporters

My issue is "Add to cart" button disappear when Redux framework plug in activate. And my theme required this plug in and I don't know what's shall I do this moment.  I will really appreciate if you respond with troubleshooting solution or any considerable suggestion. 

I am runnging "SPORTEXX" woocomerce theme and add to cart button not show up on product detail pages. With redux framework deactivate, it show.  However, I believe this plug in required to install on this theme, when deactivate some of option such as "logo" change won't work. 

please advise,

**Comment by kprovance** [comment]
You'll have to get with the author of the theme on that one.  They need to make the determination why that's happening, that is, supporting their own work.  if it's a Redux issue, they will have to report it to us, as we do not offer support directly to users of themes, especially where the theme is probably the culprit.  Sorry.  Thanks.

**Comment by benchun1** [comment]
Thanks for quick responds, 
I already tried to contact theme maker, wp support, and woocomerce support. They all seems to have no obligation to support this kind issue so I finally landed here.. Is it nowadays online support? or am I just not lucky enough?

**Comment by kprovance** [comment]
Well, regardless what the theme author says, he is 100% wrong.  if you purchased that theme from ThemeForest, you should complain to them that he is not supporting his work.  They will get on him about it.

Now, I do not have access to that theme.  I would have to but it (which I don't want to do), download it and debug it.  Since it's not my code, and not my theme, and you paid him and not me, where does the support obligation lay here?  I would be spending several hours doing the job of the theme author and not being paid for it.  Again, if it's truly a Redux issue, THEY need to make that determination, because the issue is very likely in their code, and not ours.  If it is our code, they should have caught the issue first before releasing the theme.  If it's an issue with your server (which it could well be), they have to do the work to make that determination,  if it's a conflict with Redux, then they need to file a report with us.  I wish I could be of more help.  The fact is, it's the theme author's responsibility.

**Comment by kprovance** [comment]
I might also voice your concern here:  http://themeforest.net/item/sportexx-sports-gym-fashion-woocommerce-theme/12388957/comments

**Comment by kprovance** [comment]
Or here:  http://themeforest.net/item/sportexx-sports-gym-fashion-woocommerce-theme/reviews/12388957

**Comment by ibndawood** [comment]
Hello @kprovance, Thank you very much for your informing us about this issue. I really appreciate that. I'd also like to thank you for your wonderful plugin. I completely agree with you on your views on support. You are under no obligation to support our theme. We support all our requests and our response time is 24 hours. I don't @benchun1 have contacted us before. @benchun1 has just raised a request about 26 mins back which is 1 min after @kprovance's email.

I believe the reason could be that he has enabled catalog mode which disables "Add to Cart" button and other shopping functionality. Please navigate to Sportexx > Shop > Catalog Mode and disable it. 

If you have any other questions please email our support and we are happy to assist. 

Thanks,
Ibrahim
