### ISSUE TITLE
Redux Framework options translation

### ISSUE THREAD

**Issue by kabeza** [reduxframework/redux-framework#3024]
Hi
I've bought a theme, babykids from nickdarkthemes.com which has Redux Framework already integrated. I'm burning my brain trying to make Redux options translated strings to show, but am having no luck. Theme's author wants to charge me additional u$s 50 for troubleshooting this problem.

Please look at this image:
![imagen_221](https://cloud.githubusercontent.com/assets/274856/16101002/e0ff70d8-3338-11e6-97e5-8744517e372d.jpg)

If I make the translation directly in the themes/babykids/framework/sample/config.php, it works. 
**Is there any way to debug why isn't it taking the translated string from the .po/.mo file correctly?**

Thanks

**Comment by kprovance** [comment]
Well, unfortunately, you might not much dig my answer either. Those translation strings are part of HIS theme and not part of our Redux core.  He needs to fix it.  However, there isn't much troubleshooting involved here, really.  I can tell you exactly what's wrong.  In the __() function, he left 'redux-framework-demo'.  It needs to be whatever his translation domain is.  Again, he needs to fix it, since he didn't bother to change that setting from our sample config file to whatever the domain is for his theme.  It's that simple.  :)

**Comment by kprovance** [comment]
Also, you can tell him the Redux guys are asking for $50.00 to point out his own mistake.  ;-)

**Comment by dovy** [comment]
Yea, he didn't come up with his own domain for strings, so you'd have to load it with that specific prefix and that language file is never run since it doesn't exist.

You COULD keep it as it is, but you're going to have to init those language strings by calling the proper WordPress function. Alas, we are sorry for your situation in all of this. We wish you the best.

**Comment by kabeza** [comment]
Thanks @dovy . 
I changed domain in all the references (275 lines) to theme's name, but still don't work. I'll keep trying to debug this problem.
