### ISSUE TITLE
Redux-framework does not work with new version of wordpress.

### ISSUE THREAD

**Issue by roping** [reduxframework/redux-framework#3030]
I have used redux-framework for my theme option few days ago.But when i updated wordpress into 4.5.3 then redux-framework not working..Now what i will do?

**Comment by kprovance** [comment]
Start here:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md  since 'not working' tell me pretty much nothing.  :(

My theme uses Redux and the latest WordPress without issue, so depending on what 'not working' means, it's either server related or config related, most likely.

**Comment by roping** [comment]
I have built my theme about 6months ago with old version of redux that time it was great but right now it does not work with 4.5.3 wordpress ...Do i need to update redux into new version ?

**Comment by kprovance** [comment]
Did you read the link I sent you?

<blockquote>
If you are a developer, using Redux Framework in your project, PLEASE check to see if you are using the latest version of Redux by checking this repository. If you plan to reporting an issue with any version BUT the latest version, we are going to ask you to upgrade to the latest code base anyway to see if your issue persists. Please save yourself and us some time by taking this simple step first. Thanks!
</blockquote>

**Comment by roping** [comment]
Thanks for your help..I am going to use new version.
