### ISSUE TITLE
HTML encoding of characters in CSS editor

### ISSUE THREAD

**Issue by maketimetodesign** [reduxframework/redux-framework#3034]
Hi, 

I'm trying to add valid CSS using the custom CSS options screen that my theme (Broker) has. I noticed the editor was encoding > characters as &gt; which was annoying but not the end of the world. But now, I've come to add a pseudo element with content: " "; and the quotation marks are being encoded. 

I can't be sure if this is Redux or maybe the theme?

Anyone else spotted this? 

Thanks, 
Tom

**Comment by maketimetodesign** [comment]
Apologies I'm using v3.6.0.2 on WP 4.5.3 with the latest [Broker theme](http://broker.commercegurus.com/) from Themeforest.

**Comment by kprovance** [comment]
Theme issues go directly to the theme author.  You paid them for support, after all.  :)

**Comment by maketimetodesign** [comment]
Thanks for pointing out the obvious, I had been to them, but as I pointed out I wasn't sure if this was an issue with Redux or not, hence asking here.

Having not paid you I'm not entitled to ask? Thanks all the same then.

**Comment by kprovance** [comment]
You can ask, but if you read our support guidelines, we made it clear that theme users must go to their theme author for support.  If the theme author discovers an issue (since we have no way of knowing if they modified the core or are using other hooks/filters to change things) and it's in fact related to Redux, then they need to report the issue to us.  Going over the theme author's head means we'd have to debug the theme code, which is the theme author's job.  Sorry.

**Comment by maketimetodesign** [comment]
Yeah, apologies, been a long day and was scrabbling for answers. Makes total sense, I'm just pissed at having to work with over engineered and convoluted themes; entirely not your fault! Thanks.

**Comment by dovy** [comment]
We really appreciate your understanding.
