### ISSUE TITLE
Not working typography and ace_editor fields

### ISSUE THREAD

**Issue by GalinaBublik** [reduxframework/redux-framework#3041]
Not working typography and ace_editor fields
http://take.ms/X9vVv

WordPress version 4.5.3,
Redux-framework version 3.6.0.7

**Comment by kprovance** [comment]
Please review our support guidelines and provide a support url.
On Jul 7, 2016 9:40 AM, "GalinaBublik" <notifications@github.com> wrote:

Not working typography and ace_editor fields
http://take.ms/X9vVv

WordPress version 4.5.3,
Redux-framework version 3.6.0.7

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/reduxframework/redux-framework/issues/3041>, or mute
the thread
<https://github.com/notifications/unsubscribe/ADQRi4bG-80OraJw0SroUA-K0Snt5Fmbks5qTQHcgaJpZM4JHFpA>
.

**Comment by GalinaBublik** [comment]
Sorry, 
I am developer, create new theme on localhost. Dev_mode is on.
NO error in console.
I sow this issue after update WP. try update redux, but fields not reanimate.
Please help.

**Comment by kprovance** [comment]
The support URL is required.  We are not able to offer support without.  Please review the link I sent you again.  If you are unwilling to provide we, we can't help.

**Comment by kprovance** [comment]
Closing this ticket due to lack of needed information.  If the problem persists, please open a new ticket and include a support URL as explained here:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md
