### ISSUE TITLE
Can't save br or p tag 

### ISSUE THREAD

**Issue by 2pay** [reduxframework/redux-framework#3042]
**I have issues:**

1. Version:
Wordpress 4.5.3
Redux Framework 3.6.0.2

2. This is my code:
```
array(
                            'id'       => 'footer-copyright',
                            'type'     => 'editor',
                            'title'    => __( 'Copyright Info', 'myproject' ),
                            'desc'     => __( 'Copyright Info', 'myproject' ),
                            'default'  => 'Powered by ScriptsMartket.',
                            'args'   => array(
                                'teeny'            => true,
                                'textarea_rows'    => 10
                            )
                        )
```

When i enter new line but nothings in code (not insert p or br tag). I change to text mode and enter:

```
My Project<br />
Address: Abc<br />
....
```

When Save first it working but seconds then br and p is remove.

Sorry my english.

**Comment by kprovance** [comment]
It's not redux doing it.
On Jul 8, 2016 4:05 AM, "Vu Van Dung" <notifications@github.com> wrote:

*I have issues:*

   1.

   Version:
   Wordpress 4.5.3
   Redux Framework 3.6.0.2
   2.

   This is my code:

array(
                            'id'       => 'footer-copyright',
                            'type'     => 'editor',
                            'title'    => __( 'Copyright Info', 'myproject' ),
                            'desc'     => __( 'Copyright Info', 'myproject' ),
                            'default'  => 'Powered by ScriptsMartket.',
                            'args'   => array(
                                'teeny'            => true,
                                'textarea_rows'    => 10
                            )
                        )

When i enter new line but nothings in code (not insert p or br tag). I
change to text mode and enter:

My Project

Address: Abc

....

When Save first it working but seconds then br and p is remove.

Sorry my english.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/reduxframework/redux-framework/issues/3042>, or mute
the thread
<https://github.com/notifications/unsubscribe/ADQRiyg0254WYCZMLpvDwpl9EyzuGLYnks5qTgS_gaJpZM4JHztr>
.

**Comment by 2pay** [comment]
@kprovance What do you mean?

**Comment by kprovance** [comment]
This has been asked and answered before.  Redux does not trip characters.  The field is created using the WP API that does this.  It passes any arguments you add untouched.  It captures the save exactly as typed and stores it, and recalls it the same way.  That's it.  If the content is being altered, it is by something else, maybe a remove_empty_p hook or the like from another plugin on filter.  It would be impossible for me to say.  You're going to have to do some digging on that one since it's not something we support.  You'll have to check the codex, but I do believe the wp_editor's wpautop is set to true by default.  I think it needs to be false to automatically add paragraph tags.
