### ISSUE TITLE
Uncaught TypeError: a.redux.hideFields is not a function

### ISSUE THREAD

**Issue by adims** [reduxframework/redux-framework#3045]
I have included Redux on theme, not as a plugin

Redux version is 3.6.0.2
Jquery is jQuery v1.12.4 
Wordpress version 4.5.3

Everything was working perfect the other day and Now I have this error in console. Becasue of this no sections open (screenshot attached).

![screen shot 2016-07-12 at 1 02 02 pm](https://cloud.githubusercontent.com/assets/2819709/16758394/ed9b3c48-4830-11e6-9f84-4bd2586bc3c0.png)

**Comment by kprovance** [comment]
I believe this was fixed in the latest version of Redux available from this repo.  Please update to that version.  If the problem persists, please start a new issue, but note our support guidelines and include a support URL, as explained here:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md
