### ISSUE TITLE
Error With Color_RGBA Field

### ISSUE THREAD

**Issue by manikbajaj** [reduxframework/redux-framework#3051]
Team, 

I am facing another issue with redux. While i am using color_rgba field and using an option for allow_empty. So i am able to empty the option. so for the first time I can see all value blank like 

array('color'=>'' , alpha=>'' , 'rgba'=>'');

But after reload the page and next save(considering without change in that color_rgba option) it changes the rgba value like 0 , 0 , 0 so the output shows like in below array

array('color'=>'' , 'alpha'=>'' , 'rgba'=>'0,0,0);

Please help me as i need all the value should be empty if we didn't selected any value.

Thanks

**Comment by kprovance** [comment]
Required:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by manikbajaj** [comment]
I am a theme develoepr by using redux. 

I have updated redux with latest version.

After update there is two issues which I was facing. I raised one issue before couple of days and your guys denied to support us. and again we are facing another issue.

https://github.com/reduxframework/redux-extensions/issues/283

Thanks

**Comment by kprovance** [comment]
That was not refusal, that was you NOT reading our support guidelines via the link I sent, and you not supplying us with the required saupport URL.  No support URL, no support.  I am not playing this back and forth with clients anymore, especially when we have this system in place to avoid such a thing.  So, if you are refusing to read those guidelines and generate a proper support URL, then no, I cannot assist you.  I honestly don;t see what the problem is, it's a very simple process to do so and helps US to help you.

**Comment by kprovance** [comment]
Never mind.  I fixed it without your assistance.  In the future, please provide a support URL with ALL requests.  It's required, I ask everyone to do it now.
