### ISSUE TITLE
Missing Elusive Font Icons

### ISSUE THREAD

**Issue by streamworksaudio** [reduxframework/redux-framework#3063]
Hi there,

My theme (Sprout Theme) uses the Redux Framework for it's theme options panel. But recently I have noticed that some of the fonts icons (specifically arrows) are missing.

This happened suddenly, and the theme author thinks I should install the Redux Framework plugin, but to my knowledge the theme comes with a 'Theme Options' plugin which is built off Redux Framework (version 3.5.4). So I am not sure how installing Redux Framework on top of that will help.

So I am reaching out to you guys, to see if you have any idea as to why some of the Elusive fonts have suddenly stopped showing? As far as I can see they are (css and font files) on the server where they should be. They are just not loading.

Any insights you may have would be appreciated.

Cheers

**Comment by kprovance** [comment]
Hi.  You need to contact the theme author for support, as that is what he got paid to do.  I have NO idea what kind of code he may have added or filters, so he'll have to make that determination.  If he finds an issue, he needs to report it to us.  We do not actually support theme users.  Sorry.

**Comment by streamworksaudio** [comment]
Thank you for your reply.

I totally understand where you are coming from.  It just very frustrating when the theme developer says 'There is something wrong with Redux or the Elusive Fonts - contact them'.  Kinda go round and round.

I tried downloading the Fonts on their own and replacing the ones that came with the theme's plugin - but that made all fonts not work (not just the arrows).

I guess I will have to bug the theme developer to figure it out.

Cheers

**Comment by kprovance** [comment]
I assume you got the theme from ThemeForest?  Their support guidelines are very specific in that regard.  You can always contact TF and report him for failing to provide support.  Thing is, if we have to look into it, we have to download his theme and spend our time on it, which would fall under a premium service.  Sorry about this, but this is why TF has these kinds of guidelines.  Many uthors look to pass the buck, because it means having to go into their code and see what's wrong, which can be time consuming.  I know, I do it every day.  ;-)

**Comment by streamworksaudio** [comment]
No worries I understand.  I will push the developer - after all I already gave him my money.  It is the least he/she can do ;-)

Thanks again

**Comment by streamworksaudio** [comment]
Just an update incase it could be something with the framework.

The theme author is being no help, jsut says it's all Redux and he does not know what the problem is.

Today I tried something on my own.  I manually updated the redux-framework directory in the plugin's dir. to 3.6.0.2 that I downloaded from the WordPress rep.  But the problem persists.  Just those darn arrow fonts are not rendering.

**Comment by kprovance** [comment]
What's the authors themeforest name?  I'll take it up with him

**Comment by kprovance** [comment]
Never mind, I see the thread on TF.  What happens if you disable the Redux plugin and let the version he has embedded run?

**Comment by streamworksaudio** [comment]
Thanks Kevin,  I really appreciate it.

The author is:

https://themeforest.net/user/envirra

And just in case... here is a screenshot of the problem...

https://drive.google.com/file/d/0B5QmcW_8DZ4MQ0RMZEJEdHFrX3M/view

**Comment by streamworksaudio** [comment]
I tried installing the plugin on it's own, but my site stopped working (had to restore a saved image).

But with his embedded version everything works expect the missing icons/fonts.

Should I try to install the Redux framework plugin again?

**Comment by kprovance** [comment]
Dammit, I hate when theme authors pull this crap.  It IS his responsibility to do the debugging, as noted here:  https://themeforest.net/page/item_support_policy, specifically:  "Answering technical questions about the item (and included third party assets)".  This means he should have asked you for some kind of temporary admin access so he could actually see the issue, and maybe do some debugging through the dev console.  He has no way of knowing if it's a Redux issue until he takes the time to make that determination.  If it is, then he comes to us and we sort it out.  Sending his customers to us is now how support works.  Ugh.

No, if installing the plugin caused you site to stop, then he must have made some kind of modification, or has theme code getting in the way, but again, only HE can log onto your server to make that determination.  

If you want to send me some kind of temporary admin access to your site, I'll take a quick look in the dev console to see if something jumps out.   If it were a Redux issue, all our users would be affected, and the issue tracker would be full of help requests.  If it turns out to be a theme issue, I won't be able to fix it.  My email is kevin@reduxframework.com

**Comment by kprovance** [comment]
The link you sent me gives me a 403 forbidden message.  I tried to email you about it, but your mail server rejected it.

**Comment by streamworksaudio** [comment]
Interesting about the mail - not sure what happened there.

I had WP Admin (and wp-login.php) locked with Apache.  I just unlocked them, hopefully your should be able to access the site (admin) now.

**Comment by kprovance** [comment]
ya, in now

**Comment by kprovance** [comment]
As I suspected, it's his code.

**Comment by streamworksaudio** [comment]
Not surprised.  Is it something simple I can fix on my own.  Not sure if he/she will get to it.

**Comment by kprovance** [comment]
Unfortunately, it's all CSS based and not very simple.  I'm contacting him now.  He needs to pay me for my time since it's his issue to fix.

**Comment by streamworksaudio** [comment]
Thanks again Kevin - it is much appreciated.    

Curious to know what the issue is.  Is it in one of his scripts (in the plugin or theme)?

**Comment by kprovance** [comment]
CSS conflict regarding icon render.

**Comment by kprovance** [comment]
Don't share that, I want to this to pony up.

**Comment by streamworksaudio** [comment]
gotcha - thanks again

**Comment by streamworksaudio** [comment]
If you can let me know when you are done so I can bring the site back to live that would be great.

**Comment by kprovance** [comment]
I tried to email you again (coz I don't want to spam links to his theme here).  Got bounced again.  THis is what came back (I x'ed out your name for security reasons)

Delivery to the following recipient failed permanently:

     xxx@streamworksaudio.com

Technical details of permanent failure: 
Google tried to deliver your message, but it was rejected by the server for the recipient domain streamworksaudio.com by mx1.emailsrvr.com. [98.129.185.131].

The error that the other server returned was:
550 5.7.1 <xxx@streamworksaudio.com>: Relay access denied.

Anyways, I left him a comment.  It's up to him to fix it now.  Shoot me an email from another address if need be, something else I want to ask, but not here.
