### ISSUE TITLE
Translate the contents of sample-config.php file

### ISSUE THREAD

**Issue by waqasriaz** [reduxframework/redux-framework#3098]
Hi,
I am facing hard time to translate sample-config.php. any help ?

**Comment by kprovance** [comment]
You have to replace the text domain, I think it's 'redux-framework-demo' with the text domain for your theme/plugin.

**Comment by waqasriaz** [comment]
Hi, 
1. I added theme text domain, check this screenshot https://monosnap.com/file/s3jHnKJBJO4cYJAyzzWYGbDPMqBJnn

2. I include this file in functions.php 
3. Translated string in theme /languages/fr_FR.po but not working

**Comment by kprovance** [comment]
Thing is, this isn't a Redux issue, at all.  We're not PHP tutors or theme author advisors (unless you want to pay us to be).

**Comment by waqasriaz** [comment]
sample-config.php is not part of Redux ? 
How much it will cost me to fix it ?

**Comment by kprovance** [comment]
It's a sample file that demonstrates how option are used for Redux.  It's not part of the Redux core.  Once you include it in your theme with your specific options, it becomes part of your theme.  Redux itself does not handle any translation for options arrays as those array are, again, theme specific.   The problem is probably in the way the translation API is called or handled.  But that's is part of your theme - completely unrelated to Redux.  Like I said, PHP, WordPress dev and theme/plugin dev is not something we offer.  I get paid $100.00 an hour for services such as this, but I do it outside of Redux, as a contractor.

**Comment by waqasriaz** [comment]
How many hours you need to fix this ?
Theme other translation working, only problem with theme options.

**Comment by kprovance** [comment]
One at minumim.  You might want to check and make sure the translations are even in the po file, and that that the options php is loaded after the textdomain call.  Even so, I'm pretty sure load_theme_textdomain uses MO files.   https://codex.wordpress.org/Function_Reference/load_theme_textdomain

**Comment by waqasriaz** [comment]
ok i try, if not work then i will make deal with you to fix it
