### ISSUE TITLE
Select2 suddenly error

### ISSUE THREAD

**Issue by oknoorap** [reduxframework/redux-framework#3108]
I've found same question here, but it's not my solutions
[https://github.com/reduxframework/redux-framework/issues/3026](https://github.com/reduxframework/redux-framework/issues/3026)

When I select typography font-family field, it has no ending spinner
![Spinner](http://image.prntscr.com/image/777a0fdaae2447e499edb9bfd37bb5b1.png)

When I check devtools, it has error log
![Error Select2](http://image.prntscr.com/image/9559141c23234f819f1947ff2a4d5f20.png)

This is my redux config for google fonts
```php
/* Google API Key */
'google_api_key'		=> 'MY_API_KEY_HERE',
'google_update_weekly'	=> true,
'async_typography'		=> true,
```

**Comment by kprovance** [comment]
Actually, the same solution does apply.  I would download the redux master file from this repo, grab the googlefonts.php and upload it into the typography field folder.  Then disable the weekly update option until you can sort out your server permission issues, because it's going to keep nuking that file and cause this issue.

**Comment by oknoorap** [comment]
okay it's done, google fonts api key is not valid. I don't know if google upgrading their system, but I must re enable google fonts api. Thanks.
