### ISSUE TITLE
admin notice in debug mode

### ISSUE THREAD

**Issue by No3x** [reduxframework/redux-framework#3121]
I'm developer using redux in embedded mode in a plugin.
I'm not able to disable the admin notices when WP_DEBUG is defined:
![bildschirmfoto 2016-09-15 um 17 01 39](https://cloud.githubusercontent.com/assets/2690708/18554918/235af054-7b66-11e6-97e6-c2626cf75a45.png)

Is this intended or is there a way to control this behaviour?
Afaik this [doc](https://docs.reduxframework.com/core/the-basics/removing-demo-mode-and-notices/) doesn't help as it's not for the embedded version of redux.
[There are users complaining about this messages](https://wordpress.org/support/topic/nice-plugin-but-the-redux-splash-page-is-confusing/) and I hate them too.
(The splash screen issue was resolved with an update of redux btw)

[My support url ](http://support.redux.io/?id=K64q4pjPp3j15hZAJ052nMY1S8TDptIPDBwXFMUqGzBh0lPA5A2%2FqiuHmkWiESPrsjN18zdwwmRFdAoNxVVE0A%3D%3D)

**Comment by kprovance** [comment]
You could click the little X in the corner?  That would close it.  Sorry you hate it, but since users of our framework absolutely refuse to give back anything to our project, we have to comer up with ways to advertise our services and extensions.  It's the only way to keep this project going.  Notices and ads will appear when WP_DEBUG is enabled.

**Comment by No3x** [comment]
> You could click the little X in the corner?

That's not the solution.

> Notices and ads will appear when WP_DEBUG is enabled.

That's all I wanted to know. Thanks!
