### ISSUE TITLE
Themeforest review not passed

### ISSUE THREAD

**Issue by antoniomangiacapra** [reduxframework/redux-framework#3133]
Hi,

I would ask you sorry in advance because I guess it's pretty boring keep track about every ThemeForest policy.

I know you have [this guide](https://docs.reduxframework.com/core/theme-check/) about themeforest review, but seems that it's not longer enough. My reviwer has invited me to solve also some other issue (suggested by Theme Checker) and also when I explained that they are related Redux, he told that I have to change redux source or I have to use it as a third part plugin rather than embeded.

This is my situation:

WordPress: 4.5.4
Redux: 3.6.0.10
dev_mode: false
WP_DEBUG: true
Tracking: http://support.redux.io/?id=v1%2FIZDCUudyiwSIOIwT7GYMrr8AONgqM3aLDMA9BXhe66OsmoxxpIU4e2ZBYRtaNA5BHHv0bk4tTSb%2BLIM46%2Bg%3D%3D

The errors are:
`
- WARNING: The theme uses the add_shortcode() function. Custom post-content shortcodes are plugin-territory functionality.

- WARNING: Found wp_deregister_script in admin/core/ReduxCore/framework.php. Themes must not deregister core scripts.
Line 565: wp_deregister_script( 'wpb_ace' );

- WARNING: Found wp_deregister_script in admin/core/ReduxCore/core/enqueue.php. Themes must not deregister core scripts.
Line 215: wp_deregister_script( 'jquerySelect2' );

- REQUIRED: You are not allowed to hide the admin bar.

- REQUIRED It appears that you have embedded the full Redux package inside your theme. You need only embed the ReduxCore folder. Embedding anything else will get your rejected from theme submission. Suspected Redux package file(s):
Redux Plugin File: /xxxxxxxxxxxxxxxxxxxn/wp-content/themes/xxxxx/admin/core/class.redux-plugin.php`

I would like to receive some suggestions in order to be approved.

Thank you in advance.

**Comment by kprovance** [comment]
You made it sound like on Slack you were getting errors FROM Redux.  Explain 2 and 3 to the reviewer if they ding you for this again, or, as I suggested, use TGM to install Redux as a plugin, get the benefits of updates, and bypass all of TF's silliness.

1) Redux does not use add_shortcode().  It's got to be in your theme someplace.
2) wp_deregister_script( 'wpb_ace' ) is inside a conditional statement because visual composer uses (or did) an outdated version of ace_editor that was conflicting with Redux.  It's not an outright deregister.
3) Same for the select2, it's inside a condition statement because another popular plugin was forcing their version on users, and causes Redux to fail.
3) Redux does not hide the admin bar
4) Self explanatory?
