### ISSUE TITLE
Select2 Cdn link not working with https

### ISSUE THREAD

**Issue by waseemjutt** [reduxframework/redux-framework#3157]
Select2 cdn link not wokring with https 
only working with http
'//cdn.jsdelivr.net/select2/3.5.2/select2' . $this->min . '.js',
i replace with https with new cdn and then this is working i think this is bug in redux 
https://cdnjs.cloudflare.com/ajax/libs/select2/3.5.2/select2.js

**Comment by kprovance** [comment]
Are you working on a local environment or using some plugin that 'fixes' relative URLs (Ive seen a few destroy protocol relative URLs due to bad coding.?  The protocol relative URL is the preferred way to retrieve assets.

**Comment by waseemjutt** [comment]
No it's was live client site

**Comment by kprovance** [comment]
If you put the code back the way we wrote it, then open the dev console, and look at the HTML, see what URL was outputting.  Copy and past it back.

**Comment by waseemjutt** [comment]
Strange 2 days ago client come with this issue and i replace with new https select2 cdn then select2 is working  but today when i replace with old code '//cdn.jsdelivr.net/select2/3.5.2/select2' . $this->min . '.js', this is also  working

**Comment by kprovance** [comment]
Well, I'm glad it's working again.  if the issue comes up again, post a new issue (and please note the requirement in the preformatted text next time, that's important), plus whatever the output is in the HTML for that select2 URL.  This isn't much else I can do without knowing what the output that was failing was.
