### ISSUE TITLE
Redux frame slow when I login admin

### ISSUE THREAD

**Issue by cuongpx** [reduxframework/redux-framework#3208]
![vfpture](https://cloud.githubusercontent.com/assets/12441415/21797811/c15ddd28-d743-11e6-9b97-c52db64c218d.PNG)

I received such notification settings for the entire website Redux framework, and it makes my wesite running very slow and resource intensive

**Comment by kprovance** [comment]
Please go back to the new issue window, this time, read the text provided and supply us with the information we requests, otherwise we won't be able to assist you.

**Comment by cuongpx** [comment]
Its run very slow,which I'm disable its run fast.

hepl me?

**Comment by cuongpx** [comment]
It wastes resources of VPS ram.

**Comment by Basilakis** [comment]
@cuongpx Please take a look here
https://github.com/ReduxFramework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment]
It's all posted right there in the new issue window.  Most people ignore it, somehow thinking they don't have to pay attention to it.  It's actually here: https://github.com/reduxframework/redux-framework/blob/master/ISSUE_TEMPLATE

**Comment by cuongpx** [comment]
I do not understand why when active plugin admin Redux framework is not working **Maximum execution time of 120 seconds exceeded in**
I disable it when the admin function normally.

**Comment by kprovance** [comment]
Okay, for the last time:  I have asked you for the required information.  You will not provide it.  I cannot help you.  I do not have a crystal ball that allows me to see into your server.  Even so, Redux is used by tens of thousand of developers and hundreds of thousands of users.  If it were a Redux issue, this tracker would be flooded with issues.  Something is going on with your server config or PHP config that is causing a timeout, hence the delay.  I can;t diagnose that for you without a subscription to premium support.  It's ot something I will do pro bono, that is, go onto your server and figure out what is wrong, because it's not Redux.  cURL is timing out.  You have to determine why.

**Comment by cuongpx** [comment]
ok i will check them
