### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by khaledMohammed000** [reduxframework/redux-framework#3213]
We are using redux in our plugin and whenever we use it with other redux themes , we get two kinds of issues
1. our settings page vanish, when we activate any theme using the redux framework.. I have found that framework.php is the culprit file causing this isssue ( in this case we already have plugin installed and now are activating the theme )
Theme URL :  https://wordpress.org/themes/engrave-lite/

2. when we have a theme based on redux and then install our plugin , we get fatal errors ( in this case we already have theme installed and now are activating the plugin )
(We still dont know which theme causes this issue , since our users keep on reporting it and dont respond back)

I would really appreciate if you help our Opensource project by answering this query 👍 

Plugin : https://github.com/ahmedkaludi/accelerated-mobile-pages

**Comment by khaledMohammed000** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/399
Issue 1 solved

**Comment by kprovance** [comment]
You didn't supply any of the information we asked for.  When you opened a new issue, there was text already in the window.  You need to read that.

**Comment by kprovance** [comment]
Okay, I took a quick look at this, and there are a few issues that do not fall under the scope of free support.  This tracked is for bugs, not debugging.  That's a premium offering.

1) Engrave is using a modified version of the Redux core, and is slightly outdated.  If there are issues with that theme and their modified core, you have to take it up with the author who made those modifications.  Or they have to pay us to do so.

2) You have PHP error issues of your own in your plugin, which I'm not even going to try to get around.

3) I looks at your option config, and I see where it's causing some index errors for the type argument within Redux.  It's because one of your fields is missing the type argument.  You gotta fix that one.

That's the best I can do.  If Engrave is fatally erroring out, it's probably because they've done something wrong.
