### ISSUE TITLE
BUG REPORT wp-content moved, redux fell down

### ISSUE THREAD

**Issue by Remi007** [reduxframework/redux-framework#3216]
## Support Hash: 
http://support.redux.io/?id=iu%2BIfGcpp3zmAq7hZEX9pYTUVwi%2BC4zjVunVtXmBXzuBnN8T7LxOC5R61%2BpdRQ5BuuiBmpXBd8Y2eG9hfXiJ1w%3D%3D

## Steps to reproduce: 
- **move wp-content outside wordpress folder and change name**
f.ex. 
before: ../www/wp-content
after moved: 
- wp-content is here:  ../www/content 
- and wordpress here : ../www/blog

I moved  website to another folder with follow this documentation: 
https://codex.wordpress.org/Moving_WordPress#If_You_Have_Accidentally_Changed_your_WordPress_Site_URL

## Expected Behavior
website  and all plugins are working properly
## Actual Behavior
website  and plugins WITHOUT REDUX are working properly
## Any Error Details (PHP/JavaScript)
,

i have been moved folders wordpress and change place and name for wp-content:
original: 
home:: my.site.com , 
siteurl: my.site.com
folders: www/, www/wp-content
new: 
home: my.site.com 
siteurl:  my.site.com /new_wordpress
folder: ..www/new_wordpress/, ..www/new_content_for_wp
ABSPATH: /home/server/5/site/www/new_wordpress/
wp-config.php:

```
define('WP_HOME','http://' . $_SERVER['HTTP_HOST']);
define('WP_SITEURL','http://' . $_SERVER['HTTP_HOST'] .'/new_wordpress');
define('WP_CONTENT_DIR', $_SERVER['DOCUMENT_ROOT'].'/new_content_for_wp');
define('WP_CONTENT_URL', 'http://my.site.com/new_content_for_wp');

```
and .htaccess in ..www/

```
<IfModule mod_rewrite.c>
RewriteEngine on
RewriteCond %{HTTP_HOST} ^my.site.com$
RewriteCond %{REQUEST_URI} !^/new_wordpress/
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /new_wordpress/$1
RewriteCond %{HTTP_HOST} ^my.site.com$
RewriteRule ^(/)?$ new_wordpress/index.php [L] 
</IfModule>
```

and everything works fine except for michigan theme (backend settings and import demo) / Redux Framework

ERROR 1. Appearance/Customise dosn't work properly - I can NOT save configuration changes (inactive button save and other) and shows errors 404:

**for examples 404 errors:**

http://my.site.com/new_wordpress/home/server/5/site/www/new_content_for_wp/themes/michigan/inc/theme-options/ReduxCore/inc/extensions/customizer/extension_customizer.css?ver=1484512073

http://my.site.com/new_wordpress/home/server/5/site/www/new_content_for_wp/themes/michigan/inc/theme-options/extensions/wbc_importer/wbc_importer/field_wbc_importer.min.js?ver=1484512073

http://my.site.com/new_wordpress/home/server/5/site/www/new_content_for_wp/themes/michigan/inc/theme-options/ReduxCore/inc/extensions/customizer/extension_customizer.css?ver=1484512073

http://my.site.com/new_wordpress/wp-admin/customize.php?return=%2Fnew_wordpress%2Fwp-admin%2Ftools.php%3Fpage%3Dredux-status

ERROR 2. Appearance/Theme Options/Demo Importer (dont show images for demo )

regards
Remi

**Comment by kprovance** [comment]
You're a theme user, and not the theme author?

**Comment by Remi007** [comment]
i am only theme user, and the theme author is webnus  (theme: Michigan, http://webnus.biz/themes/michigan/kids/). But the author can  not help me in this case, because this is out of support rules.

**Comment by kprovance** [comment]
Well, being a theme forest theme author, I can tell you that's iffy.  He should be the one doing the legwork to determine where the problem is, if it's his theme, his embedded version of Redux, or your configuration.  You paid him for his work and for support (for example, that importer extension is his, we won't even touch that).  He's also chose to embed Redux and it's outdated.  I have no idea if he's made any modifications to our core.  This is not something I can duplicate on my end, especially with those variables in play.  If you've chosen to modify your wordpress and his theme breaks, it is his responsibility to support it.  We don't like to be put in the middle of theme authors and users.  if a user has an issue with the theme, they report it to the theme author, and if they are doing their job, they go onto your server, find the issue, and if it's with redux, THEY comes to us with the details.  That what he got paid for.  if I spend a day on this, I'm not getting paid for it, and I'm doing someone elses job, and that's why we don't get in the middle anymore.  Even so, he'd still have to update Redux, otherwise the issue will come back if he does not.

Since there is no way for me to reproduce this on my end, I'd have to go onto your server and try to find the issue, and that's a premium service that starts at $100.00 an hour.  But again, if it's Redux and not the way you've reconfigured your site, he still has to upgrade Redux, and it doesn't look like he has in quite some time.  Plus, he still has to fix his importer.

**Comment by Remi007** [comment]
Thank you for your answer. I completely understand your position and I fully agree with what you write. I will continue the dialogue with the author. We will see. But there is one thing more... I just finished testing a different theme from different author PIXELEMU pixelemu.com , theme PE SCHOOL v. 1.0.2 with Redux Framework v. 3.6.3.... and i see also error (but different) 

> Fatal error: Call to undefined function get_home_path() in /home/100/server/domain_name/www/content/themes/pe-school/inc/less.php on line 133

if I disable the redux framework plugin, the website works without error 
I sent Q to next author :)

**Comment by kprovance** [comment]
That error has nothing to do with Redux.  Again, issues with themes go to the theme author.
