### ISSUE TITLE
Redux Framework

### ISSUE THREAD

**Issue by JaDesignz** [reduxframework/redux-framework#3224]
[Redux Framework.pdf](https://github.com/reduxframework/redux-framework/files/737171/Redux.Framework.pdf)

**Comment by JaDesignz** [comment]
I having a problem with the Redux Framework, whenever I activate the plugin the “add to cart” button disappears from the product page, how this problem can be solve? 
If you need me to send you the username and password so that you can take a look at the website I can do so…….PLEASE I REALLY DO NEED YOUR HELP…ASAP. THANKS

**Comment by kprovance** [comment]
You'll hae to do some more research on this as to why you believe it'ss Redux, especially since you provided no support hash/url.  Check the CSS in the element browser and see if it's hidden.  Also, we do not go onto the sites of other people to debug their issues unless you purchase premium support.

Also, please upgrade to the version of Redux from this repo and see if the problem still persists.

After that, please provide the support hash/url.  Instructions for doing so were in the new issue window.

**Comment by kprovance** [comment]
No follow up reply with requested information.  Closing.
