### ISSUE TITLE
Site Loads Too Slow When Using Redux Framework Version 3.6.3

### ISSUE THREAD

**Issue by osocoach** [reduxframework/redux-framework#3230]
Hi there! I have a theme that uses Redux, and I found that when activated, my site is taking more than 30 seconds to load, and without it just between 3 and 5 seconds. 

I just read another post from 2014 with the same problem. I've try everything that was suggested there but still have the problem. 

Is there anything i can do in this new version in order to have better loading times?

Thanks

**Comment by kprovance** [comment]
Per the text in the new issue window, which I guess you didn't read, we do not support theme users.  You need to take this issue up with the theme author and allow them to debug your situtation.  That's what you paid them for, support.  If the developer determines it's a Redux issue (probably because they are using an old outdated or modified version), then they need to come to us.  Sorry.

**Comment by dovy** [comment]
Most speed issues are how the developers implement Redux, not Redux itself. Best of luck!

**Comment by osocoach** [comment]
@kprovance I read the ALL PREVIOS TEXT, and it says that if i don't have a response of the support team, i needed to read another useless text. So, It would be nice to know if you know something about the widget that you developed that can help me with my problem, since my problem is not the theme is the widget. Is not and old or modified version, because I downloaded from your site yesterday. But thanks anyway

@dovy Thanks for the response, i'll try to find a solution.

**Comment by dovy** [comment]
@osocoach No need to be rude to @kprovance. If you don't understand the support URL that's because you're not the actual developer. Basically it's outside of our scope because we're unsure how your developer implemented it.

I am sorry you're so frustrated, but @kprovance is probably not the person you should be upset at. We built the tool, we didn't implement it. Best of luck to you!

**Comment by osocoach** [comment]
He is being rude inferring and securing things about someone. What you give is what you get, and he only received what he gave me.

**Comment by dovy** [comment]
@osocoach sorry it came off as that. When people come in saying "it's all your fault" and it's 99% not, it can get tiring. Either way, I hope they fix your issue. Best of luck.
