### ISSUE TITLE
Manually trigger compiler

### ISSUE THREAD

**Issue by andrejarh** [reduxframework/redux-framework#3236]
Hi
What would be the best way to manually trigger compiler action. 
Currently i run it on "Save" with
`add_filter('redux/options/.../compiler', 'compiler_action', 10, 3);`
as in docs...

I am preparing an update which requires me to trigger it manually somehow.

Thanks

**Comment by kprovance** [comment]
Not easily.  You could use apply_filter on that filter tag, but not only would Redux have to be loaded, but you'd have to feed in all the parameters, including the entire options array, the compiler css array and that changed values array.  Otherwise your compiler code will have no data to work with and would be output incorrectly.
