### ISSUE TITLE
Sorter field with data parameter modify array key after save

### ISSUE THREAD

**Issue by rafaelfndev** [reduxframework/redux-framework#3239]
This is my code of sorter:

```
array(
    'id'        => 'pages',
    'type'      => 'sorter',
    'title'     => 'Site Pages',
    'data'	=> array('pages'),
    'options'   => array(
        'enable'   => array(),
    ),
),
```

Before click on save button the ID works correctly and show real page-id:
```
[pages] => Array
        (
            [enable] => Array
                (
                )

            [0] => Array
                (
                    [44] => Page Test 1 // I need keep this keys (keys of pages 44, 48...)
                    [48] => Page Test 2
                    [34] => Page Test 3
                    [51] => Page Test 4
                    [32] => Page Test 5
                )

        )
```
After click on save button the key are changed to title slug (title of sorter, not page) or something else:

```
[pages] => Array
        (
            [enable] => Array
                (
                    [placebo] => placebo
                )

            [0] => Array
                (
                    [placebo] => placebo
                    [page-test-1] => Page Test 1
                    [page-test-2] => Page Test 2
                    [page-test-3] => Page Test 3
                    [page-test-4] => Page Test 4
                    [page-test-5] => Page Test 5
                )

        )
```

Is possible to keep ID of pages on key? or get more parameters like page-slug, etc?

**Comment by kprovance** [comment]
What you missed in the new issue window.  Please review and supply the required information.

Hello, and welcome to Redux Framework!

Are you a user reporting a bug with a theme or plugin?
======================================================
Redux is a tool for developers to include an options panel in their project. Consequently, we do not offer support for folks who have purchased a theme or plugin that uses Redux. The responsibility of support for themes and plugins falls upon it's author. We realize that some authors have included support links for Redux in their projects, when they should not have. We do apologize for that confusion and are taking steps to remedy this confusion. 

If you have purchased a theme or plugin that utilizes Redux, please contact the author for support. If the author is unavailable for support or has discontinued support, please refer to this before posting to our issue tracker: https://docs.reduxframework.com/core/support-defined/
	
Have a development usage question?
==================================
The issue tracker isn't the best place for usage questions. This format is not well-suited for Q&A, and questions here don't have as much visibility as they do elsewhere. Before you ask a question, here are some resources to get help first:

- Try Redux: https://demo.reduxframework.com/
- Read the docs: https://docs.reduxframework.com/
- Look for/ask questions on StackOverflow: https://stackoverflow.com/questions/tagged/redux-framework
- Ask in our community Slack channel: http://slack.redux.io/
- For Premium support or advanced customizations we offer premium support. See https://reduxframework.com/extension/premium-support/ for more information.

Questions about a Redux extension?
==================================
All pre-sale and support for premium extensions need to be posted to the Redux Extensions Issue Tracker. Please do not post them to this issue tracker. https://github.com/reduxframework/redux-extensions/

Think you found a bug?
======================
Please use the "BUG REPORT" template below. Remember, we are rabbid about backwards compatability. Do not submit fixes that break previous ways of doing so or they will be rejected.

**Also, unless you provide a Support Hash, your request will also be rejected.** See https://docs.reduxframework.com/core/generating-a-support-hash/ for more details.

You MUST be using Redux in dev mode when submitting an issue to us. If you are not, or have circumvented our dev mode protocol, you are on your own. There could be information in your issue that requires dev move active. (Compressed Javascript, for example. We are unable to diagnose issues with compressed Javascript and why dev mode needs to be enabled.)

If an error or notice appears on your screen, please cut and paste it into your issue. PLEASE, do not say you 'got an error' without telling us what the error or notice is.

Before you post, check the JavaScript!
======================================
Sometimes, an issue may be tied to JavaScript. To make this determination, you will need to check the JavaScript console. To do this, ensure your web browser is the topmost window. On your keyboard, press CTRL+SHIFT+I. The JavaScript console will open. If there are notices or errors there, please cut and paste them into your issue. We would prefer a cut and paste, since it will include all pertinent information. Also, Redux dev mode must be enabled so an accurate line number may be reported.


## Support Hash

## Steps to reproduce

## Expected Behavior

## Actual Behavior

## Any Error Details (PHP/JavaScript)

**Comment by rafaelfndev** [comment]
Before click on save button the ID works correctly and show real page-id, but after I click on save button the key are changed to title slug (title of sorter, not page) or something else...

**Are you a user reporting a bug with a theme or plugin?**
Plugin, I'm using redux build to make a theme with required plugin

## Support Hash
Redux Framework v3.6.3 (generated with redux build) and updated plugin trought WordPress panel (from latest version of WordPress repository)

## Steps to reproduce
Create a filed sorter with data 'pages':

```
array(
    'id'        => 'pages',
    'type'      => 'sorter',
    'title'     => 'Site Pages',
    'data'	=> array('pages'),
    'options'   => array(
        'enable'   => array(),
    ),
),
```

## Expected Behavior
Keep ID of array keys, but keys are changed (44 > page-test-1...), I need keep the same ID that I had before I clicked on save.
```
[pages] => Array
        (
            [enable] => Array
                (
                )

            [0] => Array
                (
                    [44] => Page Test 1 // I need keep this keys (keys of pages 44, 48...)
                    [48] => Page Test 2
                    [34] => Page Test 3
                    [51] => Page Test 4
                    [32] => Page Test 5
                )

        )
```

## Actual Behavior
After click on save button the key are changed to title slug (title of sorter, not page) or something else:
```
[pages] => Array
        (
            [enable] => Array
                (
                    [placebo] => placebo
                )

            [0] => Array
                (
                    [placebo] => placebo
                    [page-test-1] => Page Test 1
                    [page-test-2] => Page Test 2
                    [page-test-3] => Page Test 3
                    [page-test-4] => Page Test 4
                    [page-test-5] => Page Test 5
                )

        )
```

## Any Error Details (PHP/JavaScript)
Console does't show any errors, and dont have any error of php (developer mode is enabled).

**Comment by kprovance** [comment]
Still need the support hash/url, please.

**Comment by rafaelfndev** [comment]
> Still need the support hash/url, please.

How I can get this? Do you need to URL of my site with the problem? Sorry, I really did not understand what you need when you say "hash/url"...

**Comment by kprovance** [comment]
It's in the test I provided for you above.

<blockquote>
Also, unless you provide a Support Hash, your request will also be rejected. See https://docs.reduxframework.com/core/generating-a-support-hash/ for more details.
</blockquote>

**Comment by rafaelfndev** [comment]
I run my site on localhost, have some problem? if not, thats it:

http://support.redux.io/?id=13YtK8q%2F5xvOC8V6%2FAAlfyCALuBX0rUdtEbblCWZZbAHfc1Baz%2FnHWLSmr2vC%2BSeGgB6YgPs2hRHyOz6md4LKQ%3D%3D

**Comment by kprovance** [comment]
The page IDs should not be coming up at all.  That's a bug I will have to work on.  The reason was had to force page titles on save was due to the sorter not sorting properly because array keys with the page IDs were not sorting properly, and it became a mess.

How can however take the page title and get the ID this way:  https://codex.wordpress.org/Function_Reference/get_page_by_title
