### ISSUE TITLE
Feature Suggestion: Auto-Export Options

### ISSUE THREAD

**Issue by tylonius** [reduxframework/redux-framework#3262]
I use Redux as part of Dynamic Frameworks' Ronneby WP theme for a number of sites. 

On more than one occasion, I have lost of all of my Theme Settings, due to some database connection interruption. While I am usually able to recover the custom CSS, the other settings all revert to their defaults, and I have to go through and restore them.

As a result, I've gotten into a habit of exporting the settings before and after I save them, so that if something goes wrong, I have something to fall back on.

Why not make that an automated process, at the end of the Save Settings script? You could easily output the JSON code to a physical file before executing the various SQL queries. That way, if there is some database connection issue, developers have an easily executable fallback.

Just a suggestion.

Thanks,

ty

**Comment by dovy** [comment]
This wouldn't be too difficult to do, we have a save action hook. Just add your own functions and write out a file. Honestly, however, your issue is quite rare and I've never heard of this kind of problem. Sounds like you need a better DB server.

We probably wouldn't integrate this into the core because how would we verify that the file writing works? Also file writing in WordPress is often flakey due to WP installs being installed incorrectly. I fear it would cause more problems than fix things.

Best of luck!
