### ISSUE TITLE
Typography field's cached font list

### ISSUE THREAD

**Issue by ksere** [reduxframework/redux-framework#3267]
Hi Guys,

On a theme i am developing, the default font-family value is set to a font on which google has introduced a change (different font weights and variants included), some time after the [googlefonts.php](https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/inc/fields/typography/googlefonts.php) (version included in WP.org release) was generated. 

Redux is installed and activated using TGM. 
The 'freshness' check routine in [field_typography.php](https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/inc/fields/typography/field_typography.php#L944) reports the file is fresh new as it has the date of the installation, so the sooner it will be updated will be in a week. For that time the theme has styles for a missing font weight.

Could googlefonts.php not be included in the official release, as it is re-created automatically every time it is missing?

**Comment by kprovance** [comment]
I did I update it, last release.

**Comment by kprovance** [comment]
Okay, I think what happened is Dovy went ahead and pushed a new version of Redux to wp.org before I could commit and push all my fixes and changes to the git (and there were quite a few).  So, the 3.6.4.1 version in this repo now contains the updated google fonts cache.  Sorry about this.  Between his super busy life and my self imposed seclusion, communication broke down a little.

**Comment by ksere** [comment]
Hi Kevin,

Thanks for looking into this.

But, unless i am missing something, regardless if the included file is up to date at the time the release is pushed to wp.org, that file, if included in the wp.org plugin, will cause that 1 week delay for any subsequent font changes to show up in a user's panel.

**Comment by kprovance** [comment]
I guess you are using the plugin and not embedding?  I'm not sure about the delay..  I don;t know how long it will take Dovy to update the wp.org plugin to the version in our git.  The only alternative is to pack the version of from this repo into your project and use TGM to install.  Since the version number is higher, it should replace the older wp.org version.

Or, you could get a Google API key and turn on the weekly update in Redux itself (oh, the weekly update, I get it now.  Yeah, that's how Redux was coded, for a weekly check based on the googlefont.php filetime).  Problem with that is, not all servers and wp installs are created equal, and there could be write issues that crop up for your users (which is why we stopped documenting that feature, but left it for legacy reasons).  Too many people were experiencing write problem on wp installs that were not properly set for write permissions, and then complaining to us, when it was never our issue.

**Comment by ksere** [comment]
Yeah, using the plugin from the WP repo through TGM.

You are right, in case a server has write issues if the cached fonts are
missing, it will break things. Better left as is.



On Mar 27, 2017 10:47, "Kevin Provance" <notifications@github.com> wrote:

I guess you are using the plugin and not embedding? I'm not sure about the
delay.. I don;t know how long it will take Dovy to update the wp.org plugin
to the version in our git. The only alternative is to pack the version of
from this repo into your project and use TGM to install. Since the version
number is higher, it should replace the older wp.org version.

Or, you could get a Google API key and turn on the weekly update in Redux
itself (oh, the weekly update, I get it now. Yeah, that's how Redux was
coded, for a weekly check based on the googlefont.php filetime). Problem
with that is, not all servers and wp installs are created equal, and there
could be write issues that crop up for your users (which is why we stopped
documenting that feature, but left it for legacy reasons). Too many people
were experiencing write problem on wp installs that were not properly set
for write permissions, and then complaining to us, when it was never our
issue.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/reduxframework/redux-framework/issues/3267#issuecomment-289330395>,
or mute the thread
