### ISSUE TITLE
Destination folder already exists

### ISSUE THREAD

**Issue by mobileescaperoomla** [reduxframework/redux-framework#3268]

**Comment by mobileescaperoomla** [comment]
I'm trying to install Redux Framework and I keep getting an error saying the destination folder already exists. Not sure where to start.

**Comment by mobileescaperoomla** [comment]
kprovance, I'm trying to install Redux Framework and I keep getting an error saying the destination folder already exists. Not sure where to start.

**Comment by dovy** [comment]
@mobileescaperoomla  That sounds like a permissions issue. Perhaps Redux was installed in another way.

Could you actually print the FULL error instead of just a portion? Makes it really hard to debug when all we know is there's an error. We'd love to see the crash location. IE, where in our code this error is being produced.

If it's not in our code, but in WordPress, then you need to delete redux-framework from ~/wp-content/plugins
