### ISSUE TITLE
WordPress media library not loading when redux framework is activaed

### ISSUE THREAD

**Issue by simrandeep** [reduxframework/redux-framework#3269]
One of my customers is facing an issue with redux framework. When redux framework is activated on his blog, the media library stops loading and shows only loader icons. When redux framework is deactivated, it starts loading again.

Customer is using Redux Framework v3.6.4 and WordPress v4.7.3. Console is not showing any error. I search over stackoverflow and Google but that didn't help. Is there any such know issue? Are there any minimum requirements for redux framework to run?

**Comment by kprovance** [comment]
No known issues.  A support url from the client is needed here.

**Comment by dovy** [comment]
I highly doubt this is an issue with Redux, but more of how Redux was implemented. Please switch the theme, turn off all other plugins, and run only redux with the sample config. 

More than likely someone tried to modify the menu location, and it's overriding the media location because another plugin is pushing it down.  ;)

**Comment by simrandeep** [comment]
I will try deactivating the other plugins. Only 2-3 other plugins were active at that time. Thanks for replying quickly :)
