### ISSUE TITLE
Error after change home url

### ISSUE THREAD

**Issue by teasantoro** [reduxframework/redux-framework#3275]
Hello, I changed the url home and I have some problems:
- Preview page error: Sorry, you are not allowed to preview drafts.
- Warning: fileperms (): stat failed for /web/htdocs/www.*****.it/home/new/index.php in /web/htdocs/www.*****.it/home/ new / wp-admin / includes / file.php on line 935

**Comment by kprovance** [comment]
Obviously you are having a theme issue?  Per the etx in the new issue window...the one you just skipped over, we are not the author of your theme.  You need to contact the theme author directly for support.

Good luck!

**Comment by teasantoro** [comment]
But if i deactive redux framework it's ok.

**Comment by kprovance** [comment]
It is still a theme author issue that they need to investigate.  You paid them for support, so it is their obligation to do the work to determine why, not ours.  If the author discovers a flaw with our framework, they need to come to us with the pertinent information, as we do not support users of themes that use our framework.  Sorry.  Good luck.

**Comment by dovy** [comment]
@teasantoro the main reason for this is theme developers can use our framework in a variety of complicated ways. We can't justify learning every theme that's produced when your developer knows what is going on so much better. You'll get better results if you go through them because they know what they wrote.

Thank you for your understanding.
