### ISSUE TITLE
easy way for remove this notice message?

### ISSUE THREAD

**Issue by vucumbra** [reduxframework/redux-framework#3289]
Hi how remove this notice
> The Ultimate Redux Extensions Bundle!
> Attention Redux Developers! Due to popular demand, we are extending the availability of the Ultimate Redux Extension Bundle, which includes all of our extensions at over 40% off! Grab you're copy today at https://reduxframework.com/extension/ultimate-bundle

**Comment by kprovance** [comment]
Close it by clicking the X.  Your end users will not see this message provided dev_mode is set to false (you see it, because you are the developer, and those are the folks we market to.  Since Redux is free, we must support the project on your extensions).

To disable permanently, you;d have to purchase and install our ad remover extension:  https://reduxframework.com/extension/ad-remover/
