### ISSUE TITLE
Live Search & Multiple Panels

### ISSUE THREAD

**Issue by ACODA-LTD** [reduxframework/redux-framework#3298]
Hey Guys, 

I just want to say, redux is a joy to use, I'm enjoying it immensely - keep up the great work!

**Live Search**
With regards to Live Search ( happily post it directly there if needed ), for some reason when I search, it shows the results + every section h2.

![screen shot 2017-05-02 at 12 21 55](https://cloud.githubusercontent.com/assets/4103430/25615946/f764a71c-2f31-11e7-8fdf-33d9556f4009.png)

**Multiple Panels**
I'm migrating my current theme options to your beautiful system. It's all going great, apart from one area. 

Currently I have a "Skin" system, that holds options like Header Color etc, however, there are multiple "Skins" that can be customized / added. 

The idea behind it is if you wanted to create a "Landing Page", which had different header, body, text colors, you can apply a different "Skin" to that page. 

I was hoping I could load options in dynamically, depending on which "Skin" was selected to be edited e.g.
 
`		
array(
				'id'        =>  'header_color_'. $skin,
				'type'      => 'color_rgba',
				'title'     => ' RGBA Color Picker',
				'subtitle'  => 'Set color and alpha channel',
				'desc'      => 'The caption of this button may be changed to whatever you like!',
				// See Notes below about these lines.
				//'output'    => array('background-color' => '.site-header'),
				//'compiler'  => array('color' => '.site-header, .site-footer', 'background-color' => '.nav-bar'),                      
			),`

**Note the ID.** However, that doesn't work. 

I'm considering using an admin panel for each "Skin", it will only load whichever "Skin" is selected to be edited. 

Would that be the best method, or is there some functionality I'm missing? 

Thanks,
Andy

**Comment by kprovance** [comment]
Hi.  Please post ALL extension issue to the extension issue tracker.  This is one is soley for the Redux core.  Thanks.

https://github.com/reduxframework/redux-extensions/issues

**Comment by ACODA-LTD** [comment]
Hi, 

No problem, what about the Multiple panels?

**Comment by ACODA-LTD** [comment]
@kprovance @dovy can you let me know your thoughts with regards Multiple Admin Panels vs a dynamic options method? Thank you :)

**Comment by kprovance** [comment]
No, dynamic IDs like that won't work.  I don't know what you mean by multi panels.  Do you mean the tabs in the option panel?  Or completely separate option panels (meaning a separate menu item for each panel in the admin menu itself).  That would be a lot of code and take up a lot of screen real estate.  You could have a select box of various skins and use required to show controls for the selected skin, but again, you'd have to have a control for each skin with a unique and non dynamic ID.  Redux has no inherent way to load/hide tabs in the option panel based on a select box choice.  It could be done, but you'd have to write your own javascript for such a thing to work using show/hide (removing html from the dom might cause save information to be lost, which is why the dynamic ID won't really work.
