### ISSUE TITLE
Update Google Font

### ISSUE THREAD

**Issue by Uranbold** [reduxframework/redux-framework#3306]
Hi guys.

Please update your Google Font Cache or function or something. Because Some fonts are added more styles and even new fonts added etc.

Thanks.

**Comment by kprovance** [comment]
They are updated with each new wp.org release.  Unfortunately, it's not something we do weekly, or monthly.  You can always get the git copy, which is usually current.

**Comment by Uranbold** [comment]
About the Montserrat font, There are few styles are added and it's not displayed on Latest version of Redux.

Example: Currenlty it shows only 400,700.

If you see current Montserrat on Google fonts there are more styles added -> https://fonts.google.com/specimen/Montserrat

So how do we achive this?

**Comment by kprovance** [comment]
You must be using an older version of Redux.  But since you didn't read the text in the new issue window that asked for the support URL/hash - which is required - there isn't much else I can tell you.  The version of Redux in our git shows Montserrate with 100,200,300,400,500,600, 700,800, 900, plus italic variants.  So...update?

**Comment by Uranbold** [comment]
I have created Pull Request and Updated new Array in Core Thanks!

**Comment by kprovance** [comment]
Not needed, I just said, it's done each release!  Thanks.  Locking.
