### ISSUE TITLE
Site slows down after changing theme options 

### ISSUE THREAD

**Issue by ay-uk** [reduxframework/redux-framework#3349]
Hi,

When we do a fresh install of WP and redux, the site is quick. However, after changing the theme options the site starts slowing down and CPU usage hits >90%. We realized the wp_options table grows in size every time we update the theme options. We are already using the latest version of Redux. Any ideas?

http://support.redux.io/?id=jeW9DncY7bjUWoKpc5%2FyUPqQ2%2F41VuO4LENTsg4B8CVmM0hdUp2M1BK%2BjM5bEgKipUvPLpmz%2BdqC13ZAiqiQ7g%3D%3D

**Comment by kprovance** [comment]
You may have to do a little homework here.  First, I am not seeing the same issue, even loading your config.  However, my PHP and WP memory settings are somewhat higher, being a developer  See if bumping up wp_mem_limit and php_post_max_size (especially) help.  Also, try disabling plugins one at a time and see if they interfere.  I wouldn't they they should (I wonder about the sweep one).  These are things we have to do to look for conflicts.

Finally, yoou say the database is growin exponentially?  To what degree?  You may need to go into myPHPAdmin (or whatever is comparable for your system), pull the serialized data (it's key will be that of your opt_name, and compare saves.  Since it's a serialized sting, this could be done with something like KDiff.  We would need to determine when the excess of data is coming from or if there is any duplication.

I also you see that you are using your own typography extension.  Was it coded properly overload the one in the core so that only yours is running?  Also, very important.

**Comment by kprovance** [comment]
There has been no reply for this ticket.  Closing.
