### ISSUE TITLE
How to add/replace fields in the slide section in metabox

### ISSUE THREAD

**Issue by hozyali** [reduxframework/redux-framework#3376]
Hi, is it possible to customize fields inside slides ? if yes, what would be the best approach?
I am using it in metabox extension.

I need a couple of more fields added in the slides field type. 

thanks

**Comment by kprovance** [comment]
You'd have to edit the actual field.  Since editing the Redux core is highly NOT recommended, your best bet would be to create an extension and add in the fields you want.

**Comment by hozyali** [comment]
Hi, I tried the custom_field boiler plate extension but no luck. Couldn't really understand without the docs. can you either provide me a link to actual docs to learn more on how to do it?
or can you give me some directions on how to create an extension (using boiler plate) to achieve the needed solution?
@dovy ?

Thanks

**Comment by kprovance** [comment]
This is a premium support service we offer.  There is this:  https://docs.reduxframework.com/extensions/using-extensions/

**Comment by hozyali** [comment]
That article tells me how to load extension which I did already and works fine. 

I am trying to find directions on where to start when I want to **CUSTOMIZE** the fields inside the **SLIDES** type fieldset.

If its a premium support, can you tell me if it is same that comes with premium extensions we buy? Since I purchased metabox extension recently, wanted to see if this is possible. 

Thank you for your help.

**Comment by kprovance** [comment]
It also tell you how to do your own:  The concept is simple. The folder, extension php filename, and extension class name, must all match.

Basically, copy the slides folder from with the Redux core fields folder and rename it to something else.  Use this boilerplate:  https://github.com/reduxframework/extension-boilerplate

Instead of 'custom field' you'd past in the slides folder from the core, but you MUST call it something else, likes, my_slides, whatever you want.  But per the instructions, the folder name and the class names must all match.  

So, you have the folder 'my_slides'.  Inside that you would have extension_my_slides.php.  You have to edit that file to change all the class names so they are suffixed with my_slides (plus change the field_name variable.  Inside the same folder, past in the slides folder form the core and rename it to 'my_slides'.  You will then have to edit every file so that all class names in the php files match 'my_slides'.  This includes all references to the 'slides' object in the javascript, or conflicts will occur.  it a process that depends upon having more than a basic knowledge of php and javascript.

Premium support, which is a fee paid to whomever would do the work is independent from any premium extension purchase.  Modifying the core slides field into an extension in which you can add or subtract fields from the slide field is separate from metaboxes.  It's a fair bit of work and not just a few minutes of changing some file names.  As I said, modifying the core slides field will ultimate backfire.  Any change you make would be lost when Redux is updated, and why we have the ability to write extensions...even if it's to take an existing field and modifying it.

As for adding new items to the slides field itself, you will have to code that up with html and php inside the 'fields_slides.php' and possibly javascript to clear fields of data when the slides remove event is fired and to handle objects that are not input text, hidden or textareas.  It will take a bit of work depending on what you are looking to add.

**Comment by hozyali** [comment]
Exactly that sort of directions I was looking for. Thanks a lot sir. 
Appreciate your help.
