### ISSUE TITLE
Conflict between WPBaker Visual Composer and Yoast SEO only with Redux Framework active

### ISSUE THREAD

**Issue by Samuelez99** [reduxframework/redux-framework#3381]
I'm not a developer, but I think that this report could be useful, because the bug seems to be related to Redux Framework (if I disable it, the issue disappears). The developer of the theme I'm using (MESH version 2.1.9) ignored us on this problem, and won't open a ticket in your issue tracker.

## Support Hash
http://support.redux.io/?id=Jp0lFCEZsK3FLK94yeKeJzgsQXz52EXSdY2lIULQ8h4%2BVorGljNVKtWm%2ByZ3hyTDREoKhBsO8COQzSxfj7qpFA%3D%3D

## Steps to reproduce
1. With Redux Framework active
2. Active both the Yoast SEO plugin and the WPBakery Visual Composer plugin.
3. Enter on the back-end of a page or a post, and click the button to enter the front-end editor of Visual Composer.
4. You won't see any of the elements the page should contain.

## Expected Behavior
This the expected behavior, the pic represents the situation with Yoast SEO disabled and Redux Framework enabled, or with Yoast SEO enabled and Redux Framework disabled: http://www.voicebookradio.com/it/wp-content/uploads/2017/07/screencapture-voicebookradio-it-wp-admin-post-php-1499864670595.png

## Actual Behavior
This the actual behavior, that I see if both Yoast SEO and Redux Framework are enabled: http://www.voicebookradio.com/it/wp-content/uploads/2017/07/screencapture-voicebookradio-it-wp-admin-post-php-1499864614275.png

## Any Error Details (PHP/JavaScript)
Inspected the page, these the errors:

`frontend-editor.min.js:9 Uncaught ReferenceError: vc_js is not defined`
    `at Object.vc.build (frontend-editor.min.js:9)`
    `at HTMLDocument.<anonymous> (page_editable.min.js:1)`
    `at i (jquery.js:2)`
    `at Object.fireWith [as resolveWith] (jquery.js:2)`
    `at Function.ready (jquery.js:2)`
    `at HTMLDocument.K (jquery.js:2)`

**Comment by kprovance** [comment]
This is will be almost impossible to even attempt to figure out without a copy of that theme...and then were getting into premium support territory, because that's a good bit of work and the theme author is not paying me to do his job.  So you know where I can find his theme, on ThemeForest I am assuming?  I'll start by taking this up with him.  The reason this is necessary is I have no idea how he incorporated VC and Redux into his theme, and going through theme code is outside the scope of what we support at Redux.  Part of the author's job it to debug his work when issues like this come up, and if it's determine it's our code, he hands us the specifics om why he thinks its Redux and we got from there.  You can send that information to me privately at kevin@reduxframework.com, as not to give him any free advertising here.

**Comment by kprovance** [comment]
I left a note on the authors comment page.  Hopefully he'll read it and get back to you, since it really is his responsibility to figure out what's wrong here.  I could do it, but I', 100 bucks an hour, and you shouldn't have to pay someone else because the author doesn't want to deal with it.  Alternatively, you can go to ThemeForest support and file a complaint there as well.  Let me know if he decides to do right by you, so I can close the ticket.  Thanks!

**Comment by Samuelez99** [comment]
I'll send you the email with the link on Themeforest anyway, because I didn't understand if you already found it.
I'll let you know if he decides to solve the problem directly with me. If I don't receive any email from him, I'll file a complaint on ThemeForest support.
Thank you very much!

**Comment by kprovance** [comment]
The theme author assured me he would handle this.  Closing ticket.
