### ISSUE TITLE
ATTN DEVS: REDUX BUILDER SITE IS DOWN, PLEASE READ....

### ISSUE THREAD

**Issue by kprovance** [reduxframework/redux-framework#3387]
Attention developers. Currently, the Redux builder site is down, in as far as attempting to generate an admin folder or theme will not work, or download improperly (zero byte) file.

We are aware of the issue. There is no ETA when it will be resolved.

It is not necessary to post about this issue.

If you would like to be notified when the builder is back up, subscribe to this post. When the builder is back up, I will post a reply here and you will receive a notice.

Thank you.

**Comment by tsktech** [comment]
"REDUX BUILDER SITE IS DOWN" and its down even on 26 April 2019.. ?? why keep the link when there is no ETA to fix it..

**Comment by dovy** [comment]
It will be up in a few days. I'm almost done with a complete rebuild.

**Comment by webmarcello8080** [comment]
Is there a way to install Redux manually or with composer in a Wordpress theme? the builder site is down to me.

**Comment by gulonline** [comment]
i also want Redux builder for wodpress theme generate. is there any way? because from past 1 yr redux builder site is under construction.

please suggest us

thanks

**Comment by dovy** [comment]
Hey all, so embedding in a theme/plugin is very easy. 

Take this directory: https://github.com/reduxframework/redux-framework/tree/master/ReduxCore
And put it in your theme or plugin.

You can give this a try, but it's very much in alpha: https://build.redux.io/alpha/dist/index.html
P.S. There's a missing settings icon on the right side of every row.

The builder was hard to maintain because of the other projects we used, TGM, etc. Hence why we haven't fixed it. We will eventually probably make it part of the Redux plugin.
