### ISSUE TITLE
http://support.redux.io/?id=rhYRsRx1USQVNmQD%2FYAgV24AeKUmH9UlFtCnSd9J5wj45LBXgbNABdaVTFWmU%2F0HDN5GRzo5GiKsuPyIxJl8qA%3D%3D

### ISSUE THREAD

**Issue by gaskobahi** [reduxframework/redux-framework#3427]

**Comment by kprovance** [comment]
You left out what exactly the issue is.  Required information.

**Comment by kprovance** [comment]
Well, since you didn't explain your issue, all I can do is look at your info via your hash, and I see three things that need to be fixed:

1) Upgrade you copy of Redux.  It's outdated.  You can do this from the wp.org plugin section.
2) Your 'max_upload_size' is set to 0B.  This value needs to be changed to at least 64MB in your php.ini
3) Your 'php_post_max_size' is also set to 0B.  This should be at least 64MB

If you do not know how to change PHP.INI settings, please contact whomever hosts your site and ask them to make the changes for you.

Otherwise, please open anew issue window, read the entire body of text, and post back all the information we require.  Thanks!
