### ISSUE TITLE
Can't save theme options

### ISSUE THREAD

**Issue by MarcoFerry** [reduxframework/redux-framework#3432]
Hey guys, 

whenever I try to save changes within my theme options the following error occurs: "There was a problem with your action. Please try again or reload the page."

Console shows following error:

"POST http://mypage.net/wp-admin/admin-ajax.php 500 (Internal Server Error)

send @ jquery.js?ver=1.12.4:4
ajax @ jquery.js?ver=1.12.4:4
a.redux.ajax_save @ redux.min.js?ver=3.6.5:1
(anonymous) @ redux.min.js?ver=3.6.5:1
dispatch @ jquery.js?ver=1.12.4:3
r.handle @ jquery.js?ver=1.12.4:3

There was an error saving. Here is the result of your action: 

redux.min.js?ver=3.6.5:1"

Can you please help me with that thanks.

Cheers,

Marco

**Comment by kprovance** [comment]
Could you please open a new issue window, read it in its entirety and provide the required information?

Are you the theme author?

**Comment by MarcoFerry** [comment]
Hey kprovance ,

I have just seen that the support is only for theme authors.
But I have already asked the author of my theme. He said I should ask my hosting provider but they also have no idea what is wrong. So that`s why I wanted to try it here because it seems the right place.

That's why I would be really happy if you could quickly look over my problem:
I can't save any changes withing my theme options. 

Here is a overview of all the errors today:

[errors.txt](https://github.com/reduxframework/redux-framework/files/1422711/errors.txt)

I would really really appreciate your help. Thanks.

Cheers, Marco

**Comment by kprovance** [comment]
Salient theme.  Figures.

Problem is, this author is embedding Redux in his theme, and it is impossible for us to know what, if any changes he has made, or hooks he uses.  it amazes me how these kids take money and then don't offer support.  Leave a bad review, that will get their attention.  The other problem is, for me or Dovy to investigate this, it's 100 dollars an hour, and it could take several.  We don't work for free here anymore, I am sorry to report, especially when the author was paid to provide support, and we don't see a cent of that..  It could mean logging into your server and investigating issues unrelated to Redux...and personally, I am not comfortable messing with other folks' servers, because I could get blamed for just about anything after that.  But yes, a 500 error is server related.  

What I can tell you is that the save function will fail (or used too, it was fixed later) when there was a PHP fatal error, of which I see several in that file.  The Salient author needs to review that so he can fix whatever he may have changed.  Also, he needs to update Redux.

Alternatively, you could download the Redux plugin from wp.org and activate that.  It will override his old version, plus you will also get updates.  Can't promise other things won't fail, especially if he made changes, but again, I have no way of knowing that.

**Comment by MarcoFerry** [comment]
Wow, thanks so much kprovance for your detailed help and information.
Sure, I totally understand your point. I really appreciate it that you still took the time to answer my question!
Knowing that I’m definitely going to contact Salient support again.

Have a nice weekend.

Cheers,
Marco

**Comment by MarcoFerry** [comment]
Download the Redux plugin from wp.org and activate that work out.
Thanks so much again.

Cheers,
Marco
