### ISSUE TITLE
I cannot access my WP admin panel if I active this redux-framework plugin. moreover my site cannot be drawn without this login. now what can I do?

### ISSUE THREAD

**Issue by linkworldus** [reduxframework/redux-framework#3446]

**Comment by kprovance** [comment]
Without any kind of version or debug data, it's impossible to say.  I can tell you that past issues involving this have always revolved around inadequate PHP settings, typically memory.  All that I can suggest at this point is for you to examine your PHP error logs and look for logs that pertain to Redux.  If you see messages about exhausted or insufficient memory, you will need to increase your PHP memory settings.  Otherwise, feel free to post back any messages that pertain to Redux for further review.  That's all we can do at this point.

Also, see:  http://www.wpbeginner.com/wp-tutorials/how-to-fix-the-wordpress-white-screen-of-death/

**Comment by kprovance** [comment]
Do you have any further information for us? Otherwise I will have to mark this as unresolved.  Thanks.

**Comment by kprovance** [comment]
I'm sorry, but for us to log into your server and and debug server issues is a premium service at $100.00 an hour.  Did you review PHP error logs as suggested?

**Comment by answersmode** [comment]
I think your problem is coming from link checker not from redux. 
The error comes from General Settings > Link Checker, not from redux.

Thanks.

**Comment by kprovance** [comment]
Okay.  Closing issue.

**Comment by linkworldus** [comment]
why are you closing the issue through quickly?

**Comment by kprovance** [comment]
You said the error came from something else.

**Comment by linkworldus** [comment]
Another person saying. I'm not saying.

**Comment by kprovance** [comment]
Still need to see PHP error logs that make reference to Redux.  As indicated previously, there is not much else I can do without those, as the white screen of death is almost always a server issue (or someone elses badly written plugin).  Please get those ASAP

**Comment by linkworldus** [comment]
I also think so, But I could not understand that, How can I solve this problem.

**Comment by kprovance** [comment]
I'm not able to support another plugin, I'm sorry.  This is the Redux issue tracker.  We support Redux only.  I need to see PHP error entries that suggest Redux is the issue.  Perhaps filing a report with the author of the other plugin would be helpful?

**Comment by kprovance** [comment]
Until the requested data can be provided, I am marking this issue as closed unresolved.
