### ISSUE TITLE
Issue with SSH/sFTP hosting environments related to typogrpahy field Google Font updates

### ISSUE THREAD

**Issue by covertnine** [reduxframework/redux-framework#3448]
We're running into some issues when running our WP systems on SSH2 FS_METHOD instead of direct that will cause warnings with the way the googlefonts are updated.

            if ( file_exists( $gFile ) ) {
                // Keep the fonts updated weekly
                $weekback     = strtotime( date( 'jS F Y', time() + ( 60 * 60 * 24 * - 7 ) ) );  
                $last_updated = filemtime( $gFile );
                if ( $last_updated < $weekback ) {
                    unlink( $gFile );
                }
            }

## Support Hash
http://support.redux.io/?id=hYRQRO6JoL2gy%2Fp5BNhUTDHi7Nn97efniHtYYFJiLlCfi04JLrqHErRsrYls%2FJGXHcWAVC04i0mXVtH9FCCeiA%3D%3D

## Steps to reproduce
Setup site on sFTP environment that's FS_Method is set to SSH2 and not Direct

## Expected Behavior
Google font files should be able to be re-created using the WP_FIlesystem commands instead of unlink because that fails on secure environments that aren't set to update FS_METHOD via the direct method. (We use SSH on our servers and sFTP for updates so this causes a warning for us)

inc/fields/typography/field_typography.php: unlink( $gFile );
inc/fields/typography/field_typography.json: unlink( $gFile );
inc/class.redux_helpers.php: unlink( $dir . "/" . $object );

I found it in those three places.

## Actual Behavior
See 3 code examples above--I believe those should use the WP_FIlesystem functions and should just be deleted. I see this code used throughout Redux, just not in this one particular field related to google fonts.

## Any Error Details (PHP/JavaScript)
PHP Warning: unlink(.... /inc/fields/typography/googlefonts.php): Permission denied in .../inc/fields/typography/field_typography.php on line 945

**Comment by kprovance** [comment]
This feature in Redux 3 was depreciated.  We no longer support it.  The good news is that in Redux 4 (not yet available), the entire Google font update system is automated, and none of that code will be used, and no API key will be required.  I hope to have a public beta available by the beginning of the new year.  Got some server issues to iron out and a few more outstanding issues to resolve before a relatively stable beta release can be made available.  Unfortunately, there will be no further work on v3 due to v4 being the primary focus now.  Sign up for our newsletter at www.reduxframework.com our follow our blog for announcements on the v4 beta release.
