### ISSUE TITLE
My Enter Multisite shuts down for period of time and comes back up

### ISSUE THREAD

**Issue by wcjbeneke** [reduxframework/redux-framework#3450]
I checked my website and the logs.  And the issue is coming from the theme SparkTheme, specifically this page: 
https://waynes.co/wp-admin/admin.php?page=SparkTheme&amp;tab=1

As per the developer of the SparksTheme, the cause of this is the 3rd Party app Redux-Framework. Without the application, my wordpress theme does not function. But at the same time it causes my multisite to shutdown randomly.

I would really appreciate some assistance regarding this matter.

**WEBSERVER ERROR LOG:**

[Tue Dec 12 09:30:46.931176 2017] [cgid:error] [pid 20875:tid 140381038573312] (32)Broken pipe: [client 105.186.220.126:50771] AH02550: Failed to flush CGI output to client, referer: https://waynes.co/wp-admin/options-reading.php
[Tue Dec 12 09:31:12.551644 2017] [cgid:error] [pid 20875:tid 140380905387776] (32)Broken pipe: [client 105.186.220.126:50818] AH02550: Failed to flush CGI output to client, referer: **https://waynes.co/wp-admin/admin.php?page=SparkTheme&tab=1**

**Comment by dovy** [comment]
Ha, your theme developer really needs to not offload issues that are related to their product back to us. They should have provided you support in regards to this.
 
This error could be caused by any kind of server-side issues. I would bet it is either a memory limitation or a no space on the hard disk, or permission issues.

We built this framework that millions of sites use on the net. I know for a fact your issue is not common. I would contact your host and look at the items I spoke about. If your theme developer uses a SASS/SCSS/LESS compiler for CSS, then the issue is on their side. 

Best of luck. Sorry you were sent back to us. I hope your host/theme-dev can help!
