### ISSUE TITLE
Website not Loading with Redux

### ISSUE THREAD

**Issue by kewalsunberg** [reduxframework/redux-framework#3470]
Hello there,

We're using Redux Framework, and the website wouldn't load when the plugin is activated.

It loads back (with some elements missing) when the plugin is deactivated. Our URL is truetribe.uk

Could this be due to SSL permissions or something else?

Looking forward to your help .

Thanks,
Kewal Ram
![true tribe paris wild by nature designer swim shorts backpacks](https://user-images.githubusercontent.com/35330321/34818802-b900b352-f6dd-11e7-96c9-7ce62026521b.png)
![true tribe paris without redux](https://user-images.githubusercontent.com/35330321/34818804-b9495b02-f6dd-11e7-9517-6b05a5e2d142.png)

**Comment by kewalsunberg** [comment]
Hi,

We're still unable to track this issue. Can you please help us out?

Thanks,
Kewal

**Comment by kprovance** [comment]
You provided none of the required information.  So, no, I cannot.  Google, 'WordPress white screen' and adjust your server settings as needed. As this is always what it turns out to be, a server settings issue, and not actually redux.  Good luck.

**Comment by kewalsunberg** [comment]
Hello,

May I ask what specific info is required? We googled everything and the server is working fine. As soon as Redux is deactivated, the site comes back up. We're using Rev slider and tried deactivating is with the Redux activated - to no resolve.

**Comment by kprovance** [comment]
If you read any of the texts in the new issue window when you filled it out, you would know. It's the same place that said we reserve the right to close tickets for not actually giving us this information. As I said issues like this are not Redux related, they are server related so please Google the term that I gave you in the last post. Ultimately these kind of things require server intervention and that is something that requires premium support from us, to figure out what is wrong because it is not actually Redux related.

**Comment by kprovance** [comment]
Is this your theme?  Did you author it?
