### ISSUE TITLE
wp-admin/tools.php?page=redux-about

### ISSUE THREAD

**Issue by fawad009** [reduxframework/redux-framework#3484]

**Comment by fawad009** [comment]
When clicking on Page option in wordpress admin redirects me to this link 
wp-admin/tools.php?page=redux-about

Please guide me solve issue so I can access my pages

**Comment by fawad009** [comment]
I m facing issue please guide me when clicking on 
https://www.kamagraukfast.com/wp-admin/edit.php?post_type=page

re-directs me to https://www.kamagraukfast.com/wp-admin/tools.php?page=redux-about

**Comment by kprovance** [comment]
I can't help you.  You did not fill the form out properly.  You did not give us the required information.  Since you did not read that information, I will tell you what you missed; if you do not provide the required information , e close the ticket.  Period.  If you do not feel the need to provide this information,you can pay us our premium support fee to answer you question one at a time.

**Comment by kprovance** [comment]
To log into your site and do debugging is a premium support issue.
