### ISSUE TITLE
Welcome Redux page launches when I try to launch ALL Pages of my wordpress site

### ISSUE THREAD

**Issue by amitjhs** [reduxframework/redux-framework#3510]
Hi,
When I am trying to launch Pages of my site, it is always redirecting me to Redux Welcome Page. 

URL I am seeing when trying to launch all pages 
http://qahacks.com/wp-admin/tools.php?page=redux-about

My Support ticket URL : 

http://support.redux.io/?id=md0Ctrdqk18m48VgZNIkgoGHiqrkc9YPL0cMkuSeTiHQE5%2FlsM52g6L0lU3Hzb4iz1zR4uUbiKA0QSKo06uFiA%3D%3D

**Comment by kprovance** [comment]
Are you the author of the theme, or a user of the theme?

**Comment by amitjhs** [comment]
I am a user of theme, creating my own website using this theme.

**Comment by kprovance** [comment]
You will need to seek support for the author of the theme.  We do not support theme user as 1) We have no idea how the theme author integrated Redux and 2) We cannot fix their code.  If the theme author is able to make the determination that the problem lies with our code, they must file a report and give us the required information.  This was all covered in the text inthe new issue window.  Sorry.  Good luck.
