### ISSUE TITLE
In select field i am pulling all the categories and then will select one out of them, way to set default category?

### ISSUE THREAD

**Issue by Nimeshbrt** [reduxframework/redux-framework#3516]
In select field i am pulling all the categories and then will select one out of them, which will display the posts of that category.
is there a way to set a default category or by default all categories (latest posts) is pulled ?

Thanks!

Here is the code i am using currently

`
     

array(
          
'id' => 'opt-select',
'type' => 'select',
'title' => __( 'Select Option', 'redux-framework-demo' ),
'subtitle' => __( 'No validation can be done on this field type', 'redux-framework-demo' ),
'desc' => __( 'This is the description field, again good for additional info.', 'redux-framework-demo' ),
				'data' => 'categories',
				'args' => array(
								'taxonomies' => array( 'category' ),
								'hide_empty' => false,
								),
				),
`

**Comment by kprovance** [comment]
For the data function of categories, to set the default, you would have to use the term ID, which is going to be different for each install, most likely.

The alternative would be to write a function to retrieve the categories using the WordPress API, and create your own option array with the key being the category name (instead of the ID), and then feed it into select using the 'options' argument.  Then you can specify the default based on name.
