### ISSUE TITLE
Media Uploads - Add/Edit Gallery does not load up

### ISSUE THREAD

**Issue by ThemeDirect** [reduxframework/redux-framework#3517]
Hi,

In theme options, when I use Media Uploads > Gallery > Add/Edit Gallery, I click on the Add/Edit Gallery button and popup window opens but i see a spinning icon (spinner.gif) next to the text "Drag and drop to reorder media files."

I expect to see an option to upload images to the gallery but the spinning doesnt stop until I click Cancel Gallery button and then click on Add/Edit Gallery button again. It then gives me the option to select files to add to the Gallery.

This issue can be replicated using your demo version: https://demo.redux.io/wp-admin/admin.php?page=_options&tab=0

Our theme is now ready for deployment but we cannot submit it until the final issues are fixed. Any ideas what is causing it? Since it is happening on your demo site too, it may be a good place to start investigating there first before i provide any more information.

Keep up the good work. This is a solid framework and looking forward to future releases!

Thank you.

**Comment by kprovance** [comment]
That is a WordPress issue, unrelated to Redux.  It happens when nothing is in the gallary.  If you click Add to Gallery and some a few things, then save it all, then go back and look again, the selected images appear.  Why that spinner thing happen with no images in the gallery is beyond me.  ASs I said, it is controlled by WP.  Our code just calls their API
