### ISSUE TITLE
Redux Framework embedded in Theme with Plugin?

### ISSUE THREAD

**Issue by db-dzine** [reduxframework/redux-framework#3535]
## Steps to reproduce
1. Install a theme with embedded Redux
2. Install a plugin that uses Redux options

## Expected Behavior
Plugin Menu Shows

## Actual Behavior
Plugin Menu does not show

So I have a theme, that uses Redux as an embedded version. But I also have a plugin, that uses Redux (if not class exists Redux). I tried different variations of hooks, but the plugin menu settings do not show. 

I tried 'plugins_loaded' with Prio 50, I tried 'after_theme_setup', but none of the actions work.

Do you know the correct Hook to use Redux in a Plugin, which has Redux embedded in a theme? Or is the only solution to use your offical plugin installed?

Best regards

**Comment by kprovance** [comment]
Go the plugin route.  Plugins load before the theme.  To hack around that isn't worth the trouble.  It would also be a premium effort on our part to even try.  Good luck.

**Comment by uaibo** [comment]
@danielbarenkamp  I just fixed a similar issue on my plugin where I'm using the embedded Redux. 
My sub-menu  was working before but I didn't update anything on my plugin since many months and just recently noticed the menu had disappeared. 

The correct hook is `after_theme_setup` so no change on that.
I changes these options in my ReduxFramework init settings:

```
'menu_type'  => 'submenu',
'page_parent'  => 'my_plugin_menu_slug',
```
Try it and see if it helps.
