### ISSUE TITLE
Redux Framework Compiler Not Working

### ISSUE THREAD

**Issue by FlippFlopps** [reduxframework/redux-framework#3559]
Main issue: compiler not working
Lesser issue: bad documentation

When trying to use the redux framework compiler to write an external css file:

THIS LINE:
`add_filter('redux/options/'.$this->args['opt_name'].'/compiler', array( $this, 'compiler_action' ), 10, 3);`

CAUSES THIS ERROR:
Fatal error: Using $this when not in object context in C:\xampp\htdocs\project\wp-content\themes\mytheme\admin\my-compiler-related-file.php on line 7

This is the code I used:
`add_filter('redux/options/'.$this->args['my_opt_name'].'/compiler', array( $this, 'compiler_action' ), 10, 3);

function compiler_action($options, $css, $changed_values) {
    global $wp_filesystem;
 
    $filename = dirname(__FILE__) . '/mycssfile.css';
 
    if( empty( $wp_filesystem ) ) {
        require_once( ABSPATH .'/wp-admin/includes/file.php' );
        WP_Filesystem();
    }
 
    if( $wp_filesystem ) {
        $wp_filesystem->put_contents(
            $filename,
            $css,
            FS_CHMOD_FILE // predefined mode settings for WP files
        );
    }
}`

I'm using the 'embed' option from reduxbuilder with 'compiler' set to TRUE.

Please note that your compiler-related documentation found here:
[https://docs.reduxframework.com/core/advanced/integrating-a-compiler/](url)
mentions initSettings, a sample-config and a compiler_action NONE of which exist in the entire code you deliver when redux is generated by reduxbuilder.

But since it says that the code from the documentation can be inserted 'anywhere in my code' I added the code after my theme options sections (after I defined all my fields).

**Comment by kprovance** [comment]
The $this object can only be used inside of a class.  That is basic PHP.  We cannot help with that.  Also, we no longer support that writing of the CSS file to the upload folder, as it will not work on all systems, especially those whose permissions are incorrectly set.

**Comment by FlippFlopps** [comment]
Thanks for replying quickly. Just to clarify, does "we no longer support that writing of the CSS file to the upload folder" mean the compiler doesn't work?

**Comment by kprovance** [comment]
The compiler works fine, that other bit will or will not.

For a working example of the compiler, see the /sample/sample-config file.  I will see about updating the code on that page.

**Comment by FlippFlopps** [comment]
I guess I'm giving up. I've been stuck trying update my css file dynamically for months and nothing works. 

https://docs.reduxframework.com/core/advanced/updating-a-css-file-dynamically/

So unless there is an example of the compiler that actually works (updates the css file dynamically as advertised in the link above) I'll have to go with the very bad (but working) solution of using a .php file as my stylesheet and fetch my redux css-related settings there. This, of course, requires wp-load.php to be run twice (drastic impact on load) because global $opt_name; doesn't get anything otherwise.

I hope this gets sorted out for everybody to enjoy and, until then, I'll focus on other stuff in my theme.

**Comment by kprovance** [comment]
We will not be providing any way to do that with Redux in the future.  

It's not a Redux feature...it's something that could be done with the compiler.  But since there is no reliable way to do it, because permissions on everyones server can and usually is different, it is the least reliable way to generate dynamic CSS.  It's also not the most optimal way, and why Redux has the 'output' feature.

While a neat trick, in the whole of things, it's not reliable.  You are setting yourself up for a support nightmare when complaints begin rolling in that 'it doesn't work', and why we no longer support that code.  Coz then people come to us wanting it fixed, and it can;t be, not reliably.  Again, I recommend the 'output' feature.  It's what I've been using for years without all the filesystem drama.

Good luck.
