### ISSUE TITLE
Multiple redux-framework issue 

### ISSUE THREAD

**Issue by mastmaster** [reduxframework/redux-framework#3594]
Hi,

I'm writing a plugin that uses your perfect redux-framework.

I have tested in many themes that use or not the redux-framework and everything works fine.

But in my latest test with a known theme I found a problem.

In my plugin redux panel it appeard the "search function" and it gives me from the other theme settings results. 

I could use CSS to hide it, but I want to know why is happened. 

![2018-10-31 11 08 45](https://user-images.githubusercontent.com/29559933/47819042-01b56a00-dd62-11e8-83d6-c02cbb986651.png)

Also, what is the best way to build plugins with redux-framework if we know someone else will also do without have conflict issues?

Do we need to check if reduxframework class has already registered?

**Comment by kprovance** [comment]
That is not functionality included within the Redux core.  I'm not sure where it came from.  Best guess, another theme/plugin that uses Redux has the Live Search extension installed (or they have written their own).  It's impossible for me to say since no support hash was given, which was requested and required for free support. (If you do not understand, open a new issue window and read the text that was provided).

Redux may be used in many instances that all run simultaneously.  As long as each project uses a different opt_name argument and a different page_slug argument (this all need to be unique to the project), there should be no conflicts.

**Comment by mastmaster** [comment]
Thank you so very much!
