### ISSUE TITLE
Create own option panel for users

### ISSUE THREAD

**Issue by lucnham** [reduxframework/redux-framework#3605]
I have an idea to make each option page for each user on my site. To do that, i need to make `$opt_name` flexible such as `$opt_name = 'site_opt_.' $user_ID`. I try to get user ID in config file but it return 0. I also try to hook a function with 'init', but it looks like my code is not working:
<pre>
function myOptionPage(){
    if ( ! class_exists( 'Redux' ) ) {
        return;
    }
    
    $user_ID = get_current_user_id();
    $opt_name = 'site_opt_'. $user_ID;
    
    // Configs and fields bellow
    // =========================
}
add_action('init', 'myOptionPage');
 </pre>
Does Redux core can make this? Do you have any way to solution my problem? And sorry for my limit English!

**Comment by kprovance** [comment]
My first thought would be hook priority?  Maybe?  Inherently, no it's not something Redux does out of the box.  I'm really busy with getting v4 ready, so it's not something I can play with right now.

I have to ask, what's the use case for something like this?  Historically, options are set  to determine the look and feel of the front end.  As soon as one user would set something, it would change the look, regardless who was logged on.  It doesn;t even address on how to output those options on the front because you'd have to specify a logged in user just to display them if the opt_name was dependent on a user name, therefore such things would only show if a certain user were logged in on the front end.  What would the default options be where no user name was specified?  Ina scenario such as this, doesn;t really seem feasable, which is why I am curious as to what your use case might be.

**Comment by lucnham** [comment]
Thanks to Kprovance! By your suggestion about hook priority, i have done with this:
<pre>
function myOptionPage(){
    if ( ! class_exists( 'Redux' ) ) {
        return;
    }
    
    $user_ID = get_current_user_id();
    $opt_name = 'site_opt_'. $user_ID;
    
    // Configs and fields bellow
    // =========================
}
add_action('init', 'myOptionPage', 1);
</pre>

Now it's work with my required, but I'm not sure there are any hidden issues, I'm a researcher, not a professional developer like you. Can you give me more advice on my case? Many thanks,

**Comment by kprovance** [comment]
You explained your use case.  Unfortunately, Redux would not be able to handle something like this as it is.  Even if one could attach a user ID to the opt_name, the output will still be very complicated for those not logged in as Redux would have to way to fallback on 'default data' with no opt_name.  Something like that would have to be written in, *assuming* it's possible.

I'm not sure how ACF does it. I could look when I have the time.  If you understand PHP, you could look as well.  :)
