### ISSUE TITLE
Wordpress 3.5.1 Problem

### ISSUE THREAD

**Issue by catistudio** [reduxframework/redux-framework#3615]
Wordpress 3.5.1 problem is product variable js button refresh page. Chrome tool console error "jquery-migrate.min.js". Please help. I deactivate redux problem solved. But theme need redux dont work.

**Comment by kprovance** [comment]
You may want to upgrade WordPress.  That file is not part of Redux  Otherwise, I have no idea what any of this means.  If you are the user of a theme, and not the actual theme author, you need to contact the author of the theme for support.  He may not even support such an old version of WordPress.  I cannot say and we did not author your theme.

**Comment by catistudio** [comment]
Sorry my wordpress version 5.0.1. 

same error
https://wordpress.org/support/topic/redux-framework-conflicting-with-woocommerce-attributes/

**Comment by kprovance** [comment]
As stated, that will be resolved in Redux v4.  Hopefully there will be a public beta sometimes early next year.
