### ISSUE TITLE
Usage of WP Plugins Path according to WP Codex

### ISSUE THREAD

**Issue by sbtre** [reduxframework/redux-framework#3629]
Dear Team!

We had issues using the plugin on a customized WordPress installation, were the plugin folder was in a different directory. The issue was, that Redux Framework (e.g. `ReduxCore/framework.php`) expected plugins to be located at `WP_CONTENT_DIR . '/plugins/'` 

That is not the correct way, because if you define a custom plugins location using `define(WP_PLUGIN_DIR, <path-to-dir>)`, `WP_CONTENT_DIR . '/plugins/'` may not exist.

Please use `WP_PLUGIN_DIR` instead, because it points to `WP_CONTENT_DIR . '/plugins/'` anyway if not changed: [https://codex.wordpress.org/Determining_Plugin_and_Content_Directories](https://codex.wordpress.org/Determining_Plugin_and_Content_Directories)

Thank you!

**Comment by kprovance** [comment]
Then everyone who embeds Redux inside a theme gets broken, and we don't do that.

Use these filters to manipulate the dir and url without messing with the core.  If you change the core, we cannot offer any type of support.

add_filter ( 'redux/_url', 'url_function_name' )  // Your callback will return your desired url
add_filter ( 'redux/_dir', 'dir_function_name' )  // Your callback will return your desired path

Good luck.

**Comment by dovy** [comment]
@kprovance is there any way we can do a "file_exists" check and switch between the two? Like another helper function?

**Comment by sbtre** [comment]
Dear @kprovance !
Thank you for the hint. 

Adding 
`function my_redux_dir( $path ) {
	$path = str_replace( '/content/plugins/', '/extensions/', $path );
	return $path;
}
add_filter( 'redux/_dir', 'my_redux_dir',  10, 1  );`
to my `functions.php` didn't help. I still saw it throwing an error 500. The only thing that helped was applying the `str_replace()` directly in the `framework.php` line `84 `and `102 `– And I really don't like to do that for good reasons ;-)

I'd appreciate if you'd implement a work around to fix this. 
Kind regards!

**Comment by kprovance** [comment]
I'm not sure what kind of a workaround you want implemented.  We can't code our core to individual installs.   That's why we have filters.   I don't know enough about your install or situation to say much more without this becoming a premium support issue.  I spoke to @dovy about it, and it's something we can look at for v4 when we get the time.  We're no longer updating v3 for anything unless some huge security hole is reported.

As long as the path you pass back through the filter is the path/url to ReduxCore, all the references within Redux should respect that.  Why do a str_replace?  Just create the path/url using the WordPress API or PHP functions?  You'll just have to play with it until you can get the properly formed path you want.

You can also change the WP_CONTENT_DIR value.  See:  https://premium.wpmudev.org/blog/change-wordpress-file-directory-structure/

**Comment by sbtre** [comment]
Dear @kprovance !
Sorry I need to bother you again, but I came across this issue some more times.

Currently implemented in Redux 3.x and 4 beta: 
In file `ReduxCore/framework.php` Redux tries to get the WordPress plugins folder by using
`WP_CONTENT_DIR . '/plugins/'` which always results `/some/server/dir/httpdocs/wp-content/plugins/`

In case that the plugin folder ist not located in wp-content, there is an error. I do that using official method with defining `WP_PLUGIN_DIR`
Example: `/some/server/dir/httpdocs/my-plugins/`

Please, instead of using `WP_CONTENT_DIR . '/plugins/'` use `WP_PLUGIN_DIR` in file `ReduxCore/framework.php` 
I won't break anything but fixes any installations with custom plugin paths :-)

Thanks for your dedicated work!

**Comment by kprovance** [comment]
@sbtre , I am no longer with Redux, so I can't really be of any help anymore.  That said, unless something has changed, the proposed solution might break backward compatibility with embedded installs, which do not use WP_PLUGIN_DIR.  I think there was a filter hook added so one could adjust the dir path set in the core?  @dovy could tell you.  I honestly don't remember.  Good luck.  :)
