### ISSUE TITLE
ATTENTION DEV!  REDUX v4 BETA NOW AVAILABLE!!

### ISSUE THREAD

**Issue by kprovance** [reduxframework/redux-framework#3632]
The public beta for Redux v4 is now available!  You can find it here:  https://github.com/reduxframework/redux-framework-4

A couple of things.

1. Please review carefully the READ ME text posted on the repository.  That information is very important and may answer many questions ahead of time.

2. Please do NOT post issues about Redux v4 in THIS repo.  Please use the issue tracker via the link above.

Have fun!

**Comment by linkworldus** [comment]
Dear Sir,
When I'm installing and active this plugin, I cannot access wp-admin panel and my site outlook changed. I'm facing this problem after clicking on the demo. I cannot resolve my problem. Please help.

This plugin is required for my theme. Please see my website: https://www.linkworld.us/
Thanks

**Comment by Lenovo1970** [comment]
Hi, my purchased template makes many mistakes due to Redux 3.6.15. The author of the template no longer responds to support anyone, so no help. I have installed Redux 4 beta and everything is OK. Although when I open the post editor, the post setting does not respond and you get an error: Compilation failed: **invalid range plugins / js_composer / include / autoload / hook-vc-grid.php on line 162**. Can you tell me what to do with it? Thank you, I've been dealing with it for a long time and I'm desperate. Leo

**Comment by dovy** [comment]
@linkworldus are you still having issues? Please open a new issue and give us more details.

@Lenovo1970 please do not piggyback other issues, create a new one. The error you are seeing is related to Visual Composer or WP Bakery Composer. I'm sorry, but it's difficult for us to support something we did not build.

**Comment by linkworldus** [comment]
> @linkworldus are you still having issues? Please open a new issue and give us more details.
> 
> @Lenovo1970 please do not piggyback other issues, create a new one. The error you are seeing is related to Visual Composer or WP Bakery Composer. I'm sorry, but it's difficult for us to support something we did not build.

Hello Sir,
My problem was solved yesterday. Now I can access my website (**linkworld.us**) and my theme is working correctly.
Thanks.
