### ISSUE TITLE
Problem with Foreach

### ISSUE THREAD

**Issue by Productdb** [reduxframework/redux-framework#3673]
Hello,

i think ther is a problem with the Multisite and the redux framework. i've got following error: supplied for foreach() in /wp-content/plugins/redux-framework/class.redux-plugin.php on line 121

is this a known issue ?

thanks,

Bricke

**Comment by dovy** [comment]
This could be a wide variety of reasons why this happened. It is probably best to contact your theme author to help, or if you’re a developer to offer a support url for us to debug. We do have a phpunit that runs against multisite, so my guess is the issue is in the product using Redux, not Redux itself.
