### ISSUE TITLE
Redux Framework causes black screen when editing pages in Elementor Pro

### ISSUE THREAD

**Issue by PBGRSA** [reduxframework/redux-framework#3708]
When activating the redux framework plugin does the editing screen of Elementor Pro become a black screen, please help.

**Comment by dovy** [comment]
@PBGRSA can you please provide a support URL? https://docs.redux.io/guides/basics/generating-a-support-hash.html

**Comment by PBGRSA** [comment]
Hi Dovy,

The new redux framework 3.6.18 update is also doing the black screen
https://ecpdpro.co.za/wp/wp-admin/post.php?post=3031&action=elementor
http://support.redux.io/?id=88Y4hY7IEKpbgCuATvlp9qBoyjZCYs%2FBIbJ%2F30VeXoCYBL%2BY46hTN32tozt4yPU7mG2wUUWo8qD%2FVKa2%2BYzmHQ%3D%3D

**Comment by dovy** [comment]
So sorry I dropped the ball on this. Did they ever get back to you?

**Comment by PBGRSA** [comment]
Hi Dovy,
I have updated my website a few times now but the issue is still not sorted

Regards,

Pieter

**Comment by dovy** [comment]
Have you tried Redux 4? Do you have a JavaScript error in the console?

**Comment by PBGRSA** [comment]
Running version 3.6.18 and Wordpress 5.4.2
No JavaScript error

**Comment by dovy** [comment]
Try this zip as the Redux plugin: https://github.com/reduxframework/redux-framework-4/archive/master.zip

From there the next step is you handing me access to your site or copies of your theme and elementor pro. :(

**Comment by PBGRSA** [comment]
Site:  https://ecpdpro.co.za/login/
User Name:Dovy
Password : iJF%VR5qvxgzP0QcJcCO3@(t

got the same issue on my other site too

**Comment by dovy** [comment]
Login doesn't work. Send to dovy@redux.io rather than giving yourself security issues. ;)

**Comment by PBGRSA** [comment]
sent

**Comment by dovy** [comment]
*sigh* The issue is you've improperly installed WordPress in a sub directory.

https://stackoverflow.com/questions/45431506/warning-fileperms-stat-failed-for/48455044

You'll need to configure it properly. WP requires the index.php file because it attempts to use it to initiate the filesystem. It did indeed seem like it was a Redux issue because we were trying to initialize the filesystem. The issue was symptomatic, but now the real concern.

Rule of thumb, don't get rid of the index.php file for WordPress. https://cldup.com/T_tokNUJbg.png

**Comment by PBGRSA** [comment]
That's interesting as I installed wp only once, had guys from envato work
on the system due to a header issue I had on both my sites.
