### ISSUE TITLE
Redux Framework 3 may break with WordPress 5.4.2 Security and Maintenance Release on 10th June?

### ISSUE THREAD

**Issue by richardbushell** [reduxframework/redux-framework#3729]
Our WordPress Theme options will NOT SAVE using Redux Framework 3.

It's a fresh WordPress install using the new WordPress 5.4.2 Security and Maintenance Release on 10th June.

I updated the Redux Plugin manually to version 4 and now it saves perfectly!

Because it's a fresh install, untested on WordPress prior to 5.4.2, I cannot say for definite that that was the break point, but the theme vendor replicated the non-save issue and reports no previous issue.

I got the idea/info from this issue posted a few days ago on the Redux GitHub page: https://github.com/reduxframework/redux-framework/issues/3726

Just a heads-up as this may need patching or an acceleration to release v4 asap.

**Comment by dovy** [comment]
Hey, can you provide me a support URL from the admin panel? This will let me know how to duplicate your environment so that I can mimic everything on my side.

This is actually great to know since Redux 4 is nearly ready and I am so glad it's working for you.

Please do get me that support URL. You can find it by going to Tools -> Redux -> Support URL.

Thank you.

**Comment by richardbushell** [comment]
https://support.redux.io/?id=JqfzkP6%2Br78%2F0dM7bnkLuHkh7vjFCyJ6lDiu6uadwG61oZveTUg%2FAViuy9I687tgbcBlyANpXTUl2cddzK0YXg%3D%3D

**Comment by dovy** [comment]
Thank you good sir. I'll get on it.  :)

**Comment by dovy** [comment]
Redux 4 has been released.  :)
