### ISSUE TITLE
Website using Redux Framework is very slow

### ISSUE THREAD

**Issue by devxpre** [reduxframework/redux-framework#3750]
Hello,
I'm using Redux framewok in my theme, version : 3.5.4.13 under php 7.2.
My website was fine, suddenly, it becomes very slow, even simple page needs 1min to be loaded, i tried everything to detect the problem but no way, so i started debugging my theme , my observation is when i comment the line which is calling the framework, the website becomes faster.
So i really need your help if someone has faced the same issue.

Regards ;

**Comment by dovy** [comment]
Oh no! Can you try Redux 4.1.14 just released and then let me know how it turns out?

If that doesn't fix anything, please let me know the theme you use and site URL. I will try and see if there's anything I can see form this end.

Lastly, if you want to go back to the previous version of Redux install WP Rollback and follow the steps in this video to go back to Redux 3.6.18. https://www.youtube.com/watch?v=oaiAzmpgbYU

Please give me as many details as you can and I will do all I can to help you. Thank you.

**Comment by dovy** [comment]
We have a fix for this and you should be able to use Redux 4.1.x from here out. Thank you for letting me know!
