### ISSUE TITLE
ongoing 404's to http://reduxframework.com/wp-content/uploads/redux/redux_notice.json

### ISSUE THREAD

**Issue by g000m** [reduxframework/redux-framework#3788]
https://github.com/reduxframework/redux-framework/blob/e22b479e620da493523c893bfc008f6c61e68da2/ReduxCore/framework.php#L432

I have at least a dozen sites that are making many requests to this URL per hour:

http://reduxframework.com/wp-content/uploads/redux/redux_notice.json

The URL has been 404ing for weeks - months

**Comment by kprovance** [comment]
Hi!

Redux 3.x has reached its end of life.  We will no longer be maintaining it.  Please update to Redux v4, which will be moved to this repository shortly.  Should you should discover the same issue with Redux v4, please rereport the issue, making sure to supply the required information request via the New Issue form.

Thank you for choosing Redux.

- Kev

**Comment by g000m** [comment]
I put this in wp-config to resolve it:

global $redux_notice_check;
$redux_notice_check = 1;

**Comment by kprovance** [comment]
All of this no longer exists in Redux 4. For security reasons, I strongly recommend updating,

**Comment by g000m** [comment]
I'm seeing this in current versions of plugins and themes where the developer has not bothered to upgrade. Would it be possible to recreate that redux_notice.json file and add an upgrade notice? Educate users, which will turn into motivation for developers to upgrade.

**Comment by kprovance** [comment]
Here's the problem with that: People hated it. The complaints never stopped (as you can see from this thread). Even if we were to do something like that again, it doesn't help this situation in which v3 users are not updating. I'll wager most of those themes are no longer supported.  For those that still do, it's their responsibility to stay on top of vendor files. If they don't, I'd find another theme, because you'd be opening yourself up to security issues. Our documentation is clear on embedding. We strongly discourage it. It's still possible, but for security reasons, it's ideal to do the plugin with TGMPA.
