### ISSUE TITLE
Hood Theme not working with Classic Editor?

### ISSUE THREAD

**Issue by Amigaeng** [reduxframework/redux-framework#3812]
Hi I'm using the Hood Theme on our company Wordpress website and for a while now, the "Classic Editor" block editor/page builder does not work when I try to upgrade the PHP level of our website. When this happens a garbled code comes up on our pages and can't get rid of it unless I drop back the PHP manager level back to 7.1.33
I believe the automatic PHP levels for wordpress are just up to 8!
I found in a few forums with other themes that had the same issue, the author/developer was able to tweek some code at their end of the theme to allow "Classic Editor" to work and they haven't had any issues since and were also able to upgrade to the latest php
Please is someone able to help with this?
If Redux can't, do you know a way to contact Hood Themes direct? 
I saw though that there a few people on here that have had issues with Hood Theme and someone from Redux has responded, so am hoping someone will to this. 
I guess maybe it could also be something to do with WPBakery Page builder? if Hood Theme can also be tweaked to work with this page builder too now?
Thank you in advance I look forward to your urgent reply

**Comment by kprovance** [comment]
Unfortunately, we didn't author the theme, and this sounds more like a theme issue.  I use Classic Editor frequently, usually on PHP 7.4 and sometimes 8.0 without an issue (however, that plugin was recently updated due to problem with WP 5.8, so, that could very well be part of the issue).  The author of your theme should be able to answer these questions for you.

Good luck!

- Kev

**Comment by PennyMarketing** [comment]
I have a quick question.

I look at google analytics or shopify analytics and it says that for referrals on site traffic, github ranks high.  How is that?  Why would people be coming from “github”?


[A picture containing text  Description automatically generated]

Amanda Penny, Director
Facebook<https://www.facebook.com/aPennyMarketing?ref=hl> | LinkedIn<https://www.linkedin.com/company/a-penny-marketing?trk=top_nav_home> |  ***@***.***?subject=ATTN:%20Penny%20Marketing>
   Penny Marketing<http://www.apennymarketing.com/>

3201 Edwards mill rd
suite 141-607
raleigh nc 27612
(o) 910.53.penny
(f) 919.917.7661





From: Kevin Provance ***@***.***>
Date: Friday, July 23, 2021 at 1:12 AM
To: reduxframework/redux-framework ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [reduxframework/redux-framework] Hood Theme not working with Classic Editor? (#3812)

Unfortunately, we didn't author the theme, and this sounds more like a theme issue. I use Classic Editor frequently, usually on PHP 7.4 and sometimes 8.0 without an issue (however, that plugin was recently updated due to problem with WP 5.8, so, that could very well be part of the issue). The author of your theme should be able to answer these questions for you.

Good luck!

  *   Kev

**Comment by kprovance** [comment]
This is a support for for Redux Framework.  I would have no way of answering that question.  Sorry.
