### ISSUE TITLE
Fatal error Using renamed function at v4.x+

### ISSUE THREAD

**Issue by prionkor** [reduxframework/redux-framework#3833]
## Edge Case: 

Multiple plugin using Redux framework including `v3` and `v4`. `v3` gets required and `v4` skipped by conditional `if(class_exists()){}`

## Explanations 

Classes of v4.x weren't separately namespaced. Imagine a scenario where a site uses multiple plugins that have a redux framework included. If all of them are using the `class_exists()` function system will only allow include one library either `3.x` or `4.x`. Which version of the redux will be included will totally depend on whichever plugin file WordPress parses first. 

If 4.x gets included everything will work fine as previous methods from `3.x` (ie: `Redux::setArgs()`) still exists in 4.x.

The problem occurs if 3.x get included and you shipped your code with `4.x` version methods. (ie: `Redux::set_args()`. This will cause a fatal error and your plugin will crush a site. 

If versions were properly namespace then the situation could be avoided, but it's too late for that. What is the recommended way of using v4? I can imagine doing a version check and use the v3 version of the method if the version is not v4.

**Comment by kprovance** [comment]
I would just not use Redux 3.x at all.  It's reached end of life and we no longer support it.  It has far too many security issues.  I'm assuming these are your projects.  You didn't say.  Or, modify the v3 code however you need.  Technically, running the v4 plugin should override everything, but I've seen devs do some unconventional things with Redux, so, who knows.  If you can, dump v3.  Beta bet.

**Comment by prionkor** [comment]
> I would just not use Redux 3.x at all

I am using 4.0 on all of my plugins now. But not everyone does.

> Technically, running the v4 plugin should override everything

Not what I've seen so far. Includes/requires are first come first serve. So, if a plugin in the earlier hierarchy in (`active_plugins` option) will add the class definition and if that is 3.x, 4.x will never be included even all other plugins use it. I don't see any way of mitigating this. Other than pushing my plugins filename at the beginning of the `active_plugins` option array (untested).

FYI: I will continue to use the camelCase version of the methods. Otherwise old plugins (other devs) with redux 3.x will most likely to break the site.

I wish v4 was available with a namespace `V4/Redux`. This would avoid this issue.

**Comment by kprovance** [comment]
Well, I wish people would stop using v3.  It's been years since we got rid of it.  Namespaces were not an option then because of old versions of PHP that WordPress still supported.  I'm not able to reproduce this.  I don't have the same config or setup you do.  If you have any suggestions short of rewriting v4 from the ground up, I'll listen, or, can get me access to whatever plugin insists on loading v3 first.  You have to appreciate how damned difficult it was to maintain backward compatibility from v3, especially when most devs didn't use v3 correctly.  It's a statistical impossibility to know every incorrect method used and compensate for it.  Redux is supposed to push itself to the top of the plugin load list to avoid this.  I must assume another plugin is doing the same.  I don't know.
