### ISSUE TITLE
this version Working fine with localhost server but not working with server

### ISSUE THREAD

**Issue by lifeweblab** [reduxframework/redux-framework#3838]
Hi Developer,
i am wordpress developer. mostly working with redux option fremwork . this version good working with localhost server when upload the theme any server like aws or hostgater etc. it giving error 

like this

Redux will send the debug information found on the WordPress Site Health screen and your Redux config to our secure server. Are you ready to proceed?

Transmitting data...

Developer Mode Enabled
JeffsBuy
1.0
Did you know that Redux sets a global variable for you? To access any of your saved options from within your code you can use your global variable: $redux_demo

  Basic Fields
Checkbox
Radio
Sortable
Text
Multi Text
Password
Textarea
  Editors

**Comment by kprovance** [comment]
That a feature, activated by CTRL+SHIFT+H, that is not yet available and will not work yet.  My only advice is...don't use that key-combo.  It won't do anything anyway.

**Comment by lifeweblab** [comment]
i don't know why give this command. the problem not solved. 
the error come from URL. the file not accepting

**Comment by kprovance** [comment]
I'm not understanding your issue.  There is clearly a breakdown in the language barrier.

That screen you described doesn't show unless the key combo is pressed.  I don't see how it shows up on its own.  Clicking Ok to that message will not work.  It sends a request to 127.0.0.1, which is localhost.  It should do absolutely nothing.  I wouldn;t even mess with it.  If the issue is something else, then I do not understand what it is.
