### ISSUE TITLE
I found an issue on the new metabox system

### ISSUE THREAD

**Issue by webbudesign** [reduxframework/redux-framework#3852]
The editor field works well with the v4.3.1 and when I update the new meta boxes  v4.3.2 > v4.3.3 > v4.3.4  the editor field removes HTML characters while saving. This issue only happens if you use the editor field as a meta box.

**Comment by kprovance** [comment]
Could you please go back and read the posting guidelines?  I will also require very specific steps to duplicate the issue.  Thanks.

**Comment by webbudesign** [comment]
## Steps to reproduce
Please add a simple editor field to the page section. and try to use HTML chars or TinyMCE buttons like bold italic.

## Expected Behavior
It should show the content correctly. ex: `<strong>123123123</strong> `

## Actual Behavior
It is showing simple text. Removing p strong i - etc... ex: `123123123`

**Comment by kprovance** [comment]
Well, required information is still missing, but that's fine.  If you don't want to post it, we can do it the long way.

Redux core has metaboxes included as of v4.3.2, which is overriding whatever older version you are using.  I have no idea what version that is or how old it is.  I am unable to duplicate any scenario in which the save works as expected, which *suggests* whatever version you have is older.  Since I have no way to recreate the expected condition, I am now looking for a needle in a stack of needles since I am unable to compare code that works with code that does not work.

To try and save time, you'll have to send me your theme that has, I would assume, the metaboxes extension installed so I can recreate the expected condition and search for the differences.  Otherwise, this will take a lot of time, possibly weeks.  If you're a developer, you're also free to see if you can find the difference.  But if it's on me, I need the theme.  If you do not want to post it here, you can use something like WeTransfer and send it that way to kevin.provance@gmail.com

**Comment by kprovance** [comment]
Actually, never mind.  I think the problem is in the array sanitize.  I can change it to wp_kses_post which will allow for the same HTML that the average post would allow.  The is for security reasons.

**Comment by webbudesign** [comment]
Thanks for the fix.
