### ISSUE TITLE
Editing in sample options is not working . 

### ISSUE THREAD

**Issue by Sulovemosharaf004** [reduxframework/redux-framework#3962]
I installed redux framework manually but pasting it into the theme directory , now no matter how much i edit in the redux sample options it dosent show in the main webpage , only header.php codes are not and not are being able to edit by redux , what to do?? and I had renamed sample-config to options ,

**Comment by kprovance** [comment]
This is far too vague for me to attempt to answer, and honestly, I don't understand what you are asking. I recommend going over the docs site for detailed information on how to use Redux. https://devs.redux.io

If you activate the demo mode via Settings > Redux, you can see exactly how Redux is supposed to work. If you are using the sample-config.php as your base, you MUST, MUST, MUST change the opt_name and the page_slug global arguments, at minimum.

Lastly, writing a theme and using Redux requires, at minimum, a more than intermediate understanding of PHP and JavaScript. If you don't have those skills, I recommend learning them first. We are not able to assist in writing themes.  Otherwise, your question needs to be very specific AND, you must include all the required information we asked for when you posted this issue.  As this service is free, that's a must.
