### ISSUE TITLE
Use of undefined constant REDUX_PLUGIN_FILE

### ISSUE THREAD

**Issue by MorenoDD** [reduxframework/redux-framework#3965]
## Site Health Report
WordPress Version: 6.3.1
Server: nginx/1.16.0
PHP Version: 7.4.1

## Steps to reproduce

1. Download Redux framework
2. Follow this guide https://devs.redux.io/guides/advanced/embedding-redux.html to embed ReduxFramework 
3. Get the error

## Expected Behavior
No Errors

## Actual Behavior
Error displayed:
Warning: Use of undefined constant REDUX_PLUGIN_FILE - assumed 'REDUX_PLUGIN_FILE' (this will throw an Error in a future version of PHP) in 'my_theme_path/nope-redux/4.4.0/sample/sections/extensions/js-button.php on line 25

**Comment by kprovance** [comment]
I can have that fixed for the next version. I must strongly encourage you NOT to embed Redux, per the warning on the docs site. The ability was left for old Redux 3 users. The issue is, that if you do not keep Redux current, you'll miss out on updates and possible security fixes. Using the plugin and installing it via TPMGA solves that issue. Most themes on ThemeForest do this.
