### ISSUE TITLE
Project Icon Category Type Not Change

### ISSUE THREAD

**Issue by dersjet** [reduxframework/redux-framework#3994]
The icons of the categories in the projects header are not changing please detek. all icons are the same 
<img width="1339" alt="Screenshot 2024-03-14 at 15 14 17" src="https://github.com/reduxframework/redux-framework/assets/104524357/51406f69-66c7-40bc-ba3d-7a7c9e3403bc">

**Comment by kprovance** [comment]
PLEASE DO NOT POST! PLEASE READ!  

We cannot offer support if you are using a theme or a plugin that includes Redux Framework.

Why? Redux allows developers to include an options panel in their projects. Consequently, we cannot offer support for folks who have purchased a theme or plugin that uses Redux Framework. The responsibility of support for themes and plugins befalls upon its author. 

The reason is simple. Each theme/plugin author integrates Redux in different ways. We do not know how these authors use Redux in their projects. The project and the code belong to them. The author must be the individual to support their work. They are responsible for debugging any problems or issues that arise with their work. If the author determines the problem rests with Redux Framework, they must come to us and file a ticket. That is when we will look at an issue more closely.

We realize that some authors have included support links for Redux in their projects when they should not have. We apologize for that confusion and are taking steps to remedy this confusion. 

Please contact the author for support if you have purchased a theme or plugin that uses Redux. If the author is unavailable to support their work or has discontinued support, please refer to this before posting to our issue tracker: https://devs.redux.io/core/support-defined.

Because of these policies, we can no longer answer the influx of these types of issues individually. They will be closed without a reply. We're sorry about this and apologize for this inconvenience.

Please refer to your theme/plug documentation to contact the author for support.

Thank you. Good luck!
