### ISSUE TITLE
Page not loading

### ISSUE THREAD

**Issue by ScruffAu** [reduxframework/redux-framework#4002]
Hi Guys,

I have just changed my template/theme for www.logistixau.com.  The website is visible through the editing software, however does not load up on the browser. See attached.  

Can you please advise if there is something wrong with my settings.

Cheers 
Mark
![Screenshot 2024-06-05 003851](https://github.com/reduxframework/redux-framework/assets/171706394/c7f77027-29e3-4cb4-9928-6950704c4504)

**Comment by kprovance** [comment]
PLEASE DO NOT POST! PLEASE READ!  

We cannot offer support if you are using a theme or a plugin that includes Redux Framework.

Why? Redux allows developers to include an options panel in their projects. Consequently, we cannot offer support for folks who have purchased a theme or plugin that uses the Redux Framework. The responsibility of supporting themes and plugins falls upon their author. 

The reason is simple. Each theme/plugin author integrates Redux in different ways. We do not know how these authors use Redux in their projects. The project and the code belong to them. The author must be the individual supporting their work. They are responsible for debugging any problems or issues that arise with their work. If the author determines the problem rests with the Redux Framework, they must come to us and file a ticket. That is when we will look at an issue more closely.

We realize that some authors have included support links for Redux in their projects when they should not have. We apologize for the confusion and are taking steps to remedy it. 

Please contact the author for support if you have purchased a theme or plugin that uses Redux. If the author is unavailable to support their work or has discontinued support, please refer to this before posting to our issue tracker: https://devs.redux.io/core/support-defined.

Because of these policies, we can no longer answer the influx of these types of issues individually. They will be closed without a reply. We're sorry about this and apologize for this inconvenience.

Please refer to your theme/plug documentation to contact the author for support.

Thank you. Good luck!
