### ISSUE TITLE
SEOLAND Theme Support Request - Service Page Sidebar Placement

### ISSUE THREAD

**Issue by Fleekerwiser** [reduxframework/redux-framework#4003]
Dear SEOLAND Theme Support Team,

I am currently using the SEOLAND theme for my website. On the service page, the sidebar is positioned on the left side. I would like to move the sidebar to the right side of the service page.

Could you please provide me with instructions on how to achieve this within the theme's settings or CSS? Any guidance or code snippets would be greatly appreciated.

Thank you for your assistance.

Sincerely,

Fw

**Comment by kprovance** [comment]
Since you skipped over it, I'll post it for you again.


PLEASE DO NOT POST! PLEASE READ!  

We cannot offer support if you are using a theme or a plugin that includes Redux Framework.

Why? Redux allows developers to include an options panel in their projects. Consequently, we cannot offer support for folks who have purchased a theme or plugin that uses Redux Framework. The responsibility of support for themes and plugins befalls upon its author. 

The reason is simple. Each theme/plugin author integrates Redux in different ways. We do not know how these authors use Redux in their projects. The project and the code belong to them. The author must be the individual to support their work. They are responsible for debugging any problems or issues that arise with their work. If the author determines the problem rests with Redux Framework, they must come to us and file a ticket. That is when we will look at an issue more closely.

We realize that some authors have included support links for Redux in their projects when they should not have. We apologize for that confusion and are taking steps to remedy this confusion. 

Please contact the author for support if you have purchased a theme or plugin that uses Redux. If the author is unavailable to support their work or has discontinued support, please refer to this before posting to our issue tracker: https://devs.redux.io/core/support-defined.

Because of these policies, we can no longer answer the influx of these types of issues individually. They will be closed without a reply. We're sorry about this and apologize for this inconvenience.

Please refer to your theme/plug documentation to contact the author for support.

Thank you. Good luck!

**Comment by Fleekerwiser** [comment]
Thanks for getting back to me.

I understand what you're saying about Redux Framework. However, even without it, there should definitely be a way to change the sidebar's position from left to right, or vice versa.

Could you please point me in the right direction on how this is generally done, or perhaps where I can find this information?

Any help would be greatly appreciated!

**Comment by kprovance** [comment]
We don't support themes, that is something the theme author would have to put in his code. We have ZERO to do with it. You're asking the wrong person. I'm not sure why contacting the theme author would be so difficult.
