### ISSUE TITLE
Fatal error: Class 'ReduxFramework' not found - After Updating plugin

### ISSUE THREAD

**Issue by NickMcBurney** [reduxframework/redux-framework#745]
Hi, ive just updated the plugin and im getting the following issue:

( ! ) Fatal error: Class 'ReduxFramework' not found in C:\wamp\www\wordpress\wp-content\themes\nicks-theme\theme-options\config.php on line 142

Line 142 in my config file is this: 'img' => ReduxFramework::$_url . 'assets/img/social/Twitter.png'

Not sure whats happened?

Thanks in advance

**Comment by diantetr** [comment]
hello . İ have same problem . i try everything pls help me bro!

**Comment by RohiniDiwakar** [comment]
Hi,
I've installed the passion redux-framework plugin on my site but on activation it gives 500 internal server error. On running wordpress in debugging mode it gives following error:
Plugin could not be activated because it triggered a fatal error.
Fatal error: Class 'ReduxFramework' not found in G:\PleskVhosts\panoramastudios.in\httpdocs\beta\wp-content\plugins\passion-redux-framework\class.redux-plugin.php on line 148

I have installed and activated the same plugin on another site and it works fine.
I have also compared the class.redux-plugin.php files of both the sites but there's no difference.
Please provide solution to this problem.

**Comment by kprovance** [comment]
1) Please do not piggy back old issues.

2) 'passion-redux-framework' is not use.  it sounds like a developer took our core and modified it.  We do not support custom modifications.  Please contact the author of the plugin or theme that uses this modified version.  They need to support it.
