### ISSUE TITLE
How to remove URL field from Slides

### ISSUE THREAD

**Issue by pnpetroff** [reduxframework/redux-framework#833]
Has been following the progress of Redux for a long time and now I'm using it for a more serious project.

I'm testing the slides field but I need only the **Title** and **Description** field.

So how can I remove the **URL** field?

EDIT:

I want to create fields for a slider. It should have **Title**, **Description** and **Image**. However it seems there is no image field in the Slides field.

How can I create repeating fields for a slider?

**Comment by hassanrazmy** [comment]
I just found this closed thread while searching how to disable image from slides. I tried 'show' argument which is to enable or disable 'title', 'description', 'url' but not image that what i was looking for.

                        'id' => 'home_slider',
                        'type' => 'slides',
                        'show' => array(
                            'title' => true,
                            'description' => true,
                            'url' => false              // <<========= that is what was asked at the top.
                        ),
                        'title' => __('Add slides to your home page slider', 'framework')

I don't want to create an issue for this one but a question that is there any chance i can handle image by any argument instead of modifying redux code functionality.?

**Comment by kprovance** [comment]
This has been answered dozens of times.  You either need to overload the field, or create your own extension based on the field.

https://docs.reduxframework.com/core/advanced/add-a-custom-field/
