### ISSUE TITLE
Using redux variables for sass

### ISSUE THREAD

**Issue by zerocool1** [reduxframework/redux-framework#897]
Here's an example of something I want to do:

In redux theme options panel, allow user to set Primary Color 
Using Sass, set a mixin using the Primary Color variable (for gradients)

I'm assuming you just can't put the PC variable into the sass file .. so is this done in a style.php type file or done right in the redux config file? I feel like it must be done in the config file ... I've read up on using compiler, but I'm obviously missing something

**Comment by nova-ind** [comment]
@dovy @zerocool1 I know this is almost a year old now, but this is the only thing I could find related to using Redux options for dynamic Sass.

I'm on a MU setup, if that matters. The problem is the options object is undefined when wp-sass compiles the stylesheet. From what i can tell, the theme's functions.php file isn't being executed, so redux isn't getting loaded.

What am I missing?
