### ISSUE TITLE
Disable localization loading

### ISSUE THREAD

**Issue by SirDarcanos** [reduxframework/redux-framework#988]
How can i disable the framework locales loading inside a theme?

I'm using redux inside a theme so i need my textdomain to be loaded instead of your. Codestyling will not find it.

**Comment by TuxReports** [comment]
I'd like to see a working example for plugins in the documentation. After months of trying different ways, nothing works to get codestyling localization to see anything but the redux-framework textdomain. Worse, using add_action('init', 'languages') prior to loading the admin (loaded using add_action('plugin_loaded') ) should work but fails - so I must be misunderstanding the statement not to use a hook. After all, WordPress documentation states, "Also load_plugin_textdomain calls should be made during init, otherwise users cannot hook into it."

http://codex.wordpress.org/Plugin_API/Action_Reference/init
